### ISSUE TITLE
vault_token should not ForceNew for pgp_key field

### ISSUE THREAD

**Issue by mitsutaka** [hashicorp/terraform-provider-vault#1000]
### Terraform Version
```
$ terraform -v
Terraform v0.14.8
```
But it is not related to terraform core itself.

### Affected Resource(s)
- `vault_token`

### Terraform Configuration Files
```hcl
resource "vault_token" "example" {
  policies   = ["example"]
  no_parent  = true
  renewable  = true
  period     = "168h"
  pgp_key    = data.vault_generic_secret.gpg-key.data["public_key_base64"]
}
```

I'm using https://github.com/LeSuisse/vault-gpg-plugin for managing GPG key pair in the Vault. and also customize it to expose base64 formatted GPG public key because `vault_token` expects base64 format for `pgp_key` field. This is the case that pgp_key refers a value from data source. Since using data source "will be updated in-place" even the value is same as current state. the `vault_token` resource will be destroyed/created every apply. It won't be affected If I use static pgp_key value like reading a file contains base64 GPG public key(e.g. `file()`). Assuming it's being read from a data source, `ForceNew: true` is a bit rough and I don't think it should be recreated a token every time, even if it hasn't expired.

### Actual Behavior
`pgp_key` has drift detection and be marked as forces replacement, therefore resource `vault_token` must be re-created.

### Steps to Reproduce
1. `terraform apply`

**Comment by fairclothjm** [comment]
`pgp_key` was removed in v3 of the provider
