### ISSUE TITLE
vault_jwt_auth_backend_role resource does not support lists as bound_claims values

### ISSUE THREAD

**Issue by ofayans** [hashicorp/terraform-provider-vault#1019]
### Terraform Version
0.12.0
### Affected Resource(s)
- vault_jwt_auth_backend_role

### Terraform Configuration Files
```
resource "vault_jwt_auth_backend_role" "gitlab" {
  depends_on      = [vault_generic_endpoint.jwt_config]
  backend         = "jwt"
  role_name       = "gitlab"
  bound_audiences = ["https://vault.ourdomain.com"]
  bound_claims = {
    "ref_type" = [
      "tag",
      "branch",
      "commit"
    ]
  }
  bound_claims_type = "glob"
  token_policies = [
    vault_policy.integration_apigee_ro.name,
    vault_policy.apigee_deployer.name,
    vault_policy.access_terraform_provider.name,
    vault_policy.infosec.name
  ]
  user_claim = "git.ourdomain.com"
  role_type  = "jwt"
}
```

### Debug Output
```
Provisioning vault env

Error: Incorrect attribute value type

  on vault.tf line 75, in resource "vault_jwt_auth_backend_role" "gitlab":
  75:   bound_claims = {
  76:     "ref_type" = ["tag",
  77:       "branch",
  78:       "commit"
  79:     ]
  80:   }

Inappropriate value for attribute "bound_claims": element "ref_type": string
required.
```
### Expected Behavior
According to [vault's documentation](https://www.vaultproject.io/api-docs/auth/jwt#bound_claims), the bound claims values may be a single string or a list of strings. 

### Actual Behavior

Obviously, current vault provider only supports string values

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by v1ctorrhs** [comment]
Also valid with terraform `1.0.0` and provider `2.23.0`

**Comment by tvoran** [comment]
Hi folks, in this case you'll want to use a comma-separated string list. i.e.

```hcl
bound_claims = {
    "ref_type" = "tag,branch,commit"
  }
```

I've attempted to clarify the [provider docs for that parameter](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role#bound_claims) in #1171.
