### ISSUE TITLE
Force delete all versions of a secret during destroy

### ISSUE THREAD

**Issue by vishmit123** [hashicorp/terraform-provider-vault#1020]
### Affected Resource(s)
vault_generic_secret

Feature request

is there a way to force delete all versions of a secret during destroy? Currently, it destroys only the latest version.

**Comment by briananstett** [comment]
I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-vault/issues/760

**Comment by benashz** [comment]
Closing as a duplicate of #760
