### ISSUE TITLE
Missing openldap secrets engine

### ISSUE THREAD

**Issue by TrueTechy** [hashicorp/terraform-provider-vault#1048]
Hi there, I'm running the latest terraform and vault provider and I can't find anything on configuring the openldap secrets engine for an OpenLDAP server. 

There is the AD resources which I'd imagine is using the same secrets engine but configured for AD schema https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/ad_secret_backend

The vault API documentation for this shows the option to configure the openldap schema via the API https://www.vaultproject.io/api-docs/secret/openldap

Is there currently any work / discussion underway around this feature being implemented in the provider?

**Comment by KristianFJones** [comment]
At the very least a generic secrets backend resource would be useful, I was just about to configure my OpenLDAP instance via Terraform. I'd be willing to try to make a PR either for OpenLDAP or a generic secrets backend resource if necessary.

**Comment by TrueTechy** [comment]
Looks like this was added in #1859
