### ISSUE TITLE
VAULT_NAMESPACE does not work

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/terraform-provider-vault#1056]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
terraform -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/vault v2.20.0

### Affected Resource(s)
vault provider

### Terraform Configuration Files
```hcl
provider "vault" {
    address = "http://vault-cluster1:8200"
    token="s.lf1Ck2j5JeLqVfccsfJDiaK7"
}

resource "vault_mount" "example" {
  path        = "dummy"
  type        = "kv-v2"
  description = "This is an example mount"
}

```

### Debug Output
https://gist.github.com/ausmartway/3b92744015164a3410ab45e58a0a0f95#file-broken-trace

### Expected Behavior
I expect vault provider to work with enviroment variable VAULT_NAMESPACE, it should work exactly the same as setting namespace in the provider config block.

### Good Behavior 

Code:
```hcl
provider "vault" {
    address = "http://vault-cluster1:8200"
    token="s.lf1Ck2j5JeLqVfccsfJDiaK7"
    namespace="/anzse"
}

resource "vault_mount" "example" {
  path        = "dummy"
  type        = "kv-v2"
  description = "This is an example mount"
}

```
### Trace log from good:
https://gist.github.com/ausmartway/3b92744015164a3410ab45e58a0a0f95#file-working-trace

### Actual Behavior
vault provider tries to create a child token to use, but but failed to inherit the policy.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. vault namespace create anzse
2. terraform init
3. VAULT_NAMESPACE=/anzse TF_LOG=trace terraform apply -auto-approve

### Important Factoids
I am using root token in both tests.

**Comment by tvoran** [comment]
Thanks for the detailed report! I see the same behavior, even going back to v2.0.0 of the provider, so it looks like it's been around for a while. We'll take a look.

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 Support for setting the namespace parameter using the environment variable was added to the TFVP in [v3.7.0](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.7.0). Going to close this issue, but please feel free to open another one if you face any other problems! Thanks again :)
