### ISSUE TITLE
error while downloading the vault plugin

### ISSUE THREAD

**Issue by akshat87** [hashicorp/terraform-provider-vault#1058]
Terraform Version
0.11.1

Terraform Configuration Files

provider "vault" {
  address   = "....."
  namespace = "...."

  auth_login {
    path      = "auth/approle/login"
    namespace = "...."
    parameters = {
      role_id   = "...."
      secret_id = "...."
    }
  }
}

Output
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

 

2021/05/20 13:58:25 [ERROR] 1 error(s) occurred:

 

* openpgp: signature made by unknown entity
2021/05/20 13:58:25 [DEBUG] plugin: waiting for all plugin processes to complete...
Error installing provider "vault": openpgp: signature made by unknown entity.

Expected Behavior
The plugin should not have crashed. An errors should have been reported instead.

Actual Behavior
It failed to download due to certificate issue

Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

terraform init

**Comment by tvoran** [comment]
Hi there, I think the solution is to update terraform to 0.11.15. More details here: https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570
