### ISSUE TITLE
Resources should support individual target namespaces

### ISSUE THREAD

**Issue by defreng** [hashicorp/terraform-provider-vault#1063]
Hi there,

I'm having some trouble with using the vault provider in a setup like the following:

> The plan is to create a reusable terraform module, which creates a child namespace and performs initial setup of this namespace (e.g. some default auth methods and secret backends).

This module would obviously receive an instance of the root namespace vault provider config, and then use the `vault_namespace` resource to create a child namespace.

Unfortunately, if I'm not mistaken this is not possible with the current design of the vault provider, where the namespace is a provider config option. Because to create resources within the new namespace, a new vault provider must be configured with that namespace.

### Why is that an issue?
Terraform discourages setting up new provider configurations in child modules.
https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations

Doing so will lead to issues with missing features (count, for_each) and often makes it impossible to easily remove the module from a terraform state (provider configs must only be removed after all resources using them are removed).

### Solution Idea
The idea which came to my mind (besides making terraform more versatile ;-) ) was to add an additional attribute `namespace` to every vault resource type. So it can be used with the provider configured for the parent namespace.

For example, if the parent provider namespace is set to `admin/` and the resource attribute is set to `namespace = "dev"`, that resource would be created in the `admin/dev` namespace.

### Terraform Version
0.15

**Comment by tristanmorgan** [comment]
This sounds like a good solution to me. I just got hit with the following error because this feature isn't available...
```
Providers cannot be configured within modules using count, for_each or depends_on.
```
The use case is I want to use a standardised module to create sub-namespaces and use a count or for_each to drive this.

**Comment by FalcoSuessgott** [comment]
I am facing the same problem trying to create namespaces and its subnamespace by iterating over a list objects using terraform.

I like @defreng approach and would love some feedback from Hashicorp whether this could be something they would like to see.:)

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 Support for setting the `namepsace` parameter by resource was added to the TFVP in [v3.7.0](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.7.0). Going to close this issue, but please feel free to open another one if you face any other problems! Thanks again :)
