### ISSUE TITLE
vault_aws_secret_backend_role doesn't support specifying iam_tags

### ISSUE THREAD

**Issue by olafz** [hashicorp/terraform-provider-vault#1073]
Hi there,

Vault supports the `iam_tags` option when creating dynamic AWS roles (see https://www.vaultproject.io/api/secret/aws#iam_tags). Unfortunately, the Terraform Vault provider doesn't support this (see https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/aws_secret_backend_role), similar to the `permissions_boundary_arn` referenced in https://github.com/hashicorp/terraform-provider-vault/issues/716 (also supported in Vault but not in the Terraform provider for Vault).

Any chance that the Vault provider for Terraform can stay relatively in sync with the features in Vault?

For this particular issue, I'm happy to open a PR if that helps.

**Comment by pporee** [comment]
Hello,

Any news on this issue, we can't propagate tag to the user created by Vault.

Regards

**Comment by Shocktrooper** [comment]
Hello! I am interested in this because it will allow us to use AWS policy variables in our IAM policies.  Without this we cannot do that and thus cannot use AWS Policy variables based off of tags
- https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html
