### ISSUE TITLE
Plugin crash! 2.20.0_x4 can't add groups with "vault_identity_group" resource

### ISSUE THREAD

**Issue by mister2d** [hashicorp/terraform-provider-vault#1079]
### Terraform Version
Terraform 1.0.0

### Vault Version
Vault 1.7.2

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_identity_group

### Terraform Configuration Files
```hcl
resource "vault_identity_group" "vault-admin" {
  name     = "vault-admin"
  type     = "internal"
  policies = ["all-access"]

  metadata = {
    roles = "vault-admin"
  }
}

resource "vault_identity_group" "vault-pki" {
  name     = "vault-admin"
  type     = "internal"
  policies = ["pki-user"]

  metadata = {
    roles = "vault-pki"
  }
}

resource "vault_identity_group" "vault-ssh-user" {
  name     = "vault-user"
  type     = "internal"
  policies = ["ssh-user"]

  metadata = {
    roles = "vault-user"
  }
}

resource "vault_identity_group" "vault-ssh-host" {
  name     = "vault-ssh-host"
  type     = "internal"
  policies = ["ssh-host"]

  metadata = {
    roles = "vault-ssh-host"
  }
}

resource "vault_identity_group" "kv-v1-all" {
  name     = "kv-v1-all"
  type     = "internal"
  policies = ["kv-v1"]

  metadata = {
    roles = "kv-v1-all"
  }
}
```

### Debug Output
https://gist.github.com/mister2d/fb964b4dd74f992fbbfeefe666d1a6ac#file-terraform_vault_debug-txt

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Expected Terraform to create internal Vault groups for Auth0 OIDC linking.

### Actual Behavior
What actually happened?

"The terraform-provider-vault_v2.20.0_x4 plugin crashed!"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

No.

**Comment by jeffsanicola** [comment]
I've run into similar issues before. As a work around I believe you can add the `-parallelism=1` option to your Terraform apply command. It would be nice to not have to do that but it should get you further if this is blocking.

**Comment by mister2d** [comment]
> I've run into similar issues before. As a work around I believe you can add the `-parallelism=1` option to your Terraform apply command. It would be nice to not have to do that but it should get you further if this is blocking.

Tried with `-parallelism=1` and it crashes the same. :(

**Comment by mister2d** [comment]
FYI, this still exists in 2.21.0.

**Comment by jeffsanicola** [comment]
I did a little more testing and was able to replicate your issue.

First thing I noticed while testing is that you have a duplicate group name:
```
resource "vault_identity_group" "vault-admin" {
  name     = "vault-admin" # <-- vault-admin
  type     = "internal"
  policies = ["all-access"]

  metadata = {
    roles = "vault-admin"
  }
}

resource "vault_identity_group" "vault-pki" {
  name     = "vault-admin" # <-- vault-admin
  type     = "internal"
  policies = ["pki-user"]

  metadata = {
    roles = "vault-pki"
  }
}
```

When I run an apply with the code as provided I get the same error.
When I change the `vault-pki` group name to something unique (vault-pki) I still get the error.
However, I get the error because the groups were already created in Vault but nothing was recorded in TF state.
If I manually delete the groups and run the corrected file then the plan and apply works as expected.

I think this bug distills down to an issue that existing groups aren't read to check for duplicates before attempting to create.

@mister2d - Can you confirm that what I've experienced here matches your experience?

**Comment by mister2d** [comment]
@jeffsanicola I can confirm that it works. This is what I get for copy/pasting code. Thanks for the second pair eyes!
