### ISSUE TITLE
Feature Request: Raft auto snapshots (`/sys/storage/raft/snapshot-auto`)

### ISSUE THREAD

**Issue by bbayszczak** [hashicorp/terraform-provider-vault#1083]
### Raft auto snapshots

There is the following endpoint in Vault API which allows Vault to create Raft snapshots and push them to a cloud storage.

I can't find implemented in the Terraform provider

https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots

Is this something already on the roadmap on your side ?

Thanks 🙂

**Comment by mbillow** [comment]
FYI: I added this in #1139. You just need to update your provider to 2.24.1. 😄 

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/raft_snapshot_agent_config

**Comment by vinay-gopalan** [comment]
Hi! Thanks for opening this Feature Request. As mentioned in a comment above, a resource for Raft Snapshot Agent Config was added in v2.24.1. 

Closing this issue, but please feel free to open up another in case you face any problems with the resource. Thanks!
