### ISSUE TITLE
Root resource was present, but now absent.

### ISSUE THREAD

**Issue by julianxhokaxhiu** [hashicorp/terraform-provider-vault#1093]
Hi,

Upon creating a generic Vault secret, although the resource seems to be created successfully this error did show up:
```sh
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to vault_generic_secret.test_secret, provider
│ "provider[\"registry.terraform.io/hashicorp/vault\"]" produced an unexpected new value: Root resource was present,
│ but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```sh
➜ terraform -v
Terraform v1.0.2
on linux_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_generic_secret

### Terraform Configuration Files
```hcl
resource "vault_generic_secret" "test_secret" {
  path = "kv/secret/project/test"

  data_json = <<EOT
{
  "foo":   "bar",
}
EOT
}
```

### Debug Output
N/A - If necessary I can provide it.

### Panic Output
N/A - Didn't panic.

### Expected Behavior
Everything applies successfully and the error doesn't show up.

### Actual Behavior
Everything applied successfully but the error did show up.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Provider version: 2.21.0
Server version: 1.6.3 Enterprise

### References
N/A

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 Support for dedicated KV v1 and v2 resources was added to the TFVP in [v3.7.0](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.7.0). We recommend using those resources and data sources to manage the lifecycle of your KV secrets over the Generic Secret resource. Going to close this issue, but please feel free to open another one if you face any other problems! Thanks again :)
