### ISSUE TITLE
vault_kubernetes_auth_backend_role documentation error

### ISSUE THREAD

**Issue by ludydoo** [hashicorp/terraform-provider-vault#1100]
Issue in the `vault_kubernetes_auth_backend_role` documentation

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/kubernetes_auth_backend_role

Current value

```
token_num_uses - (Optional) The period, if any, in number of seconds to set on the token.
```

Should probably be

```
token_num_uses (integer: 0) - The maximum number of times a generated token may be used (within its lifetime); 0 means unlimited. If you require the token to have the ability to create child tokens, you will need to set this value to 0.
```

See https://www.vaultproject.io/api/auth/approle

**Comment by vinay-gopalan** [comment]
Hi, thanks for raising the issue and apologies for the delay in responding! 🙏🏼 This no longer seems to be an issue in the latest version of the documentation, so going to close this issue. Please feel free to open an issue if you face any other problems, thanks again! :)
