### ISSUE TITLE
Migrate to terraform-plugin-sdk/v2

### ISSUE THREAD

**Issue by xescugc** [hashicorp/terraform-provider-vault#1104]
I left the template headers but it does not fit with them.

Basically Terraform released a while back the v2 of the sdk https://github.com/hashicorp/terraform-plugin-sdk and I was wondering if this Provider was intending to migrate to it.

I'll work on a PR for it as I need it for a project I'm working on. I'll open the PR to this repo too just in case it's wanted. Sometimes this changes are big and require some more internal testing that's why I'm asking beforehand too hehe.

**Comment by tvoran** [comment]
Addressed in https://github.com/hashicorp/terraform-provider-vault/pull/1175
