### ISSUE TITLE
Terraform plan fails with "Error: missing expected [" after migration from v2.21.0 to v2.22.0

### ISSUE THREAD

**Issue by iusergii** [hashicorp/terraform-provider-vault#1113]
Hi Team, 

After migration from v2.21.0 to v2.22.0 I got the error message: `Error: missing expected [` on `terraform plan. 

### Terraform Version
```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/vault v2.22.0
```
### Affected Resource(s)
I can't definitely identify what resource is causing it but my best guess from the log:
- vault_aws_secret_backend_role

Would appreciate any advice on how to find them.

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend_role" "replaced_name" {
  backend         = vault_aws_secret_backend.aws.path
  name            = "replaced_name"
  credential_type = "iam_user"
  policy_arns     = [
    format("arn:aws:iam::%s:policy/exisitng-policy", var.aws_account_id)
  ]
  policy_document = templatefile("${path.module}/templates/inline_policy.json", {
    aws_account_id = var.aws_account_id
    region = var.region
  })
}

```

### Debug Output
The only one error I can see in output:
```
2021-07-23T17:59:48.057Z [DEBUG] provider.terraform-provider-vault_v2.22.0_x4: 2021/07/23 17:59:48 [ERROR] Version of "policy_document" in state is not valid JSON: unexpected end of JSON input
```
From what I can see I have a valid JSON in my state file in the policy_document field.

**Comment by benashz** [comment]
Hi @iusergii , we are currently investigating this issue. The fix is being tracked in #1112.

Thanks,

Ben

**Comment by jasonodonnell** [comment]
@iusergii v2.22.1 was released which reverted this commit. Please upgrade to this latest version to remove this error. Sorry for the inconvenience!

**Comment by iusergii** [comment]
@jasonodonnell thank you. Closing this.
