### ISSUE TITLE
Should AppRole resource ensure vault path uniqueness?

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/terraform-provider-vault#112]
```
resource "vault_approle_auth_backend_role" "approle_test" {
  backend   = "${var.approle_path}"
  role_name = "approle_test"
  policies  = ["default"]

  #bound_cidr_list = [""]
  token_ttl     = "300"
  token_max_ttl = "900"
}

resource "vault_approle_auth_backend_role" "approle_test_2" {
  backend   = "${var.approle_path}"
  role_name = "approle_test"
  policies  = ["default"]

  #bound_cidr_list = [""]
  token_ttl     = "300"
  token_max_ttl = "900"
}
```

Should AppRole check for path uniqueness, rather than just terraform resource uniqueness?

I am trying to ensure that we don't accidentally overwrite an AppRole (and any other resources) but I am finding a lot of the resources don't check before just writing over each other.

Anyone have any examples of doing Terraform and Vault another way to ensure uniqueness of paths either with a module or something else?

**Comment by fairclothjm** [comment]
We recommend appending a random value to any role name to prevent unwanted overwrites. See https://registry.terraform.io/providers/hashicorp/random/latest/docs
