### ISSUE TITLE
Feature: add support for enabling & configuring the MongoDB Atlas Secrets Engine with provider

### ISSUE THREAD

**Issue by iniinikoski** [hashicorp/terraform-provider-vault#1124]
Long story short: Vault has supported the MongoDB Atlas Secrets Engine quite along time already (since April 2020):

https://www.mongodb.com/blog/post/manage-atlas-database-secrets-hashicorp-vault
https://www.vaultproject.io/docs/secrets/mongodbatlas
https://www.mongodb.com/atlas/hashicorp-vault
https://docs.atlas.mongodb.com/partner-integrations/#hashicorp-vault

, but, unfortunately, the Vault provider seems still missing support for it. This makes the feature quite unusable considering production quality setup.

**Comment by nick-augustine** [comment]
@benashz are there any plans or blockers for support of the MongoDB Atlas Secrets Engine ?

**Comment by vinay-gopalan** [comment]
Hi, thanks for raising this issue and apologies for the delay! 🙏🏼 Support for the MongoDB Atlas Secrets Engine was released in [v3.15.0](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.15.0). Closing this issue for now, but please feel free to open another one if you face any problems with any of the resources. Thanks again :)
