### ISSUE TITLE
Create policy document rule on condition true

### ISSUE THREAD

**Issue by dil-kpogany** [hashicorp/terraform-provider-vault#1135]
Hi,

Is there a way to create policy documents in a way that some rules are only included if a bool is set to true?

for example: 
I have a module that creates policies and policy documents as below:
I would pass a bool variable named enable_metadata_rule and based on it's value I would create the 2nd rule or not:

```
resource "vault_policy" "example_policy" {
  for_each = var.environments
  provider = vault
  name     = "${var.team}-${var.application}-${each.key}"
  policy   = data.vault_policy_document.policy_document["${each.key}"].hcl
}

data "vault_policy_document" "policy_document" {
  for_each = var.environments
  rule {
    path         = "engines/${var.team}-kv/data/${each.key}/services/${var.application}/*"
    capabilities = ["read", "list"]
    description  = "Read secrets for ${var.application}"
  }
  rule {
    # IF  enable_metadata_rule == true
    path         = "engines/${var.team}-kv/metadata/*"
    capabilities = ["list"]
    description  = "List metadata for kv store"
  }
}
```
If there isn't such thing, is there an option for merging separately created policy documents?

**Comment by jeffsanicola** [comment]
You can use the `join` command to combine multiple policies and a conditional test to determine whether to join them.

Not sure if this will work out straight away but this may be along the lines of what you're after.

```hcl
resource "vault_policy" "example_policy" {
  for_each = var.environments
  provider = vault
  name     = "${var.team}-${var.application}-${each.key}"
  policy   = enable_metadata_rule == true ? join("\n", [data.vault_policy_document.policy_document["${each.key}"].hcl, data.vault_policy_document.policy_document2["${each.key}"].hc]) : data.vault_policy_document.policy_document["${each.key}"].hcl 
}

data "vault_policy_document" "policy_document" {
  for_each = var.environments
  rule {
    path         = "engines/${var.team}-kv/data/${each.key}/services/${var.application}/*"
    capabilities = ["read", "list"]
    description  = "Read secrets for ${var.application}"
  }
}

data "vault_policy_document" "policy_document2" {
  for_each = var.environments
  rule {
    # IF  enable_metadata_rule == true
    path         = "engines/${var.team}-kv/metadata/*"
    capabilities = ["list"]
    description  = "List metadata for kv store"
  }
}
```

**Comment by mbillow** [comment]
You could do this with [Dynamic blocks](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html).

It would look something like: 
```hcl
data "vault_policy_document" "policy_document" {
  for_each = var.environments
  rule {
    path         = "engines/${var.team}-kv/data/${each.key}/services/${var.application}/*"
    capabilities = ["read", "list"]
    description  = "Read secrets for ${var.application}"
  }
  dynamic "rule" {
    // Dynamic blocks only support for_each, so we just pass in a map with zero or one key(s).
    for_each = var.enable_metadata_rule ? {enabled: true} : {}
    content {
      path         = "engines/${var.team}-kv/metadata/*"
      capabilities = ["list"]
      description  = "List metadata for kv store"
    }
  }
}
```

**Comment by dil-kpogany** [comment]
> You could do this with [Dynamic blocks](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html).
> 
> It would look something like:
> 
> ```terraform
> data "vault_policy_document" "policy_document" {
>   for_each = var.environments
>   rule {
>     path         = "engines/${var.team}-kv/data/${each.key}/services/${var.application}/*"
>     capabilities = ["read", "list"]
>     description  = "Read secrets for ${var.application}"
>   }
>   dynamic "rule" {
>     // Dynamic blocks only support for_each, so we just pass in a map with zero or one key(s).
>     for_each = var.enable_metadata_rule ? {enabled: true} : {}
>     content {
>       path         = "engines/${var.team}-kv/metadata/*"
>       capabilities = ["list"]
>       description  = "List metadata for kv store"
>     }
>   }
> }
> ```

Thanks, this worked. :)
