### ISSUE TITLE
Unsupported auth methods don't fail properly

### ISSUE THREAD

**Issue by dpogorzelski** [hashicorp/terraform-provider-vault#1163]
### Terraform Version
```
1.0.5
```

### Affected Resource(s)
- provider configuration

### Terraform Configuration Files
```hcl
provider "vault" {
  address   = "someaddr"
  namespace = "somenamespace"

  auth_login {
    path      = "auth/gcp/login"
    namespace = "somenamespace"
    method    = "gcp"
    parameters = {
      type = "gce"
      role = "somerole"
    }
  }
}
```

### Debug Output
```
Error: Error making API request.

URL: PUT https://vault:8200/v1/auth/gcp/login
Code: 400. Errors:

* missing client token
```

### Expected Behavior
The provider should be more explicit/fail properly when an unsupported `method` is supplied

### Actual Behavior
The provider fails to authenticate and returns a very not clear reason

**Comment by benashz** [comment]
Using the dedicated `auth_login_*` will resolve this issue.  The `auth_login` generic resource will accept whatever is provided in terms of auth method. Unknown method errors will bubble up from Vault itself. This is the expected behavior in this case.
