### ISSUE TITLE
Cannot Create Azure Auth Backend Config with custom path having "/"

### ISSUE THREAD

**Issue by infa-niksingh** [hashicorp/terraform-provider-vault#1186]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.0.7
on darwin_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_azure_auth_backend_config

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
This issue is only with the above provider. Other resources are working fine. 

### Terraform Configuration Files
```hcl

terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "= 2.24.0"
    }
  }
}

provider "vault" {
}


resource "vault_auth_backend" "isaas_azure_informatica_auth_backend" {
  type        = "azure"
  path        = "azure/isaas/informatica"
  description = "This auth method will allow Azure Informatica entities to access vault."
  local       = false

  tune {
    default_lease_ttl            = "3600s"
    max_lease_ttl                = "14400s"
    listing_visibility           = "hidden"
    token_type                   = "batch"
  }
}

resource "vault_azure_auth_backend_config" "isaas_azure_informatica_auth_backend_config" {
  backend       = vault_auth_backend.isaas_azure_informatica_auth_backend.path
  tenant_id     = var.azure_informatica_auth_backend_tenant_id
  client_id     = var.azure_informatica_auth_backend_client_id
  client_secret = var.azure_informatica_auth_backend_client_secret
  resource      = "https://management.azure.com"
  environment   = "AzurePublicCloud"
}
```

### Debug Output
https://gist.github.com/infa-niksingh/e873383b922470cc7ae51536c67a1789

### Expected Behavior
Resource **vault_azure_auth_backend_config** should write the provided config to vault at the given path. 
I am able to use vault CLI to write config to vault. 

### Actual Behavior
Error: expected "auth/azure/isaas/informatica/config" to have 4 pieces, has 5. 
I get below error message when I change path from  **azure/isaas/informatica** to **azure/informatica**
Error: expected "auth/azure/informatica/config" to have 4 pieces, has 4. 

Vault CLI works fine for both of these:
```bash
❯ vault write auth/azure/isaas/informatica/config \
    tenant_id=${TF_VAR_azure_informatica_auth_backend_tenant_id} \
    resource=https://management.azure.com \
    client_id=${TF_VAR_azure_informatica_auth_backend_client_id} \
    client_secret=${TF_VAR_azure_informatica_auth_backend_client_secret}
Success! Data written to: auth/azure/isaas/informatica/config
❯ vault read auth/azure/isaas/informatica/config
Key            Value
---            -----
client_id      #####
environment    AzurePublicCloud
resource       https://management.azure.com
tenant_id      #####
```

If I change path from **azure/isaas/informatica** to **azure_informatica** or  **azure-informatica**, then it works fine. 
It looks like, the resource does not work when there's a **_/_** in the path.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 
I was not able to find any reported issues for this resources.

**Comment by infa-niksingh** [comment]
I think the issue might be with this condition:

https://github.com/hashicorp/terraform-provider-vault/blob/c534482f73e03315885b4bba29623c8f36e98f41/vault/resource_azure_auth_backend_config.go#L117

**Comment by rjhornsby** [comment]
```
	if len(idPieces) != 3 {
		return fmt.Errorf("expected %q to have 4 pieces, has %d", d.Id(), len(idPieces))
	}
```

I'm sure there was a reason for this check, but since vault itself does not enforce such a strict path depth, it's unclear why the check is necessary in the first place - or how the magic numbers `3` and `4` were arrived at.

> there might also be an off-by-one error 

Right. The condition uses `3` but the error string says `4` - so definitely seems like a conflict to me.

**Comment by revanthalampally** [comment]
Still seeing the error with Terraform v1.4.4 and provider registry.terraform.io/hashicorp/vault v3.15.0
│ Error: expected "auth/pod/dc709249/config" to have 4 pieces, has 4
