### ISSUE TITLE
token recreated after expiry - a way to let it rest in peace?

### ISSUE THREAD

**Issue by rmalchow** [hashicorp/terraform-provider-vault#1206]
we're using terraform to provision various types of machines. most of these machines will sooner or later need some way to authenticate themselves to other machines. to do this, we are using a custom pki in hashicorp vault.

our plan was to create a short lived, single-use token injected into the userdata of a new machine that allows the issuing of the initial machine certificate, and then use the machine certificate for any future authentication.

as of now, we're using the terraform vault provider to create the role and token in vault, and this works well. from the userdata, we can issue the first certificate, and then we have a perfectly good way of reliably authenticating the machine.

the trouble is that the hashicorp vault provider sees the tokens expiry and/or the fact that it has been used and creates a new token every single time. this means that there would be many, many single-use tokens created that eventually expire, but could be used to issue a certificate for that machine, but we have no way of noticing. 

we did try to use the lifecycle argument on the vault token - to no effect. 

what we _would_ like to see is some way to say "no recreate" - so that in order to generate a new one, you would have to _destroy_ the old one (and possibly the machine) first.

any ideas on how to achieve this? 

### Terraform Version

Terraform v1.0.3
on linux_amd64

hashicorp/vault v2.24.1

```
resource "vault_token" "vault_token" {
  depends_on  = [null_resource.test]
  count     = local.settings.amount
  policies  = [vault_policy.vault_policy[count.index].name]
  renewable = false
  ttl       = "1h"
  num_uses  = 1
}

```

### Expected Behavior
some way not recreating the token every time.

### Actual Behavior
after a token has expired, a new token is created on every "apply"

### Important Factoids
we do want the option to let it expire. we only actually need the token once.

**Comment by benashz** [comment]
Hi @rmalchow , I might be mistaken here, but I think the [skip_child_token](https://registry.terraform.io/providers/hashicorp/vault/latest/docs#skip_child_token) feature may match up with your use-case.

Please re-open this issue if it does not address your needs, and we can take a closer look.

Thanks,

Ben
