### ISSUE TITLE
vault_policy_document missing support for `patch` capability introduced in Vault 1.9.0

### ISSUE THREAD

**Issue by aleksejspopovs** [hashicorp/terraform-provider-vault#1227]
### Terraform Version
```
Terraform v0.12.31
+ provider.vault v2.24.1
```

(yes, I know it is out of date, but that is not the issue here)

### Affected Resource(s)
- vault_policy_document

### Terraform Configuration Files
```hcl
provider "vault" {
  version = "~> 2.0"
}

data "vault_policy_document" "policy" {
  rule {
    path         = "secret/hello"
    capabilities = ["patch"]
  }
}
```

### Debug Output
https://gist.github.com/aleksejspopovs/324e6f841b0ca3fbd41986f35da1cf30

The interesting bit is this:

```
Error: invalid capability: "patch" in: rule.0.capabilities.0

  on main.tf line 5, in data "vault_policy_document" "policy":
   5: data "vault_policy_document" "policy" {
```

### Expected Behavior
A policy document should be generated containing [the `patch` capability](https://github.com/hashicorp/vault/blob/6f65a4addcee1b18578fdf8ca0d4122a3674cea9/vault/policy.go#L29).

### Actual Behavior
The provider throws an error, because [the `capabilityValidation` function](https://github.com/hashicorp/terraform-provider-vault/blob/70c272b64a136d02c109f28ef2cae538f155b325/vault/data_source_policy_document.go#L195) checks capabilities against [a hardcoded allowlist](https://github.com/hashicorp/terraform-provider-vault/blob/70c272b64a136d02c109f28ef2cae538f155b325/vault/data_source_policy_document.go#L30) that does not include `patch`.

### Steps to Reproduce
1. `terraform apply`

**Comment by aleksejspopovs** [comment]
Sorry, hadn't realized v3.0.0 of the provider was out when creating the report, but this issue is also present there.

**Comment by benashz** [comment]
@aleksejspopovs thanks for reporting this. We are aware that there are still some 1.9 features not yet present in the provider. Patch support and others will be added to the v3 series in the near future. 

The 2.x series of the Vault Provider is now in maintenance mode. It will only receive critical fixes on a case by case basis. All new feature development has been moved to the 3.x series of the provider. Please see the [3.0.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/guides/version_3_upgrade) for more details.
