### ISSUE TITLE
Revert removal of vault_ad_secret_backend options in #1207

### ISSUE THREAD

**Issue by maxb** [hashicorp/terraform-provider-vault#1253]
Please could you revert the removal of the `formatter` and `length` parameters from `vault_ad_secret_backend` in #1207 ?

Whilst Vault is trying to push people towards use of password policies, they are overcomplicated and unnecessary for many common cases, and are unable to fully represent the previous behaviour, which included the static prefix `?@09AZ` in every password (or, using `formatter`, custom prefixes/suffices).

The presence of a specific string to mark a credential is a valuable technique to enable automated detection of carelessly hardcoded credentials in source control, and one I'd like to be able to continue to use.

**Comment by benashz** [comment]
Hi @maxb,

We are discussing this issue internally and will have some news for you shortly.

Thanks,

Ben

**Comment by benashz** [comment]
Hi @maxb,

Just wanted to let you know that we are going to move forward with re-adding support for the deprecated fields: `formatter` and `length`. They will still be marked as deprecated, so there is a chance that they may be removed in the future. In the meantime you should see them back in the upcoming v3.3.0 release.

Thanks,

Ben

**Comment by maxb** [comment]
Hi @benashz,

That's great, thanks.

Is there room for some further discussion on whether marking them deprecated in terraform-provider-vault is the best approach?

Terraform doesn't have any way to suppress warnings, and any warnings emitted during a plan/apply are moderately noisy in the TFE UI. That's great when the purpose of their existence is to nudge users towards fixing their code, but in this particular scenario, there's no fix available to achieve equivalent Vault behaviour with the non-deprecated options. To me, that detail, that the warnings aren't actionable by a user, is the critical differentiator.

**Comment by benashz** [comment]
> Hi @benashz,
> 
> That's great, thanks.
> 
> Is there room for some further discussion on whether marking them deprecated in terraform-provider-vault is the best approach?

Our preference is to keep the deprecations in line with their corresponding API endpoints, so I think we should continue in the same vein here.             

> 
> Terraform doesn't have any way to suppress warnings, and any warnings emitted during a plan/apply are moderately noisy in the TFE UI. That's great when the purpose of their existence is to nudge users towards fixing their code, but in this particular scenario, there's no fix available to achieve equivalent Vault behaviour with the non-deprecated options. To me, that detail, that the warnings aren't actionable by a user, is the critical differentiator.

I will take a closer look to see if there is way to suppress deprecation warnings from Terraform. If not, we can probably open a PR to address that.

Internally, we are going to take a closer look to see how password policies could be used to provide better parity with `formatter` and `length`.
