### ISSUE TITLE
Why resource vault_approle_auth_backend_role is missing the policies field

### ISSUE THREAD

**Issue by FalcoSuessgott** [hashicorp/terraform-provider-vault#1260]
Hi,

I can see that https://github.com/hashicorp/terraform-provider-vault/pull/1181 removed `policies` from resource `vault_approle_auth_backend_role`. 

I would like to understand why and how I am now supposed to map policies to certain approle roles?

Thanks in advance

### Terraform Version
Terraform v1.1.0
Provider 3.0.1

### Affected Resource(s)
Please list the resources as a list, for example:
- `vault_approle_auth_backend_role`

**Comment by FalcoSuessgott** [comment]
Using Vault provider `2.24.1` states: 

`"policies": [DEPRECATED] use `token_policies` instead if you are running Vault >= 1.2`

but field `token_policies` is not present in resource `vault_approle_auth_backend_role`

**Comment by FalcoSuessgott** [comment]
@hsimon-hashicorp 
If the field has been removed by accident I can happily create a PR :)

**Comment by benashz** [comment]
Hi @FalcoSuessgott , we're taking a closer look at this issue now. Stay tuned!

**Comment by benashz** [comment]
Hi @FalcoSuessgott , would you mind providing us with error message and a sample of the offending Terraform code?

You should be able to specify the `token_policies` per the example [here](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/approle_auth_backend_role#example-usage)

Thanks,

Ben

**Comment by FalcoSuessgott** [comment]
Ah I see, yes token_policies should work.:)

Nevertheless the docs at this page needs to be updated: 

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/approle_auth_backend_login

**Comment by benashz** [comment]
> Ah I see, yes token_policies should work.:)

Excellent!

> 
> Nevertheless the docs at this page needs to be updated:
> 
> https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/approle_auth_backend_login

Good catch!
