### ISSUE TITLE
database_secret_backend_connection resource missing `plugin_name` field.

### ISSUE THREAD

**Issue by chperie** [hashicorp/terraform-provider-vault#1288]
Hello,

 I need to create the oracle database engine in Vault as mentionned in https://www.vaultproject.io/api/secret/databases/oracle
I plan to use Terraform and so :  resource "vault_database_secret_backend_connection"

but I can not use :
=> plugin_name  as a configuration parameter (and it's mandatory for Oracle) as it's not defined in the documentation  https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection

=> And under oracle arguments I also need to define username/password in order for Vault to define resources in the Oracle database but it's the same, the arguments don't exist  

do I have to use =>  resource "vault_generic_endpoint"  ?
Or Did I miss something?
Thanks for your help

**Comment by DrFaust92** [comment]
the oracle DB connection type is not (yet) supported in the provider. so this should be labels as enhancment/feature-parity.

**Comment by benashz** [comment]
@chperie we are going to take a closer look at this issue. Setting the Oracle db engine is supported per: https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection#oracle-configuration-options, but I see that we may be missing some of it's fields.

**Comment by DrFaust92** [comment]
Oops, sorry for misleading.

**Comment by benashz** [comment]
> the oracle DB connection type is not (yet) supported in the provider. so this should be labels as enhancment/feature-parity.

@DrFaust92 would you mind expanding on the above statement please. We should have Oracle support per: https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection#oracle-configuration-options

**Comment by benashz** [comment]
@chperie the use of `data` in your example above should not be needed. Are you encountering an error without it?

**Comment by chperie** [comment]
yes...

**Comment by benashz** [comment]
Would you mind providing the exact error message?

**Comment by chperie** [comment]
this kind of error
24:   plugin_name = "oracle-database-plugin_10_2"

An argument named "plugin_name" is not expected here.

**Comment by benashz** [comment]
We will take a closer look to see what the issue might be.
