### ISSUE TITLE
provider registry.terraform.io/hashicorp/vault" produced an invalid new value for m.delete_all_versions: was cty.False  but now nul

### ISSUE THREAD

**Issue by rosezafar** [hashicorp/terraform-provider-vault#1295]
Hi there

After the merge of PR  https://github.com/hashicorp/terraform-provider-vault/pull/1254 in version 3.1.0, all our resource code with vault_generic_secret started failing with below error.
**module.deploy_subscription_CF.vault_generic_secret.fn_functionkeys[0]
to include new values learned so far during apply, provider
registry.terraform.io/hashicorp/vault" produced an invalid new value for
m.delete_all_versions: was cty.False, but now null.**

### Terraform Version
1.0.2

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_generic_secret

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "vault_generic_secret" "func_id" {
  count = var.toggle_configure_infra_to_vault ? 1 : 0
  path       = "${local.vault_path_infra}/${var.functionapp.full_name}/function_id"
  data_json  = <<EOT
{"value": "${azurerm_function_app.fnapp.id}"}
EOT
}

### Debug Output
module.deploy_subscription_CF.vault_generic_secret.fn_functionkeys[0]
to include new values learned so far during apply, provider
registry.terraform.io/hashicorp/vault" produced an invalid new value for
m.delete_all_versions: was cty.False, but now null.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
It should update the secret in vault.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
No

**Comment by daviddob** [comment]
Can confirm we are seeing similar behavior with `3.1.1` as well.

**Comment by benashz** [comment]
We are currently looking into this issue. Thanks for reporting/confirming it @rosezafar @daviddob !

**Comment by daviddob** [comment]
For some additional context, we are targeting a vault kv v1 secret backend and seeing the following errors. Would be happy to prove additional information if necessary. 

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.azure_aks.vault_generic_secret.kube_config to include new values
│ learned so far during apply, provider
│ "registry.terraform.io/hashicorp/vault" produced an invalid new value for
│ .data_json: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.azure_aks.vault_generic_secret.kube_config to include new values
│ learned so far during apply, provider
│ "registry.terraform.io/hashicorp/vault" produced an invalid new value for
│ .delete_all_versions: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by benashz** [comment]
Thanks @daviddob. Would you mind providing us with a snippet of your TF code? 

Ben

**Comment by daviddob** [comment]
```hcl
resource "vault_generic_secret" "kube_config" {
  path = var.vault_secret_path
  data_json = jsonencode({
    cluster_name = "${azurerm_kubernetes_cluster.aks_cluster.name}"
    fqdn         = "${azurerm_kubernetes_cluster.aks_cluster.fqdn}"
    kube_config  = "${azurerm_kubernetes_cluster.aks_cluster.kube_config_raw}"
    private_fqdn = "${azurerm_kubernetes_cluster.aks_cluster.private_fqdn}"
  })
}

This is the generic resource definition inside our AKS module that is in question. Anything else regarding the tf code you're looking for?
```

**Comment by benashz** [comment]
> This is the generic resource definition inside our AKS module that is in question. Anything else regarding the tf code you're looking for?
> ```

No, I think what you posted is good enough for now. Thanks again!

**Comment by benashz** [comment]
Just wanted to follow up here. Currently we are unable to reproduce this issue. We will take another look at it for the next release `3.4.0`.

**Comment by benashz** [comment]
Unfortunately we haven't able to reproduce this issue. If the problem persists please let us know and we will take another look at it.

**Comment by remijdias** [comment]
Hello,
We also noticed this.

Versions:
terraform 0.13.7
terraform-vault-provider 3.4.0
vault 1.5.5

We have something like this:
```hcl
resource "vault_generic_secret" "<redacted>" {
  for_each = local.<redacted>_roles
  path = <redacted>
  data_json = <redacted>
  delete_all_versions = false
}
```

And when we add something into `local.<redacted>_roles` the plan comes out like this:
```hcl
  # vault_generic_secret.<redacted>["<redacted>"] will be updated in-place
  ~ resource "vault_generic_secret" "<redacted>" {
        data                = (sensitive value)
      ~ data_json           = (sensitive value)
        delete_all_versions = false
        disable_read        = false
        id                  = "<redacted>"
        path                = "<redacted>"
    }

  # vault_generic_secret.<redacted>["<redacted>"] will be updated in-place
  ~ resource "vault_generic_secret" "<redacted>" {
        data                = (sensitive value)
      ~ data_json           = (sensitive value)
      + delete_all_versions = false
        disable_read        = false
        id                  = "<redacted>"
        path                = "<redacted>"
    }

  # vault_generic_secret.<redacted>["<redacted>"] will be created
  + resource "vault_generic_secret" "<redacted>" {
      + data                = (sensitive value)
      + data_json           = (sensitive value)
      + delete_all_versions = false
      + disable_read        = false
      + id                  = (known after apply)
      + path                = "<redacted>"
    }

```

There are always differences on `delete_all_versions` and/or `data_json` fields.

When we apply the changes:
(We run the apply inside [Atlantis](https://www.runatlantis.io/))

```
Error: Provider produced inconsistent final plan

When expanding the plan for
vault_generic_secret.<redacted>["<redacted>"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/vault" produced an invalid new value for
.delete_all_versions: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

(Redactions are for data protection)
