### ISSUE TITLE
Vault Mount Secrets Engine won't show up in UI using `listing_visibility:unauth`

### ISSUE THREAD

**Issue by Dragotic** [hashicorp/terraform-provider-vault#1303]
Hi there,

When creating or updating a `vault_mount` resource with the options flag and adding the `listing_visibility = "unauth"` it will create the secrets engine but it won't show up on the UI.

Doing a `vault secrets list -detailed` will show:
```
secrets/    kv           kv_3d45b984           system         system     false             replicated     false        false                      map[listing_visibility:unauth version:2]    The kv-v2 secrets engine for test-secrets is mounted at the secrets/ path    5d0771a1-3317-5390-7bf8-a73c5ff4cd8b
```
However, it doesn't show up in the UI.

If I then do the `vault secrets tune -listing-visibility=unauth secrets/` it will immediately show up.

### Terraform Version
v1.0.1
### Vault Version
v1.8.0
### Vault Provider Version
v3.1.1

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_mount

### Terraform Configuration Files
```hcl
resource "vault_mount" "secrets_engine" {
  for_each = { for se in var.secrets_engine : se.path => se }

  path        = each.value["path"]
  type        = each.value["type"]
  description = "The ${each.value["type"]} secrets engine for ${each.value["path"]} is mounted at the ${each.value["path"]}/ path"

  default_lease_ttl_seconds = lookup(each.value, "default_lease_ttl_seconds", null)
  max_lease_ttl_seconds     = lookup(each.value, "max_lease_ttl_seconds", null)

  seal_wrap               = lookup(each.value, "seal_wrap", null)
  local                   = lookup(each.value, "local", null)
  external_entropy_access = lookup(each.value, "external_entropy_access", null)
  options                 = lookup(each.value, "options", null)
}
```

with the following values:
```hcl
  secrets_engine = [
    {
      path = "secrets"
      type = "kv-v2"
      options = {
        listing_visibility = "unauth"
      }
    }
  ]
```

### Expected Behavior
The terraform provider for Vault should create the Secrets Engine and then it should show up on the UI.

### Actual Behavior
The Secrets Engine doesn't show on the UI, and requires to do a call through the CLI `vault secrets tune -listing-visibility=unauth secrets/`

### Steps to Reproduce
1. Use the configuration above.
2. `terraform apply`
3. `vault secrets list -address=http://vault-address -detailed` (It shows the `listing_visibility:unauth`)
4. Check the UI, the secrets engine shouldn't show up 
5. `vault secrets tune -listing-visibility=unauth secrets/`
6. Check the UI again, the secrets engine shows up

**Comment by vinay-gopalan** [comment]
Thank you for opening this issue, and apologies for the delayed response! 🙏🏼 

The TFVP added feature parity for missing fields on the `vault_mount` resource as part of #2235. With this, you can specify the `listing_visibility` at the resource-level (not inside the `options` block) to list the engine in the UI.

Going to go ahead and close this issue. Apologies again for the delay!
