### ISSUE TITLE
Feature Request: Add ability to configure for the kv-v2 mounts

### ISSUE THREAD

**Issue by harsimranmaan** [hashicorp/terraform-provider-vault#1310]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
terraform14 version
Terraform v0.14.11

Your version of Terraform is out of date! The latest version
is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)
N/A
Request for new resource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
N/A
```

### Debug Output
N/A

### Expected Behavior
What should have happened?
It should be possible to set https://www.vaultproject.io/api/secret/kv/kv-v2#configure-the-kv-engine via a kv-v2 config resource

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
N/A

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
N/A

### References
https://www.vaultproject.io/api/secret/kv/kv-v2#configure-the-kv-engine

**Comment by harsimranmaan** [comment]
Looks like https://github.com/hashicorp/terraform-provider-vault/pull/1239 would solve it

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue! As of v3.7.0, the TFVP now supports configuring the KV V2 Backend using the vault_kv_secret_backend_v2 resource. This feature was added alongside other KV ecosystem resources in https://github.com/hashicorp/terraform-provider-vault/pull/1457

Closing this issue, but please feel free to open another in case you face any problems with any of the resources. Thanks!
