### ISSUE TITLE
`data` block not working in `vault_database_secret_backend_connection`

### ISSUE THREAD

**Issue by alexjplant** [hashicorp/terraform-provider-vault#1365]
When we try and use the `data` block to configure a MySQL credential backend (via update) the values aren't substituted in. If we put the username and password in the `connection_url` attribute in the `mysql` block then everything works.

### Affected Resource(s)
- `vault_database_secret_backend_connection`

### Terraform Configuration Files
```hcl
 resource "vault_database_secret_backend_connection" "mysql_backend" {
   backend       = vault_mount.database.path
   name          = "apps-database"
   allowed_roles = ["readonly", "full"]
   mysql {
     connection_url = "{{username}}:{{password}}@tcp(REDACTED)/"
     max_open_connections = 5
   }
   
   data = {
     username       = "REDACTED"
     password       = "REDACTED"
   }

```

### Expected Behavior
The resource should update and the database connection should succeed. 

### Actual Behavior
```
Error: error configuring database connection "apps-database/config/apps-database": Error making API request. URL: PUT REDACTED/v1/apps-database/config/apps-database Code: 400. Errors: * error creating database object: error verifying connection: Error 1045: Access denied for user ''@'REDACTED' (using password: NO)
with vault_database_secret_backend_connection.mysql_backend
```

### Steps to Reproduce
`terraform apply` (well, in our case a Terraform Cloud apply)

**Comment by vinay-gopalan** [comment]
@alexjplant thanks for raising your issue! As of the [v3.3.0 release](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.3.0), you can pass in the `username` and `password` fields directly in the `mysql` block. They no longer need to be passed in through a separate data block.

PR where this feature enhancement was merged: https://github.com/hashicorp/terraform-provider-vault/pull/1331

This should solve the issue for your use case, but if this issue still persists, please let us know!

**Comment by alexjplant** [comment]
@vinay-gopalan This worked! We were on an old version and adding a requirement fixed it. Thanks so much

**Comment by vinay-gopalan** [comment]
@alexjplant Glad to hear it!
