### ISSUE TITLE
Public Evaluation: Enhanced Vault namespace support

### ISSUE THREAD

**Issue by benashz** [hashicorp/terraform-provider-vault#1380]
Hi All,

We are currently looking to enhance the way that the Terraform Vault Provider handles namespaced resources and datasources. We are looking for volunteers who would be willing to give the current #1305 a test drive. We we will be adding detailed instructions on how to build and test the provider. We will also provide some sample Terraform configurations that exercise the basic functionality of this new feature.

Stayed tuned for more info.

Thanks,

Ben

**Comment by in0rdr** [comment]
Thank you for putting together this evaluation. I followed the demo instructions in my local playground and found that it works quite well :+1:

**Comment by benashz** [comment]
Awesome to hear. Thanks for the feedback @in0rdr!

**Comment by benashz** [comment]
Closing this out as we are moving forward with the current implementation under way in #1305
