### ISSUE TITLE
Add provider auth_login support for azure auth backend

### ISSUE THREAD

**Issue by ekhaydarov** [hashicorp/terraform-provider-vault#1415]
Hi there,

It seems that the provider supports auth_login only for aws. Is there a timeline for adding auth support for azure? If not would it be possible to implement at all? At the moment the provider needs to get a token that needs to be passed in to be able to log in. With azure auth we would not rely on any secrets but use the underlying service principal of the machine to perform the log in, which is a better security practice.

### Terraform Configuration Files
```hcl
provider "vault" {
  address = "https://vault.com"
  auth_login {
    path   = "auth/azure/login"
    parameters = {
      role = "default"
    }
  }
}
```

### Debug Output
The debug is ambiguous to azure not being supported
```
Error: Put "https://vault.com": EOF
```

### Expected Behavior
Allow vault provider to be able to use azure backend in the `auth_login` block fo the provider

### Actual Behavior
A random EOF error

### Steps to Reproduce
Try to initialise the vault provider with azure backend like defined above

### References
The azure auth login has mostly been implemented in [vault-plugin-auth-azure](https://github.com/hashicorp/vault-plugin-auth-azure/blob/main/path_login.go) already so it should be relatively straight forward to implement?

**Comment by benashz** [comment]
Fixed in #1617
