### ISSUE TITLE
All attributes in vault_github_auth_backend.tune seem to be required

### ISSUE THREAD

**Issue by DanielWright** [hashicorp/terraform-provider-vault#1435]
### Terraform Version
Terraform v1.1.9
+ provider registry.terraform.io/hashicorp/vault v3.5.0

### Affected Resource(s)
- vault_github_auth_backend

### Terraform Configuration Files
```hcl
resource "vault_github_auth_backend" "chordcommerce" {
  organization = "example"

  tune = [{
    default_lease_ttl = "24h"
  }]

  # OR

  tune = {
    default_lease_ttl = "24h"
  }
}
```

### Expected Behavior
Since each of the elements in the `tune` block is marked as optional, I would expect to be able to tune a single value, or a subset of the tunable values. Moreover, requiring all values is counterintuitive—how would I use all defaults _except_ for `default_lease_ttl`?

### Actual Behavior
```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 85, in resource "vault_github_auth_backend" "chordcommerce":
│   85:   tune = [{
│   86:     default_lease_ttl = "24h"
│   87:   }]
│ 
│ Inappropriate value for attribute "tune": element 0: attributes
│ "allowed_response_headers", "audit_non_hmac_request_keys",
│ "audit_non_hmac_response_keys", "listing_visibility", "max_lease_ttl",
│ "passthrough_request_headers", and "token_type" are required.

# OR

│ Error: Incorrect attribute value type
│ 
│   on main.tf line 85, in resource "vault_github_auth_backend" "chordcommerce":
│   85:   tune = {
│   86:     default_lease_ttl = "24h"
│   87:   }
│ 
│ Inappropriate value for attribute "tune": set of object required.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
I'm planning and applying in Terraform Cloud, if that's relevant.

**Comment by benashz** [comment]
Hi @DanielWright ,

`tune` is a resource block which is pretty close to what you have in your second example. Your resource definition should look like:

```hcl
resource "vault_github_auth_backend" "chordcommerce" {
  organization = "example"

  tune {
    default_lease_ttl = "24h"
  }
}
```

**Comment by DanielWright** [comment]
Hi @benashz,

I tried that too! 😅  I did my best to show both types I tried, and neither worked but for different reasons. With the resource block, the validation error I get is:

```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 85, in resource "vault_github_auth_backend" "chordcommerce":
│   85:   tune = {
│   86:     default_lease_ttl = "24h"
│   87:   }
│ 
│ Inappropriate value for attribute "tune": set of object required.
```

**Comment by benashz** [comment]
I believe it should work if you include the `tune{}` without using the `=` assignment. 

Here's an example from the resource's acceptance test:

 https://github.com/hashicorp/terraform-provider-vault/blob/d8c735dd3668e990b60c6972276fb56fd043dfcb/vault/resource_github_auth_backend_test.go#L298-L313

All `tune` fields are optional, so a block of the form `tune {}` should be accepted.

Please let us know this helps.

Thanks!

**Comment by DanielWright** [comment]
Oh my goodness, thank you for sorting that out. My smooth brain completely missed the lack of `=`. 🤦‍♂️
