### ISSUE TITLE
vault_ldap_auth_backend does not support userfilter

### ISSUE THREAD

**Issue by rdbrim** [hashicorp/terraform-provider-vault#1456]
### Terraform Version
Terraform v1.1.8

### Affected Resource(s)
vault_ldap_auth_backend

### Expected Behavior
Able to set [userfilter](https://www.vaultproject.io/docs/auth/ldap?_ga=2.105561729.361588623.1652465994-583764845.1650404179#userfilter-1) argument via the [vault_ldap_auth_backend](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/ldap_auth_backend#argument-reference)

### Actual Behavior
vault_ldap_auth_backend does not expose the userfilter argument to set

**Comment by vinay-gopalan** [comment]
Hey @rdbrim, thanks for opening the issue! Support for LDAP Auth `userfilter` attribute was recently merged to the TFVP through PR #1378, and it is scheduled to be released in TFVP v3.6.0 later this month. If you face any problems with the resource post-release, please do let us know by opening another issue, thanks!
