### ISSUE TITLE
Feature Request: Support /sys/config/auditing/request-headers

### ISSUE THREAD

**Issue by geekofalltrades** [hashicorp/terraform-provider-vault#1465]
The provider [apparently does not support](https://discuss.hashicorp.com/t/does-the-vault-provider-support-v1-sys-config-auditing/39197) the [/sys/config/auditing/request-headers](https://www.vaultproject.io/api-docs/system/config-auditing) APIs. Can a resource be added to represent this, e.g. `vault_audit_request_header` or `vault_audit_config_request_header`?

**Comment by geekofalltrades** [comment]
It's been almost six months since I opened a pull request to address this. Is that realistically going to be reviewed and merged?

**Comment by hsimon-hashicorp** [comment]
@geekofalltrades Apologies for the delay! And thanks for pinging us again on it. I'll get it in front of an engineer. :)
