### ISSUE TITLE
add allowed_uri_sans_template parameter to vault_pki_secret_backend_role

### ISSUE THREAD

**Issue by jcarrothers-sap** [hashicorp/terraform-provider-vault#1486]
### Affected Resource(s)
* vault_pki_secret_backend_role

### Expected Behavior

Add `allowed_uri_sans_template` argument that corresponds to https://www.vaultproject.io/api-docs/secret/pki#allowed_uri_sans_template

**Comment by fairclothjm** [comment]
closed by https://github.com/hashicorp/terraform-provider-vault/pull/1910
