### ISSUE TITLE
vault_generic_secret cannot load pki CA cert String

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-provider-vault#1487]
### Terraform Version
Terraform 1.2.1

### Affected Resource(s)
- vault_generic_secret (data)

### Terraform Configuration Files
```hcl
data "vault_generic_secret" "intermediate_cert" {
  path = "pki/sed_smesh/ca/pem"
}
```

### Error Output
```
│ Error: error reading from Vault: invalid character '-' in numeric literal
│ 
│   with module.test_task.data.vault_generic_secret.mesh_intermediate_cert,
│   on .terraform/modules/test_task/secretsmanager.tf line 28, in data "vault_generic_secret" "intermediate_cert":
│   28: data "vault_generic_secret" "intermediate_cert" {
```

This exact same error exists in the vault cli attempting to get the string of a CA cert.  This issue is noted [here](https://github.com/hashicorp/vault/issues/919)

### Panic Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x5ab30d4]
```

The panic happens as the vault provider cannot load the data, due to an issue that exists on the vault CLI as well noted [here](https://github.com/hashicorp/vault/issues/919)

### Expected Behavior
The data loads the certificate string so I can put it in the AWS secrets manager, when using the consul-ecs mesh-task hashicorp terraform module.

### Actual Behavior
The data source can't actually load the value.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Setup a CA backend in a vault instance
2. Load the CA PEM string via terraform's vault_generic_secret data source

### References
- [Vault Github Issue 919](https://github.com/hashicorp/vault/issues/919)

**Comment by kitography** [comment]
Is there a reason you are using the `/ca/pem` endpoint rather than the `/cert/ca` endpoint?  The pki backend doesn't work like other secrets-engines, and returns pem data at the former endpoint (vs. json at the latter, which terraform could understand).

**Comment by reskin89** [comment]
That was the endpoint I was advised to use by my vault enterprise team

**Comment by dekimsey** [comment]
FWIW, the `data.http` method generates spurious warnings regarding content-type (I do wish it had a way to ignore or override the context type.)

```
│ Warning: Content-Type is not recognized as a text type, got "application/pem-certificate-chain"
│
│   with data.http.client_ca,
│   on demo.tf line 1, in data "http" "ca":
│   1: data "http" "ca" {
│
│ If the content is binary data, Terraform may not properly handle the contents of the response.
╵
```

Instead, I opted to use the PKI backend [Read Issuer Certificate json endpoint](https://www.vaultproject.io/api-docs/secret/pki#read-issuer-certificate) for this and it seems to work well enough.
```
data "vault_generic_secret" "ca" {
  path = "pki/issuer/default/json"
}
output "cert_pem" {
  value = join("\n", jsondecode(nonsensitive(data.vault_generic_secret.ca.data.ca_chain)))
}
```

Still a bit clunky, but at least I don't get warnings now ;)

**Comment by kitography** [comment]
I've checked internally, and no one on the hashicorp side (that we know of) has recommended the `ca/pem` endpoint for this use-case.  The endpoint to use here is `cert/ca`.  That endpoint is also unauthenticated.  Replacing `ca/pem` with `cert/ca` should solve your issue (looking at curl, it seems to have :) ).  Feel free to reopen this ticket if it doesn't.

The terraform provider documents that it provides access to the endpoints that the vault client provides read, write and delete for (https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/generic_secret).  The vault client does not provide access to the `ca/pem` endpoint (https://www.vaultproject.io/api-docs/secret/pki#vault-cli-with-der-pem-responses).  If I've missed documentation somewhere, please let me know (reopen), and we'll work to correct that.
