### ISSUE TITLE
No resource for Kubernetes Secret Engine

### ISSUE THREAD

**Issue by dirtyrandy** [hashicorp/terraform-provider-vault#1522]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
https://registry.terraform.io/providers/hashicorp/vault/latest/docs

### Expected Behavior
Kubernetes Secret Engine resource present in Vault Terraform provider

### Actual Behavior
Kubernetes Secret Engine resource NOT present in Vault Terraform provider

The feature was released with HCV v1.11.0 but has not made it into the Terraform provider yet. This is keeping us from consuming these new feature sets because we primarily deploy our Vault with Terraform.

**Comment by austingebauer** [comment]
This is set to be released in the next version of the provider. I'm going to close this issue now. Thanks!
