### ISSUE TITLE
Database engine password is sent even if not changed

### ISSUE THREAD

**Issue by axolotlgeoff** [hashicorp/terraform-provider-vault#1629]
When changing the list of `allowed_roles`, the provider is sending the password even though it has not changed. This results in an error in scenarios where Vault has rotated the root credentials:

```
vault_database_secret_backend_connection.example: Modifying... [id=database/config/postgres]
╷
│ Error: error configuring database connection "database/config/postgres": Error making API request.
│ 
│ URL: PUT https://local.pillar:8200/v1/database/config/postgres
│ Code: 400. Errors:
│ 
│ * error creating database object: error verifying connection: pq: password authentication failed for user "vaultdbuser"
│ 
```

It looks like this is a regression as this scenario was specifically addressed in PR #739 however I believe that since the `data` block is no longer used, the check at [resource_database_secret_backend_connection.go:1459](https://github.com/hashicorp/terraform-provider-vault/blob/810708c38cfba3283edce88fa1def5191d8a67e6/vault/resource_database_secret_backend_connection.go#L1459) never runs:

```
	if m, ok := d.GetOkExists(prefix + "data"); ok {
		for k, v := range m.(map[string]interface{}) {
			// Vault does not return the password in the API. If the root credentials have been rotated, sending
			// the old password in the update request would break the connection config. Thus we only send it,
			// if it actually changed, to still support updating it for non-rotated cases.
			if k == "password" && (d.IsNewResource() || (d.HasChange(k) && !d.IsNewResource())) {
				data[k] = v.(string)
			}
		}
	}
```

The root credentials are now nested under database engine specific blocks, which makes perfect sense. It looks like `getDatabaseAPIDataForEngine` will make the password available at `data["password"]` . Does this (completely untested code) look like a reasonable fix?

```
	if v, ok := d.GetOkExists(prefix + "password"); ok {
		// Vault does not return the password in the API. If the root credentials have been rotated, sending
		// the old password in the update request would break the connection config. Thus we only send it,
		// if it actually changed, to still support updating it for non-rotated cases.
		if (d.IsNewResource() || (d.HasChange("password") && !d.IsNewResource())) {
			data["password"] = v
		}
	}
```
I'm mostly uncertain about the result of `d.HasChange` given `data["password"]` really exists in a provider-specific block.

If that fix looks good, I'm happy to create a PR and also make a quick fix to remove the defunct reference to the `data` block in the docs.

### Terraform Version
Vault provider version 3.9.1

### Affected Resource(s)
Please list the resources as a list, for example:
- `vault_database_secret_backend_connection`

### Terraform Configuration Files
```hcl
resource "vault_database_secret_backend_connection" "example" {
  backend       = vault_mount.database.path
  name          = "postgres"
  allowed_roles = ["role1", "role2"] # Added "role2" since last apply

  postgresql {
    connection_url = local.templated_connection_string
    username = "vaultdbuser"
    password = "someinitialpassword" # NB the password is no longer in the data block
  }
}
```

### Expected Behavior
A `terraform apply` should have updated the list of `allowed_roles` successfully without supplying the password.

### Actual Behavior
The password is being supplied as well and therefore results in an error:
```
* error creating database object: error verifying connection: pq: password authentication failed for user "vaultdbuser"
```

**Comment by rissson** [comment]
@axolotlgeoff we're also encountering that problem. Perhaps if you proposed a PR directly this would get more attention?

**Comment by vinay-gopalan** [comment]
Hi! Thanks for raising the issue and apologies for the delay 🙏🏼 The Provider should definitely cleanup and handle the state in cases of external updates like rotate root. We're looking into this bug and similar cases, and will update this thread as soon as we have the fixes up. Thanks again and we appreciate your patience! :)

**Comment by raymonstah** [comment]
Hello, just wanted to let you know that this issue should be fixed as part of https://github.com/hashicorp/terraform-provider-vault/pull/1876 and released in https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.16.0.

Thanks again for raising the issue. Please let us know if this is still a problem for you!

**Comment by jrutkowski** [comment]
It seems, that the fix only works for some of the database engines.

I believe this is the commit that aims to fix the issue: https://github.com/hashicorp/terraform-provider-vault/blob/9911f9ace842a6a345c99e54463e3c7effdead91/vault/resource_database_secret_backend_connection.go#L1518

It adds a condition to the function `setDatabaseConnectionDataWithUserPass` which checks if the password was changed in the configuration or not. 
The issue here, is that this function is only used by some subset of supported engines.
There are however other functions, that are used by other database connections, like `setElasticsearchDatabaseConnectionData` `setRedisElastiCacheDatabaseConnectionData` etc.

Could you please reopen the issue, to fix those use cases as well?

**Comment by raymonstah** [comment]
@jrutkowski you're absolutely right. I'll address these cases in an upcoming PR as well.
