### ISSUE TITLE
Redis database backend is not supported

### ISSUE THREAD

**Issue by ameyp** [hashicorp/terraform-provider-vault#1640]
### Terraform Version
v1.3.2

### Affected Resource(s)
- vault_database_secrets_mount
- vault_database_secret_backend_connection

### Terraform Configuration Files
```hcl
provider "vault" {
  address = "http://localhost:1234"
  token = "ABCD"
}

resource "vault_database_secrets_mount" "redis" {
  path = "database"

  redis {
    name = "redis"
    host = "redis-master.redis.svc.cluster.local"
    username = "redis"
    passsword = "password"
    allowed_roles = [ "*" ]
  }
}
```

### Debug Output
https://gist.github.com/ameyp/0ffe4519a42454587906b099630c8131

### Expected Behavior
The apply should have succeeded, because Redis is a database backend supported by Vault: https://www.vaultproject.io/api-docs/secret/databases/redis

### Actual Behavior
The apply failed because the provider only supports Redis Elasticache, not just plain Redis

### Steps to Reproduce
`terraform apply` with the above hcl

### Important Factoids
None

### References
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secrets_mount
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection
https://www.vaultproject.io/api-docs/secret/databases/redis

**Comment by maxcoulombe** [comment]
Hey @ameyp thanks for the detailed issue.

Redis is a brand new engine and although we try to keep the Terraform Provider up to date with new features there can be some gap before it is on par with Vault functionalities.

I can bring this issue up with the team so it's prioritised in the near future. If you or someone else have some spare cycles and would like to have a crack at it, the [pull request that added support for ElastiCache](https://github.com/hashicorp/terraform-provider-vault/pull/1596) can be used as a guide or reference.

**Comment by blufor** [comment]
@maxcoulombe: Just created a PR with that ;)

**Comment by Zlaticanin** [comment]
Moved to #1659.
