### ISSUE TITLE
Feature: Set vaultVersion in ProviderMeta without api call

### ISSUE THREAD

**Issue by SvenMarquardt5772** [hashicorp/terraform-provider-vault#1643]
I removed the template because it is not applicable here, as this is a feature request. And i checked the code of main.

Would it be feasible to let us set the vaultVersion for the ProviderMeta on the commandline or in terraform config?

We host vault ourselves and do not expose the API to get the current version of the vault publicly. Because of this, we can't deploy this anymore.  

I'm talking about this line of code https://github.com/hashicorp/terraform-provider-vault/blob/4e480a68203a9fd31cb65be2aeab55feae383357/internal/provider/meta.go#L238

**Comment by benashz** [comment]
Thanks for reporting this issue. The provider should not error out if it cannot detect the running Vault version. We should have a fix for that soon.

> Would it be feasible to let us set the vaultVersion for the ProviderMeta on the commandline or in terraform config?

That's an interesting idea. We will take a look to see what can be done that regard.

Ben

**Comment by SvenMarquardt5772** [comment]
Good to hear, that this is a bug.
