### ISSUE TITLE
`provider.auth_login_jwt` cannot use environment variable `TERRAFORM_VAULT_AUTH_JWT` because `jwt` is required.

### ISSUE THREAD

**Issue by rwblokzijl** [hashicorp/terraform-provider-vault#1657]
In https://registry.terraform.io/providers/hashicorp/vault/latest/docs#jwt it says `jwt` Can be specified with the `TERRAFORM_VAULT_AUTH_JWT` environment variable.

However `jwt` is a required variable. So it cant use `TERRAFORM_VAULT_AUTH_JWT`. Terraform gives the following error: 
![image](https://user-images.githubusercontent.com/446634/199196729-b155d6ff-81ed-43ae-8c7e-38d1add2f75b.png)

**Comment by benashz** [comment]
Hi, we are unable to reproduce this issue. Would you mind providing us with the steps that led up the reported error?

Thanks,

Ben

**Comment by rwblokzijl** [comment]
the code looks as follows:
```terraform
provider "vault" {
  address = ...
  auth_login_jwt {
    mount = "gcp"
    role  = var.vault_role
    jwt   = null
  }
  ca_cert_dir = ...
}
```
We also tried:

```terraform
provider "vault" {
  address = ...
  auth_login_jwt {
    mount = "gcp"
    role  = var.vault_role
    # jwt   = null
  }
  ca_cert_dir = ...
```
Both give the following error:
```
│ Error: Missing required argument
│
│   on providers.tf line 45, in provider "vault":
│   45:   auth_login_jwt {
│
│ The argument "jwt" is required, but no definition was found.

```

**Comment by benashz** [comment]
In the case where you are passing in the `jwt` from the environment variable your `provider` block would look like something like this:
```hcl
provider "vault" {
  auth_login_jwt {
    role = "role1"
  }
}
```

The `jwt` should be omitted.

**Comment by rwblokzijl** [comment]
I found my issue, i forgot to use `export` when setting the environment variable, which led to the issue.
