### ISSUE TITLE
FR: Implement LDAP Secrets Engine

### ISSUE THREAD

**Issue by thekev** [hashicorp/terraform-provider-vault#1662]
### Terraform Version
Terraform v1.3.4

### Affected Resource(s)
- `vault_ldap_secret_*` (does not exist)

### Expected Behavior
Complete [API](https://developer.hashicorp.com/vault/api-docs/secret/ldap) should be implemented in terraform provider.

### Actual Behavior
It seems every other secrets engine is implemented.

### Important Factoids
I'm surprised to find there isn't already an open feature request for this. Am I the only one who wants secrets management for OpenLDAP?

**Comment by benashz** [comment]
Hi @thekev , despite this being a Vault 1.12 we will be adding this feature during the Vault 1.13 time-frame. We can't give you an exact date for its inclusion, unfortunately.

**Comment by digitalfredy** [comment]
Hi @benashz 

Does HachiCorp have any news about this?

I'm doing a project and I will prefer to do this via Terraform then if you give us a clue about how much time could take (weeks, months more that a year) we could decide if we take the risk to wait until this get released.

**Comment by benashz** [comment]
HI @digitalfredy, it should be available around the time that Vault 1.13 comes out. We don't like to provide an exact date for the major vault  releases. More than likely you should see this feature available by the end of March.

**Comment by digitalfredy** [comment]
@benashz thanks for your diligent answer because having this in mind we will probably hold with manual management until Q1 or Q2 next year.

And for sure to me is crystal clear that is not a promise.

**Comment by thekev** [comment]
This feature is for the unified `ldap` secrets engine introduced in 1.12. I am still on 1.10. Is there terraform provider support for the `openldap` secrets engine? I didn't see any documentation for it, just a few resources for `ad` secrets.

**Comment by EvertonSA** [comment]
Is this feature accepting PR? I would like to work on that

**Comment by bmhughes** [comment]
I've implement this in a local fork, I'm working on getting it into a suitable PR which I hope can be merged.

**Comment by fairclothjm** [comment]
Addressed by https://github.com/hashicorp/terraform-provider-vault/pull/1859
