### ISSUE TITLE
"unsupported path" error on `hashicorp/vault` v3.9.0+ plugin

### ISSUE THREAD

**Issue by altokarev** [hashicorp/terraform-provider-vault#1665]
Hey! 👋 

It seems `hashicorp/vault` provider partially stopped working since `v3.9.0`. I've double-checked that and discovered that until `v3.8.2` it works as usual. I suppose there was a related issue at past - #1642, which states, that:
>VaultProviderAuthLogin().Path = auth/approle/login is overwtitten by auth/token/create

### Terraform Version
```
Terraform v1.1.7
on linux_arm64

Your version of Terraform is out of date! The latest version
is 1.3.4. You can update by downloading from https://www.terraform.io/downloads.html
```
```
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/vault v3.9.0
+ ...
```

### Affected Resource(s)
`hashicorp/vault` provider configured with `auth/approle/login` auth method

### Terraform Configuration Files
```hcl
terraform {
    required_version = ">= 1.0.7"
        required_providers {
...
            vault = {
                source = "hashicorp/vault"
                version = ">= 3.8.2"
            }
        }
}

provider "vault" {
  address = "https://my-vault.example.org/"
  skip_tls_verify = true

  auth_login {
    path = "auth/approle/login"
    namespace = "myCoolNamespace"
    parameters = {
    role_id   = var.login_approle_role_id
    secret_id = var.login_approle_secret_id
    }
  }
}
```

### Debug Output
```
╷
│ Error: could not determine the Vault server version, err=Error making API request.
│
│ URL: GET https://my-vault.example.org/v1/sys/seal-status
│ Code: 404. Errors:
│
│ * unsupported path
│
│   with provider["registry.terraform.io/hashicorp/vault"],
│   on provider.tf line 37, in provider "vault":
│   37: provider "vault" {
│
╵
```

### Expected Behavior
`terraform plan/apply` shouldn't be interrupted by any errors

### Actual Behavior
`terraform plan/apply` stopped working, indicates an error I've posted above

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### References
- #1623
- #1642

**Comment by benashz** [comment]
From the error you received, it looks like the provider could not get the Vault version from the server's seal-status. With v3.10.0 you can specify the version with https://registry.terraform.io/providers/hashicorp/vault/latest/docs#vault_version_override. If you wouldn't mind giving that try just to verify that this is not an login issue, that would be great. In the meantime we will investigate a bit to ensure that the `sys/seal-status` is accessible using a namespaced client.

**Comment by altokarev** [comment]
Yup, that helped! 🎉 

```hcl
provider "vault" {
  address = "https://my-vault.example.org/"
  vault_version_override = "1.5.4"
  skip_tls_verify = true

  auth_login {
    path = "auth/approle/login"
    namespace = "myCoolNamespace"
    parameters = {
    role_id   = var.login_approle_role_id
    secret_id = var.login_approle_secret_id
    }
  }
}
```

It seems the backward compatibility is handled with this option, and it's OK for me.

Really appreciated, @benashz 🙏
