### ISSUE TITLE
Unable to use auth_login_gcp: `unknown fields: ["credentials" "service_account"]`

### ISSUE THREAD

**Issue by itspngu** [hashicorp/terraform-provider-vault#1667]
### Terraform Version
```
terraform -v
Terraform v1.3.4
on linux_amd64
```

### Affected Resource(s)
n/a (affects provider configuration)

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "3.10.0"
    }
  }
}

# This doesn't work
provider "vault" {
  address     = "http://localhost:8200"

  auth_login_gcp {
    role = "terraform-vault"
    jwt  = var.GCP_OAUTH_TOKEN
  }
}

# This works
provider "vault" {
  address     = "http://localhost:8200"

  auth_login {
    path = "auth/gcp/login"
    parameters = {
      "role" = "terraform-vault"
      "jwt"  = var.GCP_OAUTH_TOKEN
    }
  }
}

resource "vault_mount" "kv" {
  type = "kv"
  path = "kv"

  options = {
    "version" = "2"
  }
}
```

### Debug Output
https://gist.github.com/itspngu/8a65aaef0f4b4eb576557ebfaf9b2c82

### Panic Output
n/a

### Expected Behavior
Authentication succeeds as shown in the docs.

### Actual Behavior
Authentication fails with the following error:

```
Error: Error making API request.

URL: PUT http://localhost:8200/v1/auth/gcp/login
Code: 422. Errors:

* unknown fields: ["credentials" "service_account"]

  with provider["registry.terraform.io/hashicorp/vault"],
  on providers.tf line 44, in provider "vault":
  44: provider "vault" {
```

Using the included alternate configuration (`auth_login` instead of `auth_login_gcp`) everything works fine.

### Steps to Reproduce
1. `terraform apply`
2. profit

### Important Factoids
Vault is running in HA (Raft) using a MIG on GCP and accessed via IAP proxying through an SSH tunnel. The JWT is generated using the `gcloud` console command [shown in the docs](https://developer.hashicorp.com/vault/docs/auth/gcp#gcloud-example). Vault version info: `Vault v1.12.1 (e34f8a14fb7a88af4640b09f3ddbb5646b946d9c), built 2022-10-27T12:32:05Z`

### References
- [GH-1607](https://github.com/hashicorp/terraform-provider-vault/pull/1607)

**Comment by benashz** [comment]
This was fixed in #1648, will be released tomorrow in [v3.11.0](https://github.com/hashicorp/terraform-provider-vault/milestone/25)
