### ISSUE TITLE
Documentation discrepancy for resource vault_okta_auth_backend

### ISSUE THREAD

**Issue by jlestrada** [hashicorp/terraform-provider-vault#1681]
### Overview
There appears to be an issue where the documentation of the resource vault_okta_auth_backend does not match the intended behavior. The attribute `path` is stated as to be required but does not appear to actually be required. The value defaults to `okta`. The logic can be found [here](https://github.com/hashicorp/terraform-provider-vault/blob/a9813b3deaeee4d7a2c8ba696daa393b3735911d/vault/resource_okta_auth_backend.go#L36-L38).

I assume that the intended attribute is to be optional considering the code logic, so I am suggesting an update to the documentation to correctly reflect the behavior. If this is not the intended behavior, then please feel free to say otherwise. 

### Terraform Version
1.3.3 

### Affected Resource(s)
- vault_okta_auth_backend

### Terraform Configuration Files
```hcl
resource "vault_okta_auth_backend" "okta_auth" {
  description     = "Vault Okta auth backend for database access"
  organization    = "joinmodernhealth"
  token           = <redacted>
  ttl             = "1h"
  bypass_okta_mfa = false
  base_url        = "okta.com"
}
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
Failure of the resource from being created should have happened if the attribute `path` is required.

### Actual Behavior
The resource is created and defaults to the path `okta`.

### Steps to Reproduce
Simply setup the Terraform Vault provider and attempt to create a resource without specification of the required variable `path`. An example of what we created is posted above.

### Important Factoids
NA

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- [PR 1680](https://github.com/hashicorp/terraform-provider-vault/pull/1680)

**Comment by vinay-gopalan** [comment]
Closing after meging #1680
