### ISSUE TITLE
Regression in 3.10.0: Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by maxb** [hashicorp/terraform-provider-vault#1690]
During a plan/apply run in TFE, an error was produced:

> Error: Provider produced inconsistent final plan
> When expanding the plan for vault_identity_group.group["RG-Foo-Bar-Baz"] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/vault" produced an invalid new value for .external_member_group_ids: was cty.False, but now null.
> 
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

external_member_group_ids is a new resource attribute added in provider 3.10.0.

The plan (transcribing from the TFE GUI) showed:

```
+ external_member_group_ids: false
~ member_group_ids: [
    each existing value -> Known after apply
  ]
```

The apply then produced the error text shown above.

The code change that triggered this plan/apply run changed other members of the `for_each` for the `vault_identity_group.group` resource block, but made no changes to the particular resource instances for which the error arose.

### Terraform Version
Terraform 1.3.4
terraform-provider-vault 3.10.0

### Affected Resource(s)
- vault_identity_group

### Terraform code
```hcl
resource "vault_identity_group" "group" {
  for_each = <complex expression trimmed>
  name = each.key
  type = "internal"
  member_group_ids = <complex expression trimmed>
  policies = concat(each.value, ["default"])
  depends_on = [var.vault-namespace]
}
```

**Comment by hsimon-hashicorp** [comment]
Thanks, @maxb! I'll get this in front of our engineering team.

**Comment by benashz** [comment]
Hi @maxb, we'd need a bit more information to better understand this issue.

Would you be able to provide us with the relevant log output from a `TF_LOG=debug terraform apply` ? Also, was the `apply` made on a new TF state?

Thanks,

Ben

**Comment by maxb** [comment]
The problem was so far only occurred in a secure environment where we can't enable debug logging.

It was running in Terraform Enterprise following a merge to Git master, so no, the state would not have changed between the plan and apply.

I will probably need to pick this up in January, as I only have 1 more working day in 2022.

**Comment by maxb** [comment]
Still an issue with Terraform 1.3.7, terraform-provider-vault 3.12.0 ... unfortunately I still haven't managed to reproduce this outside of a locked down production environment, but having captured some new occurrences, I am persuing new leads.

**Comment by maxb** [comment]
Aha! I figured out how to reproduce it!

Start with this Terraform configuration:
```
// An example Vault provider config, modify as needed for your testing
provider "vault" {
  address = "http://localhost:8200"
  auth_login {
    path = "auth/userpass/login/admin"
    parameters = {
      password = "wibble"
    }
  }
}

terraform {
  required_providers {
    vault = {
      source = "hashicorp/vault"
      // Phase 1
      version = "~> 3.9.0"
      // Phase 2
      //version = "~> 3.12.0"
    }
  }
}

locals {
  // Phase 1
  groups = toset(["alpha"])
  // Phase 2
  //groups = toset(["alpha", "beta"])
}

resource "vault_identity_group" "groups_to_lookup" {
  for_each = local.groups
}

data "vault_identity_group" "groups_to_lookup" {
  for_each = local.groups
  group_id = vault_identity_group.groups_to_lookup[each.key].id
}

resource "vault_identity_group" "group_with_members" {
  for_each = local.groups
  member_group_ids = [data.vault_identity_group.groups_to_lookup[each.key].id]
}
```

Run `terraform init -upgrade && terraform apply -auto-approve`

Now edit the configuration, commenting out the two lines marked as "Phase 1" and uncommenting the two lines marked as "Phase 2".

Run `terraform init -upgrade && terraform apply -auto-approve` again

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for vault_identity_group.group_with_members["alpha"] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/vault" produced an invalid new value for .external_member_group_ids: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Comment by maxb** [comment]
TF_LOG=debug yields these lines in particular:
```
2023-01-14T22:11:22.582Z [DEBUG] After incorporating new values learned so far during apply, vault_identity_group.group_with_members["alpha"] change has become NoOp
2023-01-14T22:11:22.582Z [ERROR] vertex "vault_identity_group.group_with_members[\"alpha\"]" error: Provider produced inconsistent final plan
```

Which lead me towards a hypothesis for what is happening:

* The upgrade of the provider has introduced a new boolean attribute external_member_group_ids with default value false
* As a result, when any other change to the resource is planned, the plan includes the new external_member_group_ids transitioning from null to false
* However, the other change ends up turning out to be no change at all at apply time, because data sources read during apply return existing values
* At this point, the logic which is supposed to determine whether there are any changes left in the plan, fails to consider "null -> false" as an actual change, and incorrectly marks the change as NoOp
