### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by jmm94** [hashicorp/terraform-provider-vault#1691]
Hi

there  is an error on the document page
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/kv_secret_v2

data "vault_kv_secret_v2" "secret_data" {
  mount = vault_mount.kvv2.path
  name  = vault_kv_secret_v2.test.name
}

should be

data "vault_kv_secret_v2" "secret_data" {
  mount = vault_mount.kvv2.path
  name  = vault_kv_secret_v2.secret.name
}

regards

**Comment by hsimon-hashicorp** [comment]
Hello @jmm94, thanks for reporting this! Please feel free to file a PR to resolve this if you wish, or I'll have our engineers take a look at it - but that may take longer. :)

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 A fix for the docs was merged in #1701 and was released. Going to close this issue since this is resolved,  thanks again for bringing this to our attention :)
