### ISSUE TITLE
vault_kv_secret_backend_v2 import issue (get "mount": null,)

### ISSUE THREAD

**Issue by byunru** [hashicorp/terraform-provider-vault#1698]
vault_kv_secret_backend_v2 import issue:

### Expected Behavior
as mount is a required value (https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/kv_secret_backend_v2)
so its value should be like  mount = "kv"

### Actual Behavior
after import, get
    {
      "module": "module.vault-ldap.module.kv[\"appconfigs_kv\"]",
      "mode": "managed",
      "type": "vault_kv_secret_backend_v2",
      "name": "config",
      "provider": "module.vault-ldap.provider[\"registry.terraform.io/hashicorp/vault\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cas_required": false,
            "delete_version_after": 0,
            "id": "appconfigs_kv/config",
            "max_versions": 0,
            "mount": null,
            "namespace": null
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    },
from terraform.tfstate

### Steps to Reproduce
terraform import "$kv_module.vault_kv_secret_backend_v2.config" "$path/config"

**Comment by hsimon-hashicorp** [comment]
Are you getting an error message, or anything else that can help us reproduce this? Thanks!

**Comment by byunru** [comment]
no error message, but the return attribute "mount" suppose has value, shouldn't be empty

**Comment by benashz** [comment]
Hi @byunru, the arguments that you are passing to `terraform import` seem to be invalid. Would you mind following the import docs to see if they resolve your issue?

- https://developer.hashicorp.com/terraform/cli/commands/import#example-import-into-module
- https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/kv_secret_backend_v2#import

Thanks,

Ben

**Comment by byunru** [comment]
@benashz 
I use Powershell console, the Terraform import syntax is 100% correct. $kv_module & $path are my predefine pwsh variable, which map to my Terraform module code, and the import already executed successfully, by checking the terraform.tfstate, it added a section of {
"module": "module.vault-ldap.module.kv["appconfigs_kv"]",
"mode": "managed",
"type": "vault_kv_secret_backend_v2",
"name": "config",
"provider": "module.vault-ldap.provider["registry.terraform.io/hashicorp/vault"]",
"instances": [
...
(I have to repeat)

terraform import "$kv_module.vault_kv_secret_backend_v2.config" "$path/config"

**Comment by benashz** [comment]
Thanks @byunru. We'll take a closer look at the issue.

**Comment by benashz** [comment]
@byunru Thanks again for reporting this issue. The fix should go out in next week's release  v3.12.0.
