### ISSUE TITLE
Members are added, removed, added again etc in vault identity groups

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [hashicorp/terraform-provider-vault#1743]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
 terraform --version --json
{
  "terraform_version": "1.3.7",
  "platform": "linux_amd64",
  "provider_selections": {
    "registry.terraform.io/hashicorp/vault": "3.11.0",
  },
  "terraform_outdated": false
}
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `vault_identity_group`
- `vault_identity_group_member_entity_ids`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Here is how I create identity entities, identity groups and identity group member ids

Subsequent applies of the following:

```hcl
resource "vault_identity_group_member_entity_ids" "test" {
  member_entity_ids = ["111-333-888-999-000-444"]
  group_id          = "8383-111-4344-9595-98989"
}
```

Keep adding, then removing, then adding again the entity with id `111-333-888-999-000-444` to group with id `8383-111-4344-9595-98989`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
After the first apply, there should be no changes in `terraform` (since I don't change my configuration)

### Actual Behavior
The member gets repeatedly added/removed to/from the group

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by pantelis-karamolegkos** [comment]
To simplify this, repeated applies of the following code, keep removing-->adding-->removing the entity with id `111-222-333-444-555` to group with id `999-888-777-111-222`

```hcl
module "identities_memberships" {

  source = "../../../../modules-terraform/vault/identity_group_member_entity_ids"
  member_entity_ids = ["111-222-333-444-555"]
  group_id          = "999-888-777-111-222"


}
```

**Comment by BrianHicks** [comment]
Just adding a note for others who may come across this behavior that it seems to be caused by `vault_identity_group`'s members setting conflicting with the `vault_identity_group_member_entity_ids` resource. Adding this line in my config fixed it:

```diff
 resource "vault_identity_group" "group" {
   name = "group"
   type = "internal"

+  external_member_entity_ids = true
 }

 resource "vault_identity_group_member_entity_ids" "members" {
   exclusive         = true
   member_entity_ids = [vault_identity_entity.entity.id]
   group_id          = vault_identity_group.group.id
 }
```
