### ISSUE TITLE
vault 0.11.1. vault_aws_secret_backend_role policy permanently change

### ISSUE THREAD

**Issue by sadpirit** [hashicorp/terraform-provider-vault#176]
After the update to vault 0.11.1, I get a policy change on **vault_aws_secret_backend_role** every time.

### Terraform Version
Terraform v0.11.8
+ provider.external v1.0.0
+ provider.template v1.0.0
+ provider.vault v1.1.3

Vault version:   0.11.1
### Affected Resource(s)
vault_aws_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend_role" "problem" {
    provider = "vault.current"
    backend = "secrets/aws/plr/atf01"
    name = "problem_inline"
    policy = <<EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
EOT
}
```
With each planning I get empty policy everytime:
```
  ~ vault_aws_secret_backend_role.problem
policy:    ""  =>
 "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [
        {
            \"Effect\": \"Allow\",
            \"Action\": \"*\",
            \"Resource\": \"*\"
        }
    ]
}"
```

**Comment by lawliet89** [comment]
This is most likely due to [Vault 0.11 changes](https://www.vaultproject.io/guides/upgrading/upgrade-to-0.11.0.html#aws-secret-engine-roles).

**Comment by icereed** [comment]
Experiencing this as well. Thanks for having a PR ready!

**Comment by universam1** [comment]
any news on this, we need to move to newer Vault version

**Comment by icereed** [comment]
@tyrannosaurus-becks Could you help us here to know the next steps?

**Comment by dhohengassner** [comment]
thanks for the research - also facing this issue...

would love to see this provider usable with current vault version

any updates?

**Comment by icereed** [comment]
Hello,

it seems there is nothing in progress to solve this issue.
Actually this is quite important for us, because we're stuck with Vault 0.10 otherwise.
How to proceed here?

**Comment by swenson** [comment]
I believe this was fixed in https://github.com/hashicorp/terraform-provider-vault/pull/261
