### ISSUE TITLE
auth_login_cert does not seem to work and asks for token in provider vault configuration

### ISSUE THREAD

**Issue by hatimghliel** [hashicorp/terraform-provider-vault#1778]
### Terraform Version
Terraform v1.3.6
on linux_amd64
vault provider version 3.11.0
### Affected Resource(s)
no ressources affected, it's a provider configuration issue, it may be an issue with Terraform's core

### Terraform Configuration Files
```provider "vault" {
  address = "https://myvault.net/v1/auth/cert/login"
  skip_child_token = true
  auth_login_cert{
    namespace = "BU/001"
    name = "certrole"
    cert_file = "mycert.fr.crt"
    key_file = "mycert.key"
  }
}
```

### Expected Behavior
We expect the vault provider to recognize that we are trying to connect via a TLS certificate, and establish the connection since we've given the actual required parameters ( cert_file and cert_key). 

The cert authentication method is created, also the role to use it. Please note that with an API call to vault, we can establish the connection with the tls certificates and get the secrets we want.

```export VAULT_TOKEN=$( \
curl -X POST -H "X-Vault-Namespace: ${VAULT_NAMESPACE}" -H "X-Vault-Request: true" \
 --cert ./path_to_certificate/new_cert.crt \
 --key ./path_to_certificate/new_cert_key.key \
 -d '{"name":"new-dev"}' ${VAULT_ADDR}/v1/auth/cert/login | jq -r '.auth.client_token')
```

### Actual Behavior
```
 [ERROR] vertex "provider[\"myregistry/providers/vault\"]" error: no vault token found
 [TRACE] vertex "provider[\"myregistry/providers/vault\"]": visit complete, with errors
 [TRACE] dag/walk: upstream of "data.vault_kv_secret_v2.test (expand)" errored, so skipping
 [TRACE] dag/walk: upstream of "provider[\"myregistry/providers/vault\"] (close)" errored, so skipping
 [TRACE] dag/walk: upstream of "root" errored, so skipping
 [INFO]  backend/local: plan operation completed
╷
│ Error: no vault token found
│
│   with provider["myregistry/providers/vault"],
│   on vault.tf line 29, in provider "vault":
│   29: provider "vault" {
│
╵

```

### Steps to Reproduce
To reproduce please set your certificate + key file in the root of the project and exec : 
1. `terraform plan`

**Comment by nvx** [comment]
I noticed `AuthLoginCert` is missing from this switch statement in `GetAuthLogin` https://github.com/hashicorp/terraform-provider-vault/blob/main/internal/provider/auth.go#L223-L246

It may be as simple as adding it there, although I do wonder how this defect managed to slip in...
