### ISSUE TITLE
kv_secret_v2 corrupted state

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/terraform-provider-vault#1780]
### Terraform Version
v1.3.9

### Affected Resource(s)
- vault_kv_secret_v2

### Terraform Configuration Files
```hcl
terraform {

  required_version = ">= 1.0.0"

  required_providers {
    vault = {
      source = "hashicorp/vault"
      version = ">= 3.13.0"
    }
  }
}

resource "vault_kv_secret_v2" "packer-s3-bucket" {
  mount               = "client/my/msp/secret"
  name                = "packer/aws/0123456789/vmimport"
  delete_all_versions = true
  data_json           = jsonencode({
    foo = "bar"
  })
}
```

### Expected Behavior
Terraform needs to record the state properly.

### Actual Behavior

While the provider creates/writes the correct entry into vault itself (the mount exists, permissions are good, etc), it does not record the TF state correctly and you end up with a corrupted state file.

The actual state file contains:

```
...
"mount": "client",
"name": "msp/secret/data/packer/aws/0123456789/vmimport",
"namespace": null,
"options": null,
"path": "client/my/msp/secret/data/packer/aws/0123456789/vmimport"
...
```

Note how the `path` is correct, and matches what is expected from the TF code. However, the `mount` is stored as the first path component. The second path component, "`my`" here, is dropped, and the remaining path is stored in `name` with the improper inclusion of `data` in the value.

The state file should match the TF code, like so:

```
...
"mount": "client/my/msp/secret",
"name": "packer/aws/0123456789/vmimport",
"namespace": null,
"options": null,
"path": "client/my/msp/secret/data/packer/aws/0123456789/vmimport"
...
```

The result of this corrupted state is that:
a) a plan against this state shows a delta because TF recognizes when it reads back the state that "`client`" does not match the expected `mount` value.
b) an apply against this state fails because of (a) and because TF tries to use these corrupted values to construct a path to query vault for the infrastructure state. This re-constructed path does not exist in vault, so vault reports back 404.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### Important Factoids

#1186 appears to be a similar but separate bug in terms of how vault paths are handled and assumptions made about how a vault path should/can be broken down.

While I'm presently unable to find the code that writes the `mount` and `name` values to the state, one might infer that the values are being manipulated (similar to #1186) with the assumption that a mountpoint only ever contains a single component, and thus everything before the _first_ `/` is the mount, while everything after the _second_ `/` must be the name, while the second component is discarded, presumably because the provider assumes it is the `data` or `metadata` string literal at the end of a mountpoint, without actually looking at it.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #1186

**Comment by ramnarayanp** [comment]
Same issue has been raised previously and has been marked as a bug and will be fixed in a future release. For details and workaround please refer to https://github.com/hashicorp/terraform-provider-vault/issues/1770

**Comment by ram-parameswaran** [comment]
Same issue has been raised previously and has been marked as a bug and will be fixed in a future release. For details and workaround please refer to [1770](https://github.com/hashicorp/terraform-provider-vault/issues/1770)

**Comment by rjhornsby** [comment]
Duplicates #1770
