### ISSUE TITLE
Data source: vault_auth_backends

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform-provider-vault#1793]
### Terraform Version
1.3.3

### Affected Resource(s)
- NEW: vault_auth_backends

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "test1" {
	type = "userpass"
	path = "test-up"
}

resource "vault_auth_backend" "test2" {
	type = "userpass"
	path = "test-up2"
}

resource "vault_auth_backend" "test3" {
	type = "approle"
	path = "test-ar"
}

resource "vault_auth_backend" "test4" {
	type = "approle"
	path = "test-ar2"
}

data "vault_auth_backends" "test" { }
```

### Debug Output
In developing this data source, I've come across the following issues while doing testing, and also have a problem determining the `id` to set for this data source.

```text
2023/03/13 16:38:03 [INFO] Using Vault token with the following policies: root
--- FAIL: TestDataSourceAuthBackends (0.41s)
    testing_new_config.go:82: no "id" found in attributes
    testing_new.go:62: no "id" found in attributes
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     0.798s
FAIL
make: *** [testacc] Error 1
```

The relevant files for developing this feature can be found here: https://github.com/hashicorp/terraform-provider-vault/compare/main...mengesb:terraform-provider-vault:data-source-vault-auth-backends

### Panic Output
N/A

### Expected Behavior
Clean tests, functional new data source

### Actual Behavior
Erroring tests, incomplete `d.SetId()` function on data source

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Clone my fork
2. `vault server -dev`
3. `export VAULT_ADDR=http://127.0.0.1:8200`
4. `export VAULT_TOKEN=...content from vault dev server run...`
5. `export TESTARGS="--run TestDataSourceAuthBackends"`
6. `GOPATH=$CWD make build`
7. `GOPATH=$CWD make testacc`

### Important Factoids
developing new data source

### References
- Addresses GH-1081

**Comment by mengesb** [comment]
My first question relates to this: https://github.com/hashicorp/terraform-provider-vault/compare/main...mengesb:terraform-provider-vault:data-source-vault-auth-backends#diff-c1b251fc6aca149ffa17a2089969644b9ddb974d987e3cdaf49d7c6023496fcbR74

I'm wondering where I might be able to find the provider's vault address to set this as the ID for this data source. I'm open to input on whether that's a good way to do things. In comparison to the AWS provider list style data sources, they use the provider's configured region. I think the most equivalent thing to the vault provider would be the vault server address.

**Comment by mengesb** [comment]
My second question stems from my test failures, which I am unsure whether that's related to the ID or not... however a review over the tests for this new data source would be appreciated as well.

**Comment by fairclothjm** [comment]
Hi @mengesb !

For the first question -- Mostly what we care about the ID is that it is unique. However, the first thing to consider is do we want to make this datasource single-use or multi-use. 

If it is a single-use data source, and we expect users to list all Auth mounts only once in their TF configuration, then we can document that this data source is meant to only be used once. In this case we can set the ID to whatever we prefer. In the past we have simply used the string `default` for the [managed keys resource](https://github.com/hashicorp/terraform-provider-vault/blob/f86e54d09f341760a335c9ea623d77b4c6e7286f/vault/resource_managed_keys.go#L515) for example, since it is only ever meant to be used once.

If we expect this data source to be used multiple times then we may need to think a little more about how we should generate the ID.

As for the second question, the failures do appear to be related to the ID not getting set.

**Comment by mengesb** [comment]
Hi @fairclothjm ,

I tried using `d.SetId("default")` per your recommendation above, however testing is still returning failures

```text
2023/04/04 10:27:28 [INFO] Using Vault token with the following policies: root
--- FAIL: TestDataSourceAuthBackends (0.74s)
    testing_new_config.go:82: no "id" found in attributes
    testing_new.go:62: no "id" found in attributes
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     1.137s
FAIL
make: *** [testacc] Error 1
```

I've pushed changes once more; do you think you can take a look and see what I might be missing?

**Comment by mengesb** [comment]
Now this was odd...

I moved `d.SetId("default")` higher up in the `authBackendsDataSourceRead` function... and I get the following error now

```
--- FAIL: TestDataSourceAuthBackends (1.27s)
    data_source_auth_backends_test.go:19: Step 1/2 error: Check failed: length of paths is 0; want 4
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     1.669s
FAIL
make: *** [testacc] Error 1
```

So this is at least showing my tests run and I can start addressing this.

Does this mean I had some other non-descript error between L45 and L80?

**Comment by mengesb** [comment]
My last remaining headache is trying to get the following test to work correctly:

```go
	// These are not working as expected
		if iState.Attributes["type"] == "userpass" {
			if got, want := len(iState.Attributes["paths"]), 1; got != want {
				return fmt.Errorf("2 length of paths is %d; want %d", got, want)
			}
		} else {
			if got, want := len(iState.Attributes["paths"]), 3; got != want {
				return fmt.Errorf("3 length of paths is %d; want %d", got, want)
			}
		}
```

In my test setup

```go
func TestDataSourceAuthBackends(t *testing.T) {
	typ := "userpass"
	path := []string{"foo", "bar"}

	r.Test(t, r.TestCase{
		Providers: testProviders,
		PreCheck:  func() { testutil.TestAccPreCheck(t) },
		Steps: []r.TestStep{
			{
				Config: testDataSourceAuthBackendsBasic_config,
				Check:  testDataSourceAuthBackends_check,
			},
			{
				Config: testDataSourceAuthBackends_config(path, typ),
				Check:  testDataSourceAuthBackends_check,
			},
		},
	})
}
```

The second step has a set of additional content which is designed to test the filtering. By default, `vault server -dev` should have the `token/` backend, and the code should create an `approle/` and `userpass/` backend. The first test just makes sure the resource works as intended, and it should return 3 backends in that list (`token/`, `userpass/`, `approle/`). The second test should filter the data source to just the `userpass/` backend, and should have a length of 1. When I try test on `len(iState.Attributes["paths"])` I don't seem to be getting the right result - Step 2/2 is reporting length 0 when I want length 1.

```text
--- FAIL: TestDataSourceAuthBackends (2.73s)
    data_source_auth_backends_test.go:20: Step 2/2 error: Check failed: 2 length of paths is 0; want 1
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     3.104s
FAIL
make: *** [testacc] Error 1
```

**Comment by mengesb** [comment]
So while inspecting things that I could be testing against, and while using `data_source_auth_backend_test.go` as a foundation, I did the following:

```go
	fmt.Println("-----------------------")
	fmt.Println(resourceState.Primary.Attributes["paths"])
	fmt.Println(iState.Attributes)
	fmt.Println(iState.Attributes["paths"])
	fmt.Println(iState.Attributes["id"])
	fmt.Println("-----------------------")
```

Here's what I got for output:

```text
-----------------------

map[%:5 accessors.#:3 accessors.0:auth_userpass_a37b713b accessors.1:auth_approle_6560dd29 accessors.2:auth_token_f5af27e6 id:default paths.#:3 paths.0:userpass paths.1:approle paths.2:token type:]

default
-----------------------
--- FAIL: TestDataSourceAuthBackends (0.87s)
    data_source_auth_backends_test.go:20: Step 1/2 error: Check failed: 3 length of paths is 0; want 3
FAIL
FAIL    github.com/hashicorp/terraform-provider-vault/vault     3.407s
FAIL
```

So, `fmt.Println(resourceState.Primary.Attributes["paths"])` output nothing, `fmt.Println(iState.Attributes["paths"])` output nothing, but `fmt.Println(iState.Attributes["id"])` output the correct ID, and `fmt.Println(iState.Attributes)` output the full object, including keys for `accessors`, `paths`, `type`, and `id`. The only key I can evaluate appears to be `id`, which is strange, because when I go back and run the tests for `data_source_auth_backend`, it functions and passes correctly (so long as I comment out my failures with `data_source_auth_backends`).

**Comment by fairclothjm** [comment]
@mengesb Hi, I made some changes to the branch and pushed them here: https://github.com/hashicorp/terraform-provider-vault/compare/auth-backends-datasource-1793.

These are mostly changes to the tests. I think the only change to the code itself was to [sort the paths](https://github.com/hashicorp/terraform-provider-vault/compare/auth-backends-datasource-1793#diff-c1b251fc6aca149ffa17a2089969644b9ddb974d987e3cdaf49d7c6023496fcbR62-R65) to make testing easier.

**Comment by mengesb** [comment]
OK so I see what's done, but doesn't look like I have the skills to cherry pick your changes into my branch to pull your help in directly. Is it OK that I replicate your changes into my fork?

**Comment by mengesb** [comment]
@fairclothjm I managed to get help, either through you via Becca or by Becca. I've pulled in your changes, and these tests look soo much better.
