### ISSUE TITLE
Can't modify a `vault_azure_secret_backend_role` with TF v1.4

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-vault#1807]
### Terraform Version

Terraform version: 1.4.2

### Affected Resource(s)

- `vault_azure_secret_backend_role`

### Terraform Configuration Files

This has been simplified to work as an example.

```hcl
resource "vault_azure_secret_backend_role" "test" {
  backend = "my-path"
  role    = "test"
  ttl     = 3600
  max_ttl = 7200

  azure_roles {
    role_name = "Reader"
    scope     = "/subscriptions"
  }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

When I modify `vault_azure_secret_backend_role` resource (e.g. change the TTL) it should work.

### Actual Behavior

If the `vault_azure_secret_backend_role` resource is modified the following error is thrown.

> Error: must specify at most one of 'role_name' or 'role_id'
>
>  with vault_azure_secret_backend_role.test,
  on main.tf line 1, in resource "vault_azure_secret_backend_role" "test":
  34: resource "vault_azure_secret_backend_role" "test" {

### Steps to Reproduce

Modify a `vault_azure_secret_backend_role` resource specifying `azure_roles` with terraform `v1.4.2`.

### Important Factoids

 n/a

### References

n/a

**Comment by stevehipwell** [comment]
This appears to be related to https://github.com/hashicorp/terraform-provider-vault/issues/1632.

**Comment by florentvaldelievre** [comment]
Same issue reproduced on the latest Hashicorp Vault Provider (v3.15.2) and Terraform 1.4.6 and 1.5.0-rc1.
When using Terraform 1.3.X, it works, but it recreates the roles each time as mentioned in [#1632](https://github.com/hashicorp/terraform-provider-vault/issues/1632.)
