### ISSUE TITLE
vault_gcp_secret_impersonated_account resource does not support `ttl` parameter

### ISSUE THREAD

**Issue by itspngu** [hashicorp/terraform-provider-vault#1812]
### Terraform Version
terraform -v
Terraform v1.4.3-dev
on linux_amd64

### Affected Resource(s)
- vault_gcp_secret_impersonated_account

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "vault_gcp_secret_impersonated_account" "impersonated_account" {
  backend        = vault_gcp_secret_backend.gcp.path

  impersonated_account  = "this"
  service_account_email = google_service_account.this.email
  token_scopes          = ["https://www.googleapis.com/auth/cloud-platform"]
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The `vault_gcp_secret_impersonated_account` resource should support the `ttl` parameter [exposed by the corresponding Vault API endpoint](https://developer.hashicorp.com/vault/api-docs/secret/gcp#ttl-1).

### Actual Behavior
The `vault_gcp_secret_impersonated_account` resource does not expose the `ttl` parameter.

### Steps to Reproduce
n/a

### Important Factoids
n/a

### References
n/a

**Comment by ambis** [comment]
This would be essential especially in the case where the TTL could be configured to be less than 1h (not sure yet if this is possible), since the static_account TTL is always 1h.

**Comment by itspngu** [comment]
> This would be beneficial for places like CI which runs fast and only needs a short TTL token.

Hey there @ambis :wave:

I've not tried it myself because our CI runs on Github and there's a "native" means of having workflows in Github Actions authenticate to Google Cloud called [Workload Identity Federation](https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions) (pretty much just a fancy wrapper around OIDC).

If that's not an option you might want to look into making _the tokens returned by the auth method_ your CI system uses short-lived (instead of setting short TTLs on _the secrets themselves_), Vault will periodically clean up "dangling" secret leases (for secrets from dynamic secrets engines, for static secrets there's nothing to clean up) after the token used to create them has expired.

This could possibly be further optimized by using non-renewable [Batch Tokens](https://developer.hashicorp.com/vault/tutorials/tokens/batch-tokens) with a fixed TTL for the CI usecase specifically, but I've not experimented with those yet and I'm not 100% sure they properly work with dynamic secrets.
