### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by netflash** [hashicorp/terraform-provider-vault#1850]
https://github.com/hashicorp/terraform-provider-vault/blob/e55cfcd486a3cc13ca401954c0b6fb0adbb48948/website/docs/r/identity_mfa_pingid.html.md?plain=1#L17

Here it says DUO, which looks dodgy. Should it be `pingid`?

**Comment by hsimon-hashicorp** [comment]
@yhyakuna @benashz can we verify this?
