### ISSUE TITLE
LDAP backend update breaks bindpass

### ISSUE THREAD

**Issue by bmhughes** [hashicorp/terraform-provider-vault#1870]
### Terraform Version
`Terraform v1.4.6`

### Affected Resource(s)

- `vault_ldap_secret_backend`

### Expected Behavior

Updating the vault provider should not update `bindpass` as it will have been rotated by Vault.

### Actual Behavior

Due to a combined create/update function the `bindpass` setting is set back to the orignial value which breaks the LDAP backend as it is no longer the bind account password.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- #1859 
- @raymonstah

**Comment by raymonstah** [comment]
Hey @bmhughes, thanks for raising this issue.

Would you be able to post your steps to reproduce?

**Comment by bmhughes** [comment]
Yes, that's exactly what I ran into.

**Comment by raymonstah** [comment]
Hmm, unfortunately I'm not able to reproduce this. Can you send me more details?

1. What change are you making to `vault_ldap_secret_backend` to trigger the update?
2. What version of Vault are you running?
3. Are you using a local dev build of `terraform-provider-vault` using the `main` branch?

**Comment by bmhughes** [comment]
1. Any change does it for me, the createUpdate func doesn't call HasChange so it sends the full map every time does it not? I think I changed description the first time I triggered it, I can check in the morning. 
2. Vault 1.13.1
3. Main branch.

**Comment by bmhughes** [comment]
I just remembered, it was password policy that I'd changed.

**Comment by raymonstah** [comment]
Awesome thanks, and if you could send the exact error message you're getting that would be great. In the mean time, we'll continue investigating! 🕵🏼

**Comment by raymonstah** [comment]
After some investigation, I don't believe the the bug is on the terraform provider side. The LDAP implementation seems to be consistent with other secrets engine, which sends the password on updates. You're correct in that removing the password field from the update function provides the desired result, but this also removes the ability to update passwords, assuming the user is not rotating root credentials. 

It also sounds like you're specifying `schema = 'AD' in your config`, right?

We'll continue investigating, and I'll keep you updated. Thanks for your patience!

**Comment by bmhughes** [comment]
Yes, I'm using the `AD` schema.

You're right good point, it does prevent the `bindpass` being changed later wrapping it in `d.HasChange` instead should cover all cases?

**Comment by bmhughes** [comment]
Just some ideas from my playing around.

This works for the `bindpass` issue but opens up the `schema` one again
```go
for _, field := range fields {
	if !d.HasChange(field) {
		continue
	}

	if v, ok := d.GetOk(field); ok {
		data[field] = v
	}
}
```
Which nessitates adding something like this but I'm not sure if this is hacky.
```go
// Ensure schema is set if data is not empty
if len(data) > 0 {
	if _, ok := data[consts.FieldSchema]; !ok {
		if v, ok := d.GetOk(consts.FieldSchema); ok {
			data[consts.FieldSchema] = v
		}
	}
}
```

**Comment by raymonstah** [comment]
Update: there's a potential fix here: https://github.com/hashicorp/terraform-provider-vault/pull/1875

@bmhughes when you have a moment would you be able to check out that branch and see if it fixes the issue you're facing?

**Comment by bmhughes** [comment]
Yes that works, it's pretty much the same thing I've tried but just for the bindpass field.
