### ISSUE TITLE
Update vault_pki_secret_backend_role resource to support cn_validations

### ISSUE THREAD

**Issue by christophecolly** [hashicorp/terraform-provider-vault#1883]
Hi there,

The [`vault_pki_secret_backend_role`](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/pki_secret_backend_role) resource is missing the[ `cn_validations` ](https://developer.hashicorp.com/vault/api-docs/secret/pki#cn_validations) argument.
It would be great to have this fixed.

### Terraform Version
terraform: v1.4.6
registry.terraform.io/hashicorp/vault: v3.15.2

### Affected Resource(s)
- [vault_pki_secret_backend_role](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/pki_secret_backend_role)

**Comment by stevendpclark** [comment]
Closing as #1820 has been merged.
