### ISSUE TITLE
Is there a vault_oidc_auth_backend_config?

### ISSUE THREAD

**Issue by specterops-avongluck** [hashicorp/terraform-provider-vault#1894]
Working to codify some existing infrastructure into Terraform, and there doesn't appear to be a vault_oidc_auth_backend* resource type to configure oidc auth backends?  We have captured everything else (kubernetes, approle, etc), however oidc stands out not having backend config resources.

### Terraform Version
```
$ terraform -v
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/vault v3.15.2
```

### Affected Resource(s)
- vault_auth_backend , type oidc

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "oidc" {
  type = "oidc"
}

# ??? How do we capture this config?
```

**Comment by fairclothjm** [comment]
@specterops-avongluck Hello, please take a look at https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend

**Comment by specterops-avongluck** [comment]
Oh.. ok.   So does this replace the need for:

```terraform
resource "vault_auth_backend" "oidc" {
  type = "oidc"
}
```

The rest of the backend auth's (except ldap and oidc?)  depend on vault_auth_backend in the documentation.

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault](https://discuss.hashicorp.com/c/vault/30).
