### ISSUE TITLE
Vault provider validates token during initialization phase, breaking code that installs and configures Vault in the same `terraform apply`

### ISSUE THREAD

**Issue by zanecodes** [hashicorp/terraform-provider-vault#1907]
Prior to `vault` provider version `3.16.0`, Terraform could be prevented from connecting to the Vault server during Terraform initialization by setting the `skip_child_token` and `skip_get_vault_version` options to `true`.

This enabled us to both create and configure a Vault server in the same `terraform apply`, which is very useful for automating Vault server deployments as well as testing Vault configuration code by running it against a local development environment created in Docker.

As of `3.16.0`, setting `skip_child_token` and `skip_get_vault_version` to `true` no longer prevents Terraform from connecting to the Vault server during Terraform initialization; the provider will always attempt to lookup the configured Vault token.

This change in behavior was introduced by this change in the following commit: https://github.com/hashicorp/terraform-provider-vault/commit/be43ceafe94fc1097ff0fb784c1f5b1c940ee42a#diff-967662bfcf527885a3604134d7f576203069ea8db8b7b03b92756448d87847afR273

Eagerly validating the token and Vault URL during planning seems like a valuable thing to do in the general case, since it allows users to catch mistakes before running `terraform apply`, but an option to explicitly opt out of this behavior would also be appreciated, for the case where the user knows the token and URL will not be valid during planning but will become valid during the `terraform apply`.

Adding an option to explicitly opt out of provider configuration validation, similar to the [bootstrap](https://registry.terraform.io/providers/rancher/rancher2/latest/docs#bootstrap) option available in the `rancher2` Terraform provider, could be a good solution.

### Terraform Version

```
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/vault v3.16.0
```

### Affected Resource(s)

- `vault` provider

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vault = {
      source = "hashicorp/vault"
      version = "3.16.0"
    }
    docker = {
      source = "kreuzwerker/docker"
      version = "3.0.2"
    }
  }
}

resource "docker_container" "vault" {
  name = "vault"
  image = "sha256:9e622613a2d513f092ae49a2b5d182382f817d125f5cbe97069f045d16fb8a95"

  env = ["VAULT_DEV_ROOT_TOKEN_ID=token"]

  ports {
    internal = 8200
    external = 8200
  }
}

provider "vault" {
  address = "http://localhost:8200"
  token = "token"

  skip_child_token = true
  skip_get_vault_version = true
}

resource "vault_policy" "test" {
  name = "test"

  policy = <<-EOH
    path "test" {
      capabilities = ["read"]
    }
  EOH

  depends_on = [docker_container.vault]
}
```

### Expected Behavior

`terraform apply` should succeed

### Actual Behavior

`terraform apply` fails with the following error:

```
_
│ Error: failed to lookup token, err=Get "http://localhost:8202/v1/auth/token/lookup-self": dial tcp [::1]:8202: connect: connection refused
│
│   with provider["registry.terraform.io/hashicorp/vault"],
│   on main.tf line 26, in provider "vault":
│   26: provider "vault" {
│
_
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

Note that this workflow will succeed as expected if the version of the `vault` provider is downgraded to `3.15.2`.

### References
- #192 
- #1198 
- #1541

**Comment by M1kep** [comment]
This also breaks a workaround for https://github.com/hashicorp/terraform-provider-vault/issues/666 where Terraform attempts to validate a provider, even if it is not used in a module.

**Comment by zanecodes** [comment]
Awesome work on #2049 @benashz! I've been testing a build of the provider with that branch merged in for a week or two now for my use case and it works perfectly, enabling me to cut out another 40 lines of ugly workarounds involving http data sources and `depends_on` ❤️

**Comment by fairclothjm** [comment]
The fix is available in https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.23.0
