### ISSUE TITLE
Add ACME support for PKI resource

### ISSUE THREAD

**Issue by igor-nikiforov** [hashicorp/terraform-provider-vault#1947]
Starting from Vault 1.14 added support for ACME protocol - https://www.hashicorp.com/blog/vault-1-14-brings-acme-for-pki-aws-roles-and-more-improvements

It would be great to have support for following resources to be able configure ACME from Terraform:
- [Set ACME configuration](https://developer.hashicorp.com/vault/api-docs/secret/pki#set-acme-configuration)
- [Set Cluster Configuration](https://developer.hashicorp.com/vault/api-docs/secret/pki#set-cluster-configuration)
- [Get ACME EAB Binding Token](https://developer.hashicorp.com/vault/api-docs/secret/pki#get-acme-eab-binding-token)

**Comment by Viper61** [comment]
Hi there,

We were looking for this too.  
A PR was opened to add cluster configuration as a first step.

I'll try to get the ACME configuration up too.  
There is one part I haven't looked at yet, and have doubts.  
It's about the headers' configuration and how this part should be handled by the provider.

```
vault secrets tune \
      -passthrough-request-headers=If-Modified-Since \
      -allowed-response-headers=Last-Modified \
      -allowed-response-headers=Location \
      -allowed-response-headers=Replay-Nonce \
      -allowed-response-headers=Link \
      pki_int
```

**Comment by jeffsanicola** [comment]
I think the `enable_templating` option is also missing from [`vault_pki_secret_backend_config_urls`](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/pki_secret_backend_config_urls) based on the instructions in the [tutorial](https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-acme-caddy#enable-pki-secrets-engine).

**Comment by igor-nikiforov** [comment]
I was able to setup ACME + Cluster configuration using `vault_generic_endpoint` resource as temporary workaround. But unfortunately this resource does not support POST method which is [required](https://developer.hashicorp.com/vault/api-docs/secret/pki#get-acme-eab-binding-token) by `acme/new-eab` endpoint. So for now there no way to automate EAB token creation using only bare TF resources.

@fairclothjm just wondering is there any ETA for full ACME support in Vault provider? Thanks.

**Comment by fairclothjm** [comment]
@igor-nikiforov Hello, unfortunately we don't have an ETA for full ACME support. We will update this issue once we get an update.

**Comment by stevendpclark** [comment]
Closing out this request as all the associated resources for PKI ACME have been merged and successfully tested with the following terraform script. Thanks everyone for your contributions on getting this feature within the Vault provider!

```
resource "vault_mount" "test" {
  path        = "pki"
  type        = "pki"
  description = "PKI secret engine mount"
  passthrough_request_headers = [
    "If-Modified-Since"
  ]
  allowed_response_headers = [
    "Last-Modified",
    "Location",
    "Replay-Nonce",
    "Link"
  ]
}

resource "vault_pki_secret_backend_role" "test" {
  backend          = vault_mount.test.path
  name             = "test-role"
  allowed_domains  = ["local"]
  allow_subdomains = true
  key_type         = "any"
}

resource "vault_pki_secret_backend_root_cert" "test" {
  backend     = vault_mount.test.path
  type        = "internal"
  common_name = "test"
  ttl         = "86400"
  issuer_name = "test-issuer"
}

resource "vault_pki_secret_backend_config_cluster" "pki_config_cluster" {
  backend  = vault_mount.test.path
  path     = "http://127.0.0.1:8200/v1/pki"
  aia_path = "http://127.0.0.1:8200/v1/pki"
}

resource "vault_pki_secret_backend_config_acme" "pki_config_acme" {
  backend                  = vault_mount.test.path
  enabled                  = true
  allowed_issuers          = [vault_pki_secret_backend_root_cert.test.issuer_name]
  allowed_roles            = [vault_pki_secret_backend_role.test.name]
  allow_role_ext_key_usage = true
  default_directory_policy = format("role:%s", vault_pki_secret_backend_role.test.name)
  eab_policy               = "always-required"
}

resource "vault_pki_secret_backend_acme_eab" "test" {
  depends_on = [vault_pki_secret_backend_config_acme.pki_config_acme]
  backend    = vault_mount.test.path
}
```
