### ISSUE TITLE
`client_id` and `client_secret` is undocumented for `vault_identity_oidc_client`

### ISSUE THREAD

**Issue by aucampia** [hashicorp/terraform-provider-vault#1960]
`vault_identity_oidc_client` provides `client_id` and `client_secret` as output:

https://github.com/hashicorp/terraform-provider-vault/blob/9f1b371673291df05abc0247fdea0fcb0bc060ed/vault/resource_identity_oidc_client.go#L68-L78

But it is not documented as far as I can tell:

https://github.com/hashicorp/terraform-provider-vault/blob/9f1b371673291df05abc0247fdea0fcb0bc060ed/website/docs/r/identity_oidc_client.html.md

**Comment by jgrumboe** [comment]
I can do this, if that's fine.
