### ISSUE TITLE
Vault provider does not update description of previously created AWS secrets engine mount

### ISSUE THREAD

**Issue by Shocktrooper** [hashicorp/terraform-provider-vault#1982]
### Terraform Version
`Terraform v1.5.4`

Vault Version:
`1.14.1`

### Affected Resource(s)
- `vault_aws_secret_backend`

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend" "group-aws-mount" {
  path                      = "group-aws"
  description               = "AWS Engine mount for group"
  default_lease_ttl_seconds = 600
  max_lease_ttl_seconds     = 600
}
```

### Debug Output
- `TODO` Will update later when I have a chance

### Expected Behavior
`Terraform should have updated the description to the correct text for the AWS secrets engine.  Initial creation of the resource works as expected.`

### Actual Behavior
`The descriptions stayed the same even though the apply says it completed successfully.  The vault UI itself showed no change and the next terraform plan showed a plan to change still that should have happened during the previous apply.`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
`It is important to note that using the vault CLI the description updated successfully thus the terraform provider itself seems to be the issue`

### References
`None I could find`

**Comment by jgrumboe** [comment]
I'd like to take this, if that's fine.

**Comment by Shocktrooper** [comment]
@jgrumboe Feel free!
