### ISSUE TITLE
[Enhancement]: OIDC auth method config resource

### ISSUE THREAD

**Issue by abexamir** [hashicorp/terraform-provider-vault#1998]
### Description

Unlike other auth methods (kubernetes, aws, azure, gcp, github, jwt, ...), there is no resource to provide configurations for oidc auth method, is this intentional? I want to have all my auth methods in terraform and I don't want to be bound to vault itself for configuring my oidc auth method.

### Affected Resource(s) and/or Data Source(s)

* vault_auth_backend

### Potential Terraform Configuration

```terraform
vault_oidc_auth_backend_config "oidc_config" {
   backend = vault_auth_backend.oidc.path
   oidc_discovery_url = "https://example.com"
}
vault_oidc_auth_backend_client_config "oidc_client_config" {
   backend = vault_auth_backend.oidc.path
   oidc_client_id = "something"
}
```

### Would you like to implement a fix?

Yes

**Comment by fairclothjm** [comment]
@abexamir Hello!

Can you take a look to see if https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend covers all your requirements?

In particular it can be used to manage the OIDC auth backend:

```hcl

resource "vault_jwt_auth_backend" "example" {
    description         = "Demonstration of the Terraform JWT auth backend"
    path                = "oidc"
    type                = "oidc"
    oidc_discovery_url  = "https://myco.auth0.com/"
    oidc_client_id      = "1234567890"
    oidc_client_secret  = "secret123456"
    bound_issuer        = "https://myco.auth0.com/"
    ...
}
```

**Comment by abexamir** [comment]
> @abexamir Hello!
> 
> Can you take a look to see if https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend covers all your requirements?
> 
> In particular it can be used to manage the OIDC auth backend:
> 
> ```terraform
> resource "vault_jwt_auth_backend" "example" {
>     description         = "Demonstration of the Terraform JWT auth backend"
>     path                = "oidc"
>     type                = "oidc"
>     oidc_discovery_url  = "https://myco.auth0.com/"
>     oidc_client_id      = "1234567890"
>     oidc_client_secret  = "secret123456"
>     bound_issuer        = "https://myco.auth0.com/"
>     ...
> }
> ```

Thank you! I tested it and it works like a charm. 
However, it's a bit ambiguous that there's a specific resource for every provider but for oidc that's merged into jwt provider.
