### ISSUE TITLE
[DOCS:] How to specify ldap engine schema 

### ISSUE THREAD

**Issue by jhfeng** [hashicorp/terraform-provider-vault#2002]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/3.20.0/docs/resources/ldap_secret_backend

### Description

In vault_ldap_secret_backend, there is no mmention how to specify ldap engine schema. The default I got is OpenLDAP
but I need to use "ad"
.
.....
deny_null_bind            true
dereference_aliases       never
discoverdn                false
groupattr                 cn
groupdn                   n/a
groupfilter               (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls              false
max_page_size             0
request_timeout           90
**schema                    openldap**
starttls                  false
tls_max_version           tls12
tls_min_version           tls12
....

### Would you like to implement a fix?

None

**Comment by fairclothjm** [comment]
@jhfeng Hi Jeff, you can use the `schema` field. However, it looks like this was missed in the documentation. We will get that added.

**Comment by fairclothjm** [comment]
For example:

```
resource "vault_ldap_secret_backend" "config" {
  path          = "ad"
  binddn        = "CN=Administrator,CN=Users,DC=corp,DC=example,DC=net"
  bindpass      = "bar"
  url           = "ldaps://localhost"
  schema = "ad"
}
```

**Comment by jhfeng** [comment]
> @jhfeng Hi Jeff, you can use the `schema` field. However, it looks like this was missed in the documentation. We will get that added.

@fairclothjm  Thanks. that works. Glad see you here virtually !
