### ISSUE TITLE
[Bug]: GCP auth provider using the wrong audience for GCE token

### ISSUE THREAD

**Issue by AlejandroSanchezGeotab** [hashicorp/terraform-provider-vault#2055]
### Terraform Core Version

1.6.1

### Terraform Vault Provider Version

3.21.0

### Vault Server Version

1.14.1

### Affected Resource(s)

provider "vault"

### Expected Behavior

Provider should be able to login to vault using GCP authentication and GCE tokens.

### Actual Behavior

Provider fails to login because the GCE JWT token's audience is incorrect.

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.


Error: Error making API request.

URL: PUT https://my-vault/v1/auth/gcp/login
Code: 400. Errors:

* at least one of the JWT claim 'aud' must end in "vault/my-role"

  with provider["registry.terraform.io/hashicorp/vault"],
  on terraform.tf line 13, in provider "vault":
  13: provider "vault" {
```

### Terraform Configuration Files
```
terraform {
  required_version = ">= 1.0.0, < 2.0.0"
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = ">= 3.21.0"
    }
  }
}

provider "vault" {
  address = "https://my-vault"
  auth_login_gcp {
    role = "my-role"
  }
}
```
### Steps to Reproduce

Run `terraform plan` on a GCE instance with a default Google service account authorized to access vault.

### References

The GCE token's audience is set to `<role>/vault` in the following line: https://github.com/hashicorp/terraform-provider-vault/blob/main/internal/provider/auth_gcp.go#L213C16-L213C16
According to the documentation and our testing, the audience should be `vault/<role>`: https://developer.hashicorp.com/vault/docs/auth/gcp#curl-example-1
The `http://` prefix seen in the documentation's audience example doesn't seem to matter.

### Would you like to implement a fix?

No

**Comment by OneWhoNests** [comment]
fixed #2064
