### ISSUE TITLE
Terraform Crash: Terraform version: 0.11.8, terraform-provider-vault_v1.1.4_x4

### ISSUE THREAD

**Issue by ahartma1** [hashicorp/terraform-provider-vault#210]
### Terraform Version
Terraform version: 0.11.8

### Affected Resource(s)
- vault_database_secret_backend_connection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "vault_database_secret_backend_connection" "postgres" {
  backend       = "${vault_mount.db.path}"
  name          = "postgres"
  allowed_roles = ["*"]

  postgresql {
    connection_url = "postgresql://${var.db_username}:${var.db_password}@${var.db_host}:5432/${var.db_name}"
  }
}
```

### Debug Output
https://gist.github.com/ahartma1/4ce23a26949b1a404efc6a3c6da82169#file-crash-log

### Panic Output
https://gist.github.com/ahartma1/4ce23a26949b1a404efc6a3c6da82169#file-panic

### Expected Behavior
Terraform should have honored the previously executed connection resource

### Actual Behavior
when i variablized the password and hostname, it started to crash terraform. Happened multiple consecutive times. 

### Steps to Reproduce
1. `terraform apply`
2. Observe resources create normally,
3. change another dependent resource, like the vault_database_secret_backend_role.
4. `terraform apply`
5. observe crash

### Important Factoids
Running via Atlantis.
works if you destroy and apply locally from windows vm

### References
none

**Comment by benashz** [comment]
This issue should be resolved in the current provider release. If the issue persists please open a new issue.

Thanks!
