### ISSUE TITLE
[Docs]: Vault provider 3.23.0 - [Data Sources] vault_aws_static_credentials

### ISSUE THREAD

**Issue by Hui012** [hashicorp/terraform-provider-vault#2121]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/aws_static_credentials

### Description

Hello,

I'm trying to get aws static role creds via terraform vault provider,

However, my terminal says [The provider hashicorp/vault does not support data source "vault_aws_static_credentials".]

So I executed "terraform providers schema -json", I found that [vault_aws_static_credentials] does not exist,

The corresponding Key in schema is [vault_aws_static_access_credentials],

Please help to confirm again, thank you a lot.

### Would you like to implement a fix?

None

**Comment by fairclothjm** [comment]
@Hui012 Thanks for reporting! I have a PR to fix the docs #2122
