### ISSUE TITLE
Support configuring plugins in Vault's plugin catalog

### ISSUE THREAD

**Issue by JayH5** [hashicorp/terraform-provider-vault#214]
### Terraform Version
```
Terraform v0.11.8
+ provider.vault v1.1.4
```

### Affected Resource(s)
A suitable resource does not exist yet.

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
There should be a resource type to add plugins to Vault's plugin catalog. This process is described in this blog post: https://www.hashicorp.com/blog/building-a-vault-secure-plugin

The main thing I am asking for here is native support for writing to the plugin catalog, like:
`vault write sys/plugins/catalog/my-plugin command=my-plugin sha256=fc1c3225364b5cdb570c0b1e7be8ebf2725bdabf472c86e4095b4880083606a3`

Such a resource could be called something like `vault_plugin` or `vault_catalog_plugin`.

It is possible to approximate this with the `vault_generic_secret` resource.

### Actual Behavior
There is not such a resource type.

### Steps to Reproduce
N/A

### References
- GH-54 is a related issue for configuring which plugin to use when mounting an auth backend.

**Comment by cpick** [comment]
It's ugly, but you can work around this by using:
```terraform
resource "vault_generic_secret" "plugin_registration" {
  path         = "sys/plugins/catalog/my-plugin-name"
  disable_read = true

  data_json = <<-EOF
    {
      "sha_256": "...",
      "command": "my-plugin-command"
    }
  EOF
}
```

**Comment by mbrancato** [comment]
Simlarly, we use this:

```hcl
resource "vault_generic_endpoint" "plugin_name" {
  disable_read         = false
  disable_delete       = true
  path                 = "sys/plugins/catalog/secret/pluginname"
  ignore_absent_fields = true

  data_json = jsonencode({
    sha_256 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaa..."
    command = "pluginname_v1"
  })
}
```

**Comment by TJM** [comment]
With the new versioned plugins, a simple `vault_generic_endpoint` is not going to cut it. I have a workaround using "curl" commands in the scottwinker_shell provider, but I feel like it is time to add this properly.
