### ISSUE TITLE
[Docs]: Typo at `/data-sources/auth_backends`

### ISSUE THREAD

**Issue by aRustyDev** [hashicorp/terraform-provider-vault#2167]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/auth_backends

### Description

The Example has one of its examples out of the backticks or is missing the backticks at the end

### Would you like to implement a fix?

None

**Comment by aRustyDev** [comment]
Created PR to fix it [2168](https://github.com/hashicorp/terraform-provider-vault/pull/2168)

**Comment by Zlaticanin** [comment]
Fix merged - [2168](https://github.com/hashicorp/terraform-provider-vault/pull/2168)
