### ISSUE TITLE
[Docs]: num_seconds_between_tests 7 seconds or 1 second?

### ISSUE THREAD

**Issue by goegol** [hashicorp/terraform-provider-vault#2173]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/azure_access_credentials

### Description

The text says 7 seconds (If validate_creds is used, by default, credentials will be validated by making a test call to Azure every 7 seconds) but the code description says 1 ( (Optional) If 'validate_creds' is true, the number of seconds to wait between each test of generated credentials. Defaults to 1.) 

![image](https://github.com/hashicorp/terraform-provider-vault/assets/23667718/64c1c172-20e0-4678-8695-2557191956ab)

![image](https://github.com/hashicorp/terraform-provider-vault/assets/23667718/2cbf31f8-2212-4f81-98c1-e1a0a843b23e)

### Would you like to implement a fix?

Yes

**Comment by F21** [comment]
Looking at the source, I think it's every 1 second: https://github.com/hashicorp/terraform-provider-vault/blob/main/vault/data_source_azure_access_credentials.go#L72
