### ISSUE TITLE
[Bug]: data vault_auth_backend failed to read from Vault

### ISSUE THREAD

**Issue by ron-benaim-af** [hashicorp/terraform-provider-vault#2196]
### Terraform Core Version

1.4.4

### Terraform Vault Provider Version

4.0.0

### Vault Server Version

1.9.10

### Affected Resource(s)

data vault_auth_backend

### Expected Behavior

Read backend data from Vault so I can use the accessor attribute 

### Actual Behavior

Error: error reading from Vault: error reading from Vault: Error making API request.
│ 
│ URL: GET https://vault.example.com:8200/v1/sys/auth/oidc
│ Code: 405. Errors:
│ 
│ * 1 error occurred:
│     * unsupported operation
│ 

When using provider version 3.25.0 with the same TF code it works. 

### Terraform Configuration Files

data "vault_auth_backend" "auth_backend_oidc" {
  path = "oidc"
}

### Steps to Reproduce

Just use the configuration file mentioned in your TF code and it fails to read from Vault

### Would you like to implement a fix?

None

**Comment by fairclothjm** [comment]
Hello @rednap. I am sorry you are having trouble!

As per the [v4.0.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/guides/version_4_upgrade), the Terraform Vault Provider only supports Vault server version 1.11.x and greater. We recommend you upgrade your Vault server.

**Comment by fairclothjm** [comment]
Hello @ron-benaim-af. I am sorry you are having trouble!

As per the [v4.0.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/guides/version_4_upgrade), the Terraform Vault Provider only supports Vault server version 1.11.x and greater. We recommend you upgrade your Vault server.

**Comment by fairclothjm** [comment]
Closing as Vault server version 1.9 is no longer supported.

**Comment by ron-benaim-af** [comment]
@fairclothjm thank you, missed that 🙏
