### ISSUE TITLE
[Docs]: MFA type is not documented

### ISSUE THREAD

**Issue by RRcwhiting** [hashicorp/terraform-provider-vault#2272]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/identity_mfa_okta#type

### Description

The value of MFA type is not documented. What options are there? do they need to be uppercase or lowercase?

### Would you like to implement a fix?

No

**Comment by fairclothjm** [comment]
@RRcwhiting The `type` attribute is exported. This is not a field that you set in your config. Resource instances managed by Terraform each export attributes whose values can be used elsewhere in configuration. 

https://developer.hashicorp.com/terraform/language/values/outputs
