### ISSUE TITLE
[Docs]: vault_config_ui_custom_message incorrect arguments

### ISSUE THREAD

**Issue by pvickery-ParamountCommerce** [hashicorp/terraform-provider-vault#2352]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/config_ui_custom_messages#message

### Description

The argument `message` should be `message_base64`

```
❯ terraform apply        
╷
│ Error: Missing required argument
│ 
│   on <path> line 121, in resource "vault_config_ui_custom_message" "this":
│  121: resource "vault_config_ui_custom_message" "this" {
│ 
│ The argument "message_base64" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on <path> line 123, in resource "vault_config_ui_custom_message" "this":
│  123:   message       = base64encode("Message")
│ 
│ An argument named "message" is not expected here.
╵
```

### References

https://github.com/hashicorp/terraform-provider-vault/blob/3418cb7063e9cda744f67b80356b6f5e98cdac68/vault/resource_config_ui_custom_message.go#L40

### Would you like to implement a fix?

None

**Comment by pvickery-ParamountCommerce** [comment]
Possibly related, but after fixing the argument name, I get the following error:
```
module.vault.vault_config_ui_custom_message.this: Creating...
╷
│ Error: config_ui_custom_message is not supported by this version of vault
```

I am using  `registry.terraform.io/hashicorp/vault v4.4.0`

**Comment by fairclothjm** [comment]
@pvickery-ParamountCommerce Thanks for reporting the docs issue. I have opened https://github.com/hashicorp/terraform-provider-vault/pull/2356 to address that.

In regards to the recent error you posted, can verify what version of the Vault Server you are running?  It looks like Custom UI messages were introduced in Vault v1.16 and require Vault Enterprise.

**Comment by pvickery-ParamountCommerce** [comment]
@fairclothjm Ah that would explain it, we are using the open source version.

Could a note be added to the documentation to indicate that it is a Enterprise feature? For example, [vault_namespace](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/namespace) has one.

**Comment by fairclothjm** [comment]
Will add a note, Thanks!
