### ISSUE TITLE
[Bug]: vault_kubernetes_secret_backend empty jwt when disable_local_ca_jwt true

### ISSUE THREAD

**Issue by mikkel3000** [hashicorp/terraform-provider-vault#2369]
### Terraform Core Version

1.9.2

### Terraform Vault Provider Version

4.4.0

### Vault Server Version

1.17.3

### Affected Resource(s)

vault_kubernetes_secret_backend

### Expected Behavior

When using `vault_kubernetes_secret_backend` with empty `kubernetes_ca_cert = null` and `disable_local_ca_jwt = true` the service account jwt should be populated, but is not.

Setting kubernetes secret backend with:

```
resource "vault_kubernetes_secret_backend" "vault-kubernetes-secret-backend" {
  count                = 1
  path                 = "kubernetes-example-cluster"
  kubernetes_host      = "https://cluster-api.example-cluster.myorg.com"
  kubernetes_ca_cert   = null
  service_account_jwt  = "EXAMPLEJWT"
  disable_local_ca_jwt = true
}

```
Expects to see.
![image](https://github.com/user-attachments/assets/bea80057-64db-4988-bb3d-2684e46d91fa)

### Actual Behavior

Service Account JWT is empty.
I did not use "EXAMPLEJWT" when applying it, i used an actual service account jwt.
Gives following in vault ui:
![image](https://github.com/user-attachments/assets/d4221bd5-5caf-431d-a61c-a2d146758ab6)

### Relevant Error/Panic Output Snippet

```shell
No errors, works fine from vault ui.
```

### Terraform Configuration Files

```
resource "vault_kubernetes_secret_backend" "vault-kubernetes-secret-backend" {
  count                = 1
  path                 = "kubernetes-example-cluster"
  kubernetes_host      = "https://cluster-api.example-cluster.myorg.com"
  kubernetes_ca_cert   = null
  service_account_jwt  = "EXAMPLEJWT"
  disable_local_ca_jwt = true
}
```

### Steps to Reproduce

Try to apply the terraform resource and observe the missing JWT. 

### Would you like to implement a fix?

None

**Comment by fairclothjm** [comment]
Hello @mikkel3000, I am sorry you are having trouble here.

I believe this is expected behavior. The `service_account_jwt` is not returned in the READ request from the kubernetes backend's /config endpoint so the UI will have no way of displaying it.

```
$ vault write -f kubernetes/config kubernetes_host=foo service_account_jwt="header.payload.signature"
Success! Data written to: kubernetes/config

$ vault read kubernetes/config
Key                     Value
---                     -----
disable_local_ca_jwt    false
kubernetes_ca_cert      n/a
kubernetes_host         foo
```

**Comment by mikkel3000** [comment]
Ah, okay thanks. I guess something else must be the problem!
