### ISSUE TITLE
vault_ldap_auth_backend: vault backend still exists after create failure

### ISSUE THREAD

**Issue by mrparkers** [hashicorp/terraform-provider-vault#266]
### Terraform Version
Terraform v0.11.10
+ provider.google v1.20.0
+ provider.vault v1.4.1

### Affected Resource(s)
- `vault_ldap_auth_backend`

### Expected Behavior
When this resource is created but an error occurs, the ldap backend should be removed from vault.

### Actual Behavior
The ldap backend remains in vault if the resource errors when creating.  Subsequent runs of `tf apply` fail, because the backend already exists.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an invalid config for `vault_ldap_auth_backend`. I did this by specifying a `certificate` that was not in x509 format.
2. `tf apply` - results in an error
3. Fix the invalid config
4. `tf apply` - results in an error, because the backend already exists

### References
[This line of code](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_ldap_auth_backend.go#L155) should be changed to check for an error, and remove the backend if the update operation failed.

I will happily submit a PR for this if I get some confirmation that this is not the intended behavior.

Thanks!

**Comment by fairclothjm** [comment]
Closing as this has been fixed
