### ISSUE TITLE
vault_generic_secret should be renamed to vault_generic

### ISSUE THREAD

**Issue by chrismatteson** [hashicorp/terraform-provider-vault#276]
It works perfectly fine for non "secret" resources. For instance I can manage azure auth config with it:

resource "vault_generic_secret" "example" {
  path = "auth/azure/config"

  data_json = <<EOT
{
    "client_id": "",
    "environment": "AzurePublicCloud",
    "resource": "https://vault.hashicorp.com",
    "tenant_id": "11111111-2222-3333-4444-55555555555"
}
EOT
}

**Comment by cvbarros** [comment]
See discussion and changes on #244 regarding this topic.

**Comment by fairclothjm** [comment]
closed by https://github.com/hashicorp/terraform-provider-vault/pull/374
