### ISSUE TITLE
Tune tokens TTL

### ISSUE THREAD

**Issue by chadparry** [hashicorp/terraform-provider-vault#290]
Hi there,

### Terraform Version

Terraform v0.11.11
+ provider.consul v2.2.0
+ provider.vault v1.4.1

### Affected Resource(s)
- `vault_auth_backend`

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "token" {
  type = "token"
  max_lease_ttl_seconds = "${24 * 60 * 60}"
}
```

### Debug Output
https://gist.github.com/chadparry/20b33323b4720dc15dffd22d9e01b816

### Expected Behavior
Terraform should adjust the `max_lease_ttl_seconds` property of the token backend. I'm trying to discover the Terraform equivalent of this command:
```sh
vault auth tune -max-lease-ttl=24h token/
```

### Actual Behavior
Terraform complains that the "token" mount is already in use.  I tried treating the token backend as a `vault_auth_backend` (as in the example config) and also a `vault_mount`. Either way it complains about the path being used. Next I tried to manually insert the existing token mount into terraform.tfstate so it would know that the mount existed. That still failed, because Terraform tried to delete and re-create the token backend, which is forbidden by Vault.

### Steps to Reproduce
1. `terraform apply`

**Comment by lyess-ow** [comment]
I had the same problem,
do you have a solution?

**Comment by chadparry** [comment]
I am using this workaround:

```terraform
resource "null_resource" "vault_auth_backend-token" {
  provisioner "local-exec" {
    command = "vault auth tune -max-lease-ttl=${365 * 24}h token/"  # 1 year
    environment = {
      VAULT_ADDR = "${var.vault-address}"
    }
  }
}
```

**Comment by jsoareswebsummit** [comment]
I've not tested but the solution would be to import the existing token authentication backend to terraform state and then edit it. It in seems to me that this is the default behaviour of TF. Since the auth backend was created outiside the scope of terraform when you define it in your TF file once you apply terraform will try first to create the backend but it alrady exists thus failing. So in this case you need first to import the backend like decribed here:
terraform import vault_auth_backend.example github
and then you can apply your terraform file.

**Comment by typez** [comment]
Hi All,

Came across this issue while googling. Just want to confirm that import approach works fine.
I've create a resource with default definition:
```
resource "vault_auth_backend" "token" {
  type            = "token"
}
```
Performed import: `terraform import vault_auth_backend.token token`
Then adjusted setting including ttl, e.g.:
```
resource "vault_auth_backend" "token" {
  type            = "token"
  disable_remount = false
  description     = "token based credentials"

  tune {
    default_lease_ttl = "86400s"
    max_lease_ttl     = "31104000s"
  }
}
```
Done `terraform apply` and that's it. I guess it makes sense to close this issue.

**Comment by fairclothjm** [comment]
The [token auth method is built-in and enabled in Vault by default](https://developer.hashicorp.com/vault/docs/auth/token). Thus the backend must be imported and then it can be tuned as described by @typez
