### ISSUE TITLE
1.6.0 do not support default_sts_ttl for vault_aws_secret_backend_role

### ISSUE THREAD

**Issue by sadpirit** [hashicorp/terraform-provider-vault#348]
### Terraform Version
Terraform v0.11.11
provider.vault v1.6.0
vault: 1.0.3
### Affected Resource(s)
vault_aws_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend_role" "test" {
    backend = "aws"
    name = "test"
    credential_type="federation_token"
    default_sts_ttl=60
    policy_document = <<EOT
....skip....
        EOT
}
```

### Debug Output
`Error: vault_aws_secret_backend_role.test: : invalid or unknown key: default_sts_ttl`

vault doc: https://www.vaultproject.io/api/secret/aws/index.html#default_sts_ttl

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 Support for setting the this parameter was added to the TFVP in [this PR](https://github.com/hashicorp/terraform-provider-vault/pull/444). Going to close this issue, but please feel free to open another one if you face any other problems! Thanks again :)
