### ISSUE TITLE
Need to fix vault_pki_secret_backend_role key_usage defaults

### ISSUE THREAD

**Issue by estein9825** [hashicorp/terraform-provider-vault#365]
Hi there,

When running the provider to create a vault_pki_secret_backend_role, if you keep key_usage is empty it will default it to `list: ["DigitalSignature", "KeyAgreement", "KeyEncipherment"]` because that is what the API does. However, the terraform module passes nothing, as a result, if you then run it again, it thinks it needs to be updated.

### Terraform Version
Terraform v0.11.13
Vault Provider 1.6
Vault 1.0.3
### Affected Resource(s)
- vault_pki_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_pki_secret_backend_role" "intermediate_cert_role" {
  backend            = "${vault_pki_secret_backend.pki_int.path}"
  name               = "${var.role_name}"
  allowed_domains    = ["${var.allowed_domains}"]
  allow_subdomains   = true
  allow_glob_domains = true
  allow_localhost    = true
  max_ttl            = "${coalesce(var.max_ttl, var.default_secret_ttl_sec)}"
}
```

### Expected Behavior
Reporting infrastructure has not changed

### Actual Behavior
```
~vault_pki_secret_backend_role.intermediate_cert_role
      key_usage.#:                                                       "0" => "3"
      key_usage.1:                                                       "" => "DigitalSignature"
      key_usage.2:                                                       "" => "KeyAgreement"
      key_usage.3:                                                       "" => "KeyEncipherment"
```
Request to apply changes
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by dippynark** [comment]
Seeing the same with `Vault Provider 1.7`

**Comment by aglover-zendesk** [comment]
I took a look at this, but haven't contributed enough to TF providers to know what the best action is.

[key_usage](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_pki_secret_backend_role.go#L182-L190) is defined in the schema as a `TypeList`. The Schema library doesn't allow `TypeList` schemas to have a `Default` property:
```
--- FAIL: TestProvider (0.01s)
    provider_test.go:47: err: 1 error occurred:
                * resource vault_pki_secret_backend_role: key_usage: Default is not valid for lists or sets
```
 So I don't think this is as easy as setting a default.

Alternatives I thought of:
* create a [DiffSuppressFunction](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/schema.go#L114). Tricky bit here is writing it so it doesn't suppress any _real_ deltas
* try to re-think the schema in a bigger way, capturing the `key_usage` as something other than a list

If any of the core maintainers have some guidance, would be happy to take a swing at this

**Comment by aglover-zendesk** [comment]
Took a quick stab at fixing this with a [solution based on a DiffSuppressFunction](https://github.com/terraform-providers/terraform-provider-vault/compare/master...aglover-zendesk:aglover-zendesk/suppress-key-usage-defaults?expand=1), but having a hard time testing locally. Leaving it here for reference for now

**Comment by fairclothjm** [comment]
Closed by https://github.com/hashicorp/terraform-provider-vault/pull/1443
