### ISSUE TITLE
1.7.0: unexpected EOF when setting up vault_jwt_auth_backend_role

### ISSUE THREAD

**Issue by fernandrone** [hashicorp/terraform-provider-vault#381]
### Terraform Version
```
$ terraform -v
Terraform v0.11.13
+ provider.vault v1.7.0
```

### Affected Resource(s)
- vault_jwt_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_jwt_auth_backend_role" "default" {
  backend   = "${vault_auth_backend.jwt.path}"
  role_name = "default"
  policies  = ["default"]

  bound_audiences = ["kubernetes"]
  user_claim      = "email"
  groups_claim    = "groups"
  ttl             = "3600"         # 1h
}
```

### Debug Output
https://gist.github.com/fbcbarbosa/577033c97db1a58ed7596773f1c8c3f4

### Expected Behavior
vault_jwt_auth_backend_role imported succesfully

### Actual Behavior
vault_jwt_auth_backend_role is not imported and terraform crashes

### Steps to Reproduce
Just `terraform apply` or `terraform import` a vault_jwt_auth_backend_role resource.

### Important Factoids
* **This seems to be regression; it works fine when I downgrade to 1.6.0**
* The error occurs when creating OR importing the resource
* The resource _is_ created successfully, but terraform does not update its state

If this is a regression, from the logs it seems the culprit is  vault/resource_jwt_auth_backend_role.go: 

```
2019-04-04T13:56:50.671-0300 [DEBUG] plugin.terraform-provider-vault_v1.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_jwt_auth_back
```

This received two updates between 1.6.0 and 1.7.0. Line 221 specifically changed here:

https://github.com/terraform-providers/terraform-provider-vault/commit/50be4e0b45ccdd2000ecaee51db34e28f2a617fd#diff-cfeb17a55ceb3551f70da26b8f6e1264R221

Not sure if this helps. I've tried setting role_type, but this didn't fix the problem.

**Comment by aromeyer** [comment]
Hi,
you are right, problem comes from the role_type - unknown in vault 1.0 - on my side it  
should be fixed by this PR: https://github.com/terraform-providers/terraform-provider-vault/pull/380

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! 🙏🏼 Looks like the problem can be resolved by updating the Vault version being used. For more context, please see the[ comment here](https://github.com/hashicorp/terraform-provider-vault/pull/380#issuecomment-487217987). Going to close this issue, but please feel free to open another one if you face any other problems! Thanks again :)
