### ISSUE TITLE
Delete Vault Provider Terraform code

### ISSUE THREAD

**Issue by AsierArandaS** [hashicorp/terraform-provider-vault#427]
Hi all

I'm testing Vault in my Azure test environment using terraform and it works great!!
I need to remove the vault code from my terraform code, but when I do a plan, terraform try to connect to Vault server but the code is commented because I don't want use vault in this environment. I only want to test the app to other clients, not for my test environment.

Acquiring state lock. This may take a few moments...
provider.vault.address
  URL of the root of the target Vault server.

  Enter a value:
---------------
Error: Error refreshing state: 1 error(s) occurred:

* provider.vault: no vault token found

I have the code commented but I don't know if is this is sufficient

/*
provider "vault" {
  address = "http://....129:8200"
  skip_tls_verify = true
  token = "s...Nz9J4U"

}
*/
How could I remove Vault from my terraform code and backend?

Thanks!!

**Comment by cvbarros** [comment]
You need to have different states per environment you're plan/applying.
If you want to conditionally use Vault, using the same code/configuration depending on the environment, I suggest you use modules to segment and enable/disable them based on the environment.

As for fixing your current situation, you can manually edit the state or use [Terraform State Command](https://www.terraform.io/docs/state/)

**Comment by saidogoid** [comment]
Same here.
Even if I remove him from code and from tfstate, he don't disappear.
Like everytime I do the rm command, he removes again and again. Real problem here?

`terraform state rm provider.vault
1 items removed.`
`Item removal successful.`

**Comment by fairclothjm** [comment]
Closing stale issue
