### ISSUE TITLE
Caused crash by in Vault Provider's interaction with Kubernetes Auth Backend

### ISSUE THREAD

**Issue by rberlind** [hashicorp/terraform-provider-vault#44]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
0.10.8 on SaaS TFE

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_generic_secret when used against /auth/<k8s-auth-backend>/config

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.10.1"
}

provider "vault" {}

data "vault_generic_secret" "gcp_credentials" {
  path = "secret/gcp/credentials"
}

provider "google" {
  credentials = "${data.vault_generic_secret.gcp_credentials.data[var.gcp_project]}"
  project     = "${var.gcp_project}"
  region      = "${var.gcp_region}"
}

resource "google_container_cluster" "k8sexample" {
  name               = "${var.cluster_name}"
  description        = "example k8s cluster"
  zone               = "${var.gcp_zone}"
  initial_node_count = "${var.initial_node_count}"
  enable_kubernetes_alpha = "true"

  master_auth {
    username = "${var.master_username}"
    password = "${var.master_password}"
  }

  node_config {
    machine_type = "${var.node_machine_type}"
    disk_size_gb = "${var.node_disk_size}"
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring"
    ]
  }
}

resource "vault_generic_secret" "config" {
  path = "auth/${var.gcp_project}/config"
  data_json = <<EOT
  {
    "token_reviewer_jwt": "reviewer_service_account_jwt",
    "kubernetes_host": "https://${google_container_cluster.k8sexample.endpoint}:443",
    "kubernetes_ca_cert": "${chomp(replace(base64decode(google_container_cluster.k8sexample.master_auth.0.cluster_ca_certificate), "\n", "\\n"))}"
  }
  EOT
}

resource "vault_generic_secret" "role" {
  path = "auth/${var.gcp_project}/role/demo"
  data_json = <<EOT
  {
    "bound_service_account_names": "cats-and-dogs",
    "bound_service_account_namespaces": "default",
    "policies": "admins",
    "ttl": "1h"
  }
  EOT
}
```

### Debug Output

https://gist.github.com/rberlind/6944e691c53e3a65276c76e9cbe66201

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

https://gist.github.com/rberlind/49c597dd8fb2a5e6c667e646e0c07391

### Expected Behavior
I was trying to queue a Destroy plan in TFE.  All my resources should have been destroyed.  

### Actual Behavior
What actually happened?

Terraform is having issues with the Vault Provider's vault_generic_secret resource which I used to write to the auth/roger-berlind-gke-dev/auth path in order to configure the Kubernetes Auth Backend (with path roger-berlind-gke-dev since I also have one configured at roger-berlind-gke-prod).  The issue is that the Kubernetes Auth Backend does not support the delete operation.  I reported this at https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/13.  As a way of trying to get around.  I actually produced the circumstances that lead to the crash by running `vault auth-disable roger-berlind-gke-dev` to see if disabling the auth backend would then allow the Terraform Vault provider to destroy the rest of my resources.  Unfortunately, it still tried to delete the /auth/roger-berlind-gke-dev/config path when it probably no longer existed.  Note that even after I re-enabled the Kubernetes Auth Backend with the same path, I still got the crash.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -destroy -out=destroy.tfplan`
2. `terraform apply destroy.tfplan`
(I was running in TFE and queued destroy plan, but this is what that does)

### Important Factoids

After using vault CLI to write data to auth/roger-berlind-gke-dev/config, I could then do destroy plans without crashing.  But the plan still fails because it cannot delete the vault_generic_secret.config resource.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/13

**Comment by benashz** [comment]
Closing this issue out due to its age. Please open a new issue if the issue manifests itself once more.
