### ISSUE TITLE
Incompatible change with Vault < 0.9 in provider version 1.5.0 

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/terraform-provider-vault#463]
Vault provider >= 1.5.0 don't conpatible with Vault version < 0.9 because resource vault_policy try to use unavailable endpoint.

### Terraform Version
 terraform -v
Terraform v0.11.7

### Affected Resource(s)
Vault.

### Terraform Configuration Files
As example:
resource "vault_policy" "app_write" {
    name        = "app-test-write"
    policy      = <<_EOT
        path "secret/service/${data.consul_agent_self.consul.datacenter}/test/*" {
            capabilities = ["create", "update", "delete", "list"]
        }
    _EOT
}

### Debug Output
* module.app_roles.vault_policy.app_write[12]: 1 error(s) occurred:
* vault_policy.app_write.12: error writing to Vault: Error making API request.
URL: PUT http://192.168.1.2:8200/v1/sys/policies/acl/app-test-write
Code: 404. Errors:
* 1 error occurred:
• unsupported path

### Expected Behavior
ACL updated

### Actual Behavior
Fail update ACL with error

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Tested with Vault version 0.7.4 and Vault provider 2.0.0

### References
https://www.vaultproject.io/api/system/policies.html

**Comment by fairclothjm** [comment]
Closing as these versions are no longer supported.
