### ISSUE TITLE
Add wrap_ttl support to vault_approle_auth_backend_role_secret_id

### ISSUE THREAD

**Issue by ocharles** [hashicorp/terraform-provider-vault#467]
To the best of my knowledge, it's not possible to create a wrapped secret id using AppRole authentication with `vault_approle_auth_backend_role_secret_id`. My goal is to be able to create `vault_approle_auth_backend_role_secret_id` resources and only learn the wrapped token, rather than the `secret_id` itself. Perhaps this could be done with a `wrap_ttl` attribute?

**Comment by vinay-gopalan** [comment]
Hi, thanks for opening this issue and apologies for the delayed response! Support for response-wrapping AppRole secret IDs was added to the TFVP as part of #518 and released in v2.6.0. Going to close this thread as the feature exists, but please feel free to open another issue if you face any other problems! Thanks 🙏🏼
