### ISSUE TITLE
database/config always gives a diff

### ISSUE THREAD

**Issue by anshprat** [hashicorp/terraform-provider-vault#51]
### Terraform Version
terraform -v
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.null v1.0.0
+ provider.random v1.1.0
+ provider.vault v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:

- vault_generic_secret

### Terraform Configuration Files

Hi,

With the below module, database/config path always gives a diff after first apply:

```hcl

resource "vault_generic_secret" "db_config" {
  count = "${local.is_mysql}"
  path  = "database/config/${var.db_identifier}"

  data_json = <<EOT
{
  "plugin_name":"mysql-database-plugin",
  "connection_details":
    {"connection_url":"${var.db_user}:${var.db_creds}@tcp(${var.rds_name}:3306)/"} ,
    "allowed_roles":["${var.db_role}_rw","${var.db_role}_ro"]
}
EOT
}

```

This happens as on the vault side, connection_url is actually an object inside connection_details. so changing the data_json to:

```

  data_json = <<EOT
{
  "plugin_name":"mysql-database-plugin",
  "connection_details":
    {"connection_url":"${var.db_user}:${var.db_creds}@tcp(${var.rds_name}:3306)/"} ,
    "allowed_roles":["${var.db_role}_rw","${var.db_role}_ro"]
}

```

fixes the diff after creating the config. However, with the above json, new configs cannot be created as vault throws error saying

* error creating database object: connection_url cannot be empty

Below is the vault audit log from above failed creation:

`
{"time":"redacted","type":"response","auth":{"client_token":"redacted","accessor":"redacted","display_name":"token-terraform","policies":["redacted"],"metadata":null,"entity_id":"redacted"},"request":{"id":"redacted","operation":"update","client_token":"redacted","client_token_accessor":"redacted","path":"database/config/mydb","data":{"allowed_roles":["redacted"],"connection_details":{"connection_url":"user:pass@tcp(mydb:3306)/"},"plugin_name":"mysql-database-plugin"},"policy_override":false,"remote_address":"redacted","wrap_ttl":0,"headers":{}},"response":{"data":{"error":"error creating database object: connection_url cannot be empty"}},"error":""}
`

### Expected Behavior
There should be no diff

### Actual Behavior
There is always a diff 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Create a database/config object and then again do a plan. It will show a diff.

**Comment by wstaples** [comment]
I having the same issue with:
Terraform v0.11.1
+ provider.template v1.0.0
+ provider.vault v1.0.0

Windows 7 64-bit

**Comment by wstaples** [comment]
Creating a key for the transit backend also has the same issue. vault_generic_secret will successfully create the key however there is always a diff since vault adds things afterward. Given the nature of these issues it would seem like a new set of providers would be needed. Is there any sort of development guide for providers?

**Comment by paddycarver** [comment]
I've got a `vault_database_secret_backend_connection` resource merged that reifies the backend connection as a resource. This should be released in the near future as part of 1.1.0. Would this fix your issue?

**Comment by sidewinder12s** [comment]
Ya I think this is actually an issue with the `vault_generic_secret` resource and not any database related anything. They also merged a change recently that just treats everything put into `vault_generic_secret` as sensitive so you can't even diff anymore if you wanted to.

**Comment by benashz** [comment]
Please use the `vault_database_secret_backend_connection` or `vault_database_secrets_mount` resource provisioning.
