### ISSUE TITLE
Fix docs for vault_pki_secret_backend_root_cert private_key

### ISSUE THREAD

**Issue by stephencroberts** [hashicorp/terraform-provider-vault#521]
The [docs](https://github.com/terraform-providers/terraform-provider-vault/blob/master/website/docs/r/pki_secret_backend_root_cert.html.md#attributes-reference) for the vault_pki_secret_backend_root_cert should remove the `private_key` field as it doesn't seem to actually be exported. @bhuisgen, is that correct?

**Comment by bhuisgen** [comment]
Right! PR opened : https://github.com/terraform-providers/terraform-provider-vault/pull/524

**Comment by tgermain** [comment]
#524 has been merged and release. 

Should this issue be closed ?
