### ISSUE TITLE
vault_gcp_auth_backend_role:  "Expecdted 4 parts in path 'auth/gcp/foo/role/bar'"

### ISSUE THREAD

**Issue by zx8** [hashicorp/terraform-provider-vault#532]
Caused by https://github.com/terraform-providers/terraform-provider-vault/pull/517

```
Terraform v0.12.8
+ provider.vault v2.3.0
```

The linked PR introduced a bug with multiple `gcp` backends:

```
Error: invalid path "auth/gcp/foo/role/bar" for GCP auth backend role: Expecdted 4 parts in path 'auth/gcp/foo/role/bar'
```

The PR incorrectly assumes there will be 4 `/`-separated components to the path. This is correct if you use a single auth backend (e.g. `auth/gcp`), but breaks when using multiple GCP auth backends (e.g. `auth/gcp/project1` and `auth/gcp/project2`).

[Nit: Also `Expecdted` is spelled wrong]

**Comment by zx8** [comment]
Ping @julianvmodesto

**Comment by KeisukeYamashita** [comment]
@julianvmodesto I have several GCP project and having the same problem.

Is there a reason that auth backed path has to be in 4 parts?
