### ISSUE TITLE
Support enabling auth plugins with vault_auth_backend

### ISSUE THREAD

**Issue by tomwilkie** [hashicorp/terraform-provider-vault#54]
The plugin_name field needs to be supplied.

### Terraform Version

```
$ terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
- vault_auth_backend

**Comment by tomwilkie** [comment]
It can be worked around with eg:

```
resource "vault_generic_secret" "google_plugin_enable" {
  depends_on   = ["vault_generic_secret.google_plugin_sha"]
  path         = "sys/auth/google"
  disable_read = true

  data_json = <<EOF
{
  "type": "plugin",
  "plugin_name": "google-auth-vault-plugin"
}
EOF
}
```

But its a bit of a hack...

**Comment by michaeljs1990** [comment]
It seems like #214 would the final solution to this since plugins do have their own endpoints. This is a fairly annoying thing right now and everyone writing plugins ideally doesn't have to write a custom TF resource to match it.

**Comment by michaeljs1990** [comment]
This can actually be closed out now. https://github.com/hashicorp/vault/pull/5536 fixes this and going off the above example lets you write the following tf. Thanks for the work on this @tyrannosaurus-becks.

```
resource "vault_auth_backend" "google_plugin_enable" {
  type = "google-auth-vault-plugin"
}
```

**Comment by fairclothjm** [comment]
closed by https://github.com/hashicorp/vault/pull/5536
