### ISSUE TITLE
[Feature Request] Support for database static roles

### ISSUE THREAD

**Issue by xuwang** [hashicorp/terraform-provider-vault#563]
Currently database role is supported by vault_database_secret_backend_role.
It would be nice to have a resource that map to database secret backend static role, i.e. https://www.vaultproject.io/api/secret/databases/index.html#create-static-role

I tried to use vault_generic_endpoint to provision the static role but failed because the API requires POST vs GET.

Thanks!

**Comment by devops-rob** [comment]
I think this may have already been implemented but the documentation hasn't yet been updated. https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_database_secret_backend_role.go.  Does this meet your requirements @xuwang ?

**Comment by Wolfsrudel** [comment]
> I think this may have already been implemented but the documentation hasn't yet been updated. https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_database_secret_backend_role.go. Does this meet your requirements @xuwang ?

I couldn't find a hint to the path 'static-roles' and 'static-creds' in the code. In my linked issue the case is explained in detail. :)

**Comment by Wolfsrudel** [comment]
@devops-rob this is the right link to the solution: https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_database_secret_backend_static_role.go

:)
