### ISSUE TITLE
vault_generic_secret fails to read long secrets (unexpected EOF)

### ISSUE THREAD

**Issue by demeesterdev** [hashicorp/terraform-provider-vault#58]
### Terraform Version
terraform on windows v0.11.2
```
PS C:\temp\terratest> terraform -v
Terraform v0.11.2
+ provider.vault v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data vault_generic_secret

### Terraform Configuration Files
```hcl
data "vault_generic_secret" "ssh_key" {
  path = "secret/path/ssh-key"
}

output "id_rsa_pub" {
   value = "${data.vault_generic_secret.ssh_key.data["id_rsa_pub"]}"
}

output "id_rsa" {
   value = "${data.vault_generic_secret.ssh_key.data["id_rsa"]}"
}
```
### Vault Content
generated a public private keypair
```bash
$ ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
```

upload it to vault at `secret/path/ssh-key`
```json
{
  "id_rsa": "<<-redacted private key->>",
  "id_rsa_pub": "<<-redacted public key->>"
}
```
### Debug Output
TF_LOG='TRACE'
https://gist.github.com/tdemeester/caed0744f8d65992d63df063f6aa9f17

### Panic Output
terraform does not create a panic. 

### Expected Behavior
both keys should be available for the generic secret.
e.a
```hcl
output "id_rsa_pub" {
   value = "${data.vault_generic_secret.ssh_key.data["id_rsa_pub"]}"
}

output "id_rsa" {
   value = "${data.vault_generic_secret.ssh_key.data["id_rsa"]}"
}
```

### Actual Behavior
returns an error id_rsa_pub is not available
```
data.vault_generic_secret.ssh_key: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* output.id_rsa_pub: key "id_rsa_pub" does not exist in map data.vault_generic_secret.ssh_key.data in:

${data.vault_generic_secret.ssh_key.data["id_rsa_pub"]}
```

log shows
```
2018-01-19T13:43:27.210+0100 [WARN ] plugin: error closing client during Kill: err="unexpected EOF"
2018-01-19T13:43:27.218+0100 [DEBUG] plugin: plugin process exited: path=C:\temp\terratest\.terraform\plugins\windows_amd64\terraform-provider-vault_v1.0.0_x4.exe
```
If i do not access id_rsa_pub the provider does show the above warning but does not produce a panic or error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. fill vault as speciefied at vault content
2. terraform apply with terraform code as specified at Terraform Configuration Files
3. `terraform apply`

### Important Factoids
reproduced the error on a clean vault install.
all code above and gist is directly from fresh environment.

the error is resolved when splitting public and private key.

the key `data.vault_generic_secret.ssh_key.data_json` does contain the full vault entry.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- looks like its related #1

**Comment by vinay-gopalan** [comment]
Closing stale issue. `vault_generic_secret` has been deprecated for dedicated KV resources.
