### ISSUE TITLE
vault_database_secret_backend_connection don't accept plugin_name key

### ISSUE THREAD

**Issue by JnMik** [hashicorp/terraform-provider-vault#607]
### Terraform Version
vault v0.12.12
provider.vault v2.6.0

### Affected Resource(s)
vault_database_secret_backend_connection

### Terraform Configuration Files
```hcl
resource "vault_database_secret_backend_connection" "mongodb-atlas" {
  backend       = "${vault_mount.mongodb-atlas.path}"
  name          = "mongodb-atlas"
  allowed_roles = [
      ...  
  ]

  plugin_name = "mongodb-atlas-plugin"

  data = {
    public_key = "xxx"
    private_key = "xxx"
    project_id = "xxx"
  }
}

```

### Expected Behavior
Resource should accept plugin_name property to pass custom plugins

### Actual Behavior
An argument named "plugin_name" is not expected here.

I also tried with plugin_name in the data field but had the error Error: at least one database plugin must be configured

**Comment by whume** [comment]
Is there an update on this now that mongodb atlas is officially supported it would be good if we could use terraform for this.

**Comment by iiro** [comment]
Any updates on this...? Definitely needed for managing the setup with Terraform...

**Comment by angeloskaltsikis** [comment]
@iiro According to the [docs](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection) i believe that while there is no way to currently specify which plugin you want, you can use the specific blocks (for example `mysql` or `aurora_rds`) to specify which plugin you want to use.
Makes sense to you?

**Comment by benashz** [comment]
Closed by #1320

**Comment by benashz** [comment]
Hi @pedroduarteid , this is fixed in https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.3.0 . Please let us know if you continue to encounter this issue.

Thanks,

Ben

**Comment by pedroduarteid** [comment]
Hi @benashz 
I will evaluate it today and as soon as I have the result I will update you here.

Thanks,
Pedro

**Comment by pedroduarteid** [comment]
Hi @benashz 

I evaluated and the command "terraform apply" shows the error below.

![image](https://user-images.githubusercontent.com/99905653/154706991-6a08602d-4deb-488f-9c97-ebdcdf711d4b.png)

Using the "vault write..." command I configured the database engine to mongodbatlas normally. However, I believe there is some configuration missing to be able to run through terraform. But I could not find any parameters for that.

![image](https://user-images.githubusercontent.com/99905653/154709962-29865dcc-7b75-42bb-a65f-3d55b1de119a.png)

![image](https://user-images.githubusercontent.com/99905653/154710234-40ba0276-f8c0-4d68-9a2a-e33c38323a50.png)

**Comment by benashz** [comment]
HI @pedroduarteid , 

I think you might be missing database specific configuration. See https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/database_secret_backend_connection#mongodb-atlas-configuration-options for more details.

**Comment by pedroduarteid** [comment]
I believed that not...
I have trying before used these options but have errors.

By the best pratices not is correct to be use credentials in the configurations files...

I have tried several ways to use these parameters and it is not accepted by "terraform plan...apply"...etc...

![image](https://user-images.githubusercontent.com/99905653/154725907-ebf22571-58a0-4ffe-ba68-8b73d6917a0d.png)

![image](https://user-images.githubusercontent.com/99905653/154726738-dd1c19f4-bee2-462c-9513-3ba98fc94d9c.png)

![image](https://user-images.githubusercontent.com/99905653/154726956-8cd622a8-b9dd-4d2c-9ad0-36a959b2345f.png)

![image](https://user-images.githubusercontent.com/99905653/154728080-a222f2a6-6f79-4041-9603-12db7c2406f1.png)

**Comment by benashz** [comment]
I think you only need to move `public_key` and `private_key` into the resource's `mongodbatlas` block:

Example:
```hcl
resource "vault_database_secret_backend_connection" "test" {
  backend = vault_mount.db.path
  name = "...."

  mongodbatlas {
    public_key  = "your public key"
    private_key = "your private key"
    project_id  = "your project ID"
  }
}
```

**Comment by benashz** [comment]
You need to pass a string for all those fields.  What you have there are lists, which is not what the provider expects.

**Comment by pedroduarteid** [comment]
I tried several ways and all were rejected.

I tried...

public_key = var.puk
private_key = var.pk
project_id  = var.proj

public_key = [var.puk]
private_key = [var.pk]
project_id  = [var.proj]

public_key = ["var.puk"]
private_key = ["var.pk"]
project_id  = ["var.proj"]

In the file variable.tf these values are string type

But the error not is these values but it message **"An argument named "XXXX" is not expected here."**. I thinking that provider is not prepare to make connections between Vault and MongoDB Atlas.

**Comment by pedroduarteid** [comment]
Yes, @benashz 
It is now possible to perform the configuration in Vault through Terraform. 

![image](https://user-images.githubusercontent.com/99905653/154744839-0ad4e72b-f220-4a96-8612-3bc93f926b0a.png)

The values are passing in time of execution with "terraform apply" to nothing save inside files config.

![image](https://user-images.githubusercontent.com/99905653/154745603-84467a1a-214d-4ede-9f46-d53d8e22a7ee.png)

![image](https://user-images.githubusercontent.com/99905653/154745750-ccb8465c-628a-43f9-91e7-72395ad54b85.png)

Thanks!
**Pedro Duarte**
