### ISSUE TITLE
Docs for vault_database_secret_backend_connection lack connection_url examples

### ISSUE THREAD

**Issue by neilhwatson** [hashicorp/terraform-provider-vault#644]
The current docs (https://www.terraform.io/docs/providers/vault/r/database_secret_backend_connection.html) lack details on the format of connection_url. Only a postgresql example is shown. I'm currently struggling with connecting to an Azure MySQL database and an example would be helpful.

**Comment by fairclothjm** [comment]
@neilhwatson Hello, we recommend referring to your database provider's documentation for appropriate connection url formatting. Thanks!
