### ISSUE TITLE
Feature request - have vault_mount resource support audit_non_hmac_response_keys

### ISSUE THREAD

**Issue by kevinjlu** [hashicorp/terraform-provider-vault#667]
As defined in the vault API documentation, I would like to be able to specify the following fields on a `vault_mount` resource.
- `audit_non_hmac_request_keys` `(array: [])` - Specifies the comma-separated list of keys that will not be HMAC'd by audit devices in the request data object.
- `audit_non_hmac_response_keys` `(array: [])` - Specifies the comma-separated list of keys that will not be HMAC'd by audit devices in the response data object.

https://www.vaultproject.io/api-docs/system/mounts/#tune-mount-configuration

**Comment by thekev** [comment]
I am also blocked by lack of full support of the API on the `vault_mount` resource. I am unable to work around it with `vault_generic_endpoint`, and the generic `options` parameter is not applicable. For comparison, `vault_auth_backend` implements all parameters. `vault_mount` should do the same.

Any workarounds?

**Comment by eliasscosta** [comment]
I'm looking for this feature as well.

**Comment by jiesiren** [comment]
Same here, would be great to get an update on this!

**Comment by thekev** [comment]
It's been over 1.5 years since this was reported. I started to prepare a patch to add support, but other priorities have prevailed. Any other progress?

**Comment by benashz** [comment]
Closed by #1194
