### ISSUE TITLE
vault_identity_entity_alias fails update in place

### ISSUE THREAD

**Issue by JeroenBrinkman** [hashicorp/terraform-provider-vault#669]
### Terraform Version
`Terraform v0.12.20`
other relevant versions:
vault: `1.3.2`
vault_provider: `2.8.0`

### Affected Resource(s)
- vault_identity_entity_alias

### Terraform Configuration Files
See `Steps to Reproduce`

### Debug Output
None, the errors seem to swallowed somewhere.

### Panic Output
None, the errors seem to swallowed somewhere.

### Expected Behavior
The same error that is thrown when this conflict happens in a create operation.

### Actual Behavior
The `terraform apply` fails silently and gives the impression everything succeeded.

### Steps to Reproduce
Requirements: 
- A Certificate Authority, which i will mention as `CA.pem`.
- A Client certificate signed with `CA.pem` with common name: `cert_common_name`.
- Some testing policy: `test_policy.hcl`.

Steps:
1. Setup the certificate authentication to Vault and the policy. We also create an entity for a test app, but we make a mistake or typo in the alias name (or we later decide to change it):
```hcl
resource "vault_auth_backend" "test_cert_auth" {
    path = "cert/test_cert_auth"
    type = "cert"
}

resource "vault_cert_auth_backend_role" "test_cert_auth_backend_role" {
    name          = "TestCA"
    certificate   = file("CA.pem")
    backend       = vault_auth_backend.test_cert_auth.path
    policies      = ["default"]
}

resource "vault_policy" "test_policy" {
  name = "test_policy"
  policy = file("test_policy.hcl")
}

resource "vault_identity_entity" "application_identity" {
    name      = "application_name"
    policies  = ["test_policy"]
}

resource "vault_identity_entity_alias" "alias_for_some_server_with_client_cert" {
    name            = "cert_common_name with typo"
    mount_accessor  = vault_auth_backend.test_cert_auth.accessor
    canonical_id    = "${vault_identity_entity.application_identity.id}"
}
```
2. `terraform apply` This should succeed without issues.
3. Try to login the with the client cert:
This should succeed and return a token without only the default policy.
Under water Vault did the following: 
- it created an alias from which the name equals `cert_common_name`.
- it linked this to an auto generated entity with a name like: `Entity<SomeHexCode>`.
4. Fix the mistake/typo/ complete the renaming operation by adjusting the alias config:
```hcl
resource "vault_identity_entity_alias" "alias_for_some_server_with_client_cert" {
    name            = "cert_common_name"
    mount_accessor  = vault_auth_backend.test_cert_auth.accessor
    canonical_id    = "${vault_identity_entity.application_identity.id}"
}
```
5. `terraform apply`
The plan will look something like this:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vault_identity_entity_alias.alias_for_some_server_with_client_cert will be updated in-place
  ~ resource "vault_identity_entity_alias" "alias_for_some_server_with_client_cert" {
        canonical_id   = "9edbbe9a-ff2d-b34c-527d-c9cb52a7a171"
        id             = "e47a2013-aa84-3242-6c80-3c6803b8ee51"
        mount_accessor = "auth_cert_ca08050f"
      ~ name           = "cert_common_name with typo" -> "cert_common_name"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
The terraform apply will tell you that everything succeeded and has been applied successfully.
```
vault_identity_entity_alias.alias_for_some_server_with_client_cert: Modifying... [id=e47a2013-aa84-3242-6c80-3c6803b8ee51]
vault_identity_entity_alias.alias_for_some_server_with_client_cert: Modifications complete after 0s [id=e47a2013-aa84-3242-6c80-3c6803b8ee51]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Trying to login however will still only give the `default` policy where we would expect both `default` and `test_policy`(1). OR all your futures applies will fail since we just broke our tfstate(2).
What actually happened is one of the following:
I have not debugged deep enough to say which of the following causes which scenario but it might be related to one of the following: `vault version 1.3.2 vs 1.3.0 in prod`, `vault provider 2.8.0 vs 2.7.0 in prod`, `creating just one alias vs multiple in one resource block (using count) in prod`. The above scenario seems to always reproduce case 2, but i have observed case 1 multiple times in production.

1. The update in place failed silently because the new name of the alias was already taken (for the same accessor_id and name, but different canonical_id). Trying to run `terraform plan` again will propose the exact same changes again. Running apply again will succeed but do absolutely 0 changes. You end with 2 entities with one alias each.

2. The update in place merged both entities, but did not remove the previously created alias nor did it update the id in tfstate to be the auto generated alias. You will end up with one entity with 2 aliases, one with typo one without. And a broken tfstate since it points to the alias with typo. Every future plan will resuggest the same changes but applying fails with 
```
vault_identity_entity_alias.alias_for_some_server_with_client_cert: Modifying... [id=c70acf7f-dc49-2fb6-619f-ff2f961ccd14]

Error: error updating IdentityEntityAlias "c70acf7f-dc49-2fb6-619f-ff2f961ccd14": Error making API request.

URL: PUT https://127.0.0.1:8200/v1/identity/entity-alias/id/c70acf7f-dc49-2fb6-619f-ff2f961ccd14
Code: 500. Errors:

* 1 error occurred:
	* duplicate identity name
```

Currently the only workaround i can see is logging in to the vault-cli and manually deleting the  identities and alias. (only removing the alias is required, removing the identity is just cleaning up leftovers)

_Unrelated question: Is it possible to disable the auto generation of entities and entity_aliases in this way on a vault or auth engine level?_

### Important Factoids
If you remove the initial alias creation from step 1 it actually fails correctly with the following error:
```
vault_identity_entity_alias.alias_for_some_server_with_client_cert2: Creating...

Error: IdentityEntityAlias "cert_common_name" already exists. Unable to determine alias id.
```

The creation of multiple aliases in one block we do in production looks like this:
```
resource "vault_identity_entity_alias" "aliases" {
    count           = length(var.server_names)
    name            = "cert_common_name_prefix-${var.server_names[count.index]}"
    mount_accessor  = "${var.vault_accessor_id}"
    canonical_id    = "${vault_identity_entity.application_identity.id}"
}
```
### References
I think this issue was the underlying cause of #523

**Comment by arnisoph** [comment]
I am also experiencing this issue. Looks like there's on fix on the way. :/

**Comment by hsimon-hashicorp** [comment]
Thank you, folks, and sorry for the delay - I'm working with our engineering teams on this, but it might take a bit more time. I'll make a note to circle back for you all, and thank you for your patience.

**Comment by arnisoph** [comment]
any updates?

**Comment by hsimon-hashicorp** [comment]
Hi @arnisoph! Thanks for checking in. I'm still checking with our engineers on this - version 3.0.0 of the TFVP was released just a couple of weeks ago, so there will be some more bandwidth to look at this now. Thanks for your patience, and I'm reaching out to our engineering teams now.

**Comment by benashz** [comment]
Hi @arnisoph , we are taking a closer look at this issue. We should have some news for you soon.

Thanks,

Ben
