### ISSUE TITLE
Incorrect URL in the v2.0.0 release notes

### ISSUE THREAD

**Issue by nyurik** [hashicorp/terraform-provider-vault#671]
Please fix [v2.0.0](https://github.com/terraform-providers/terraform-provider-vault/releases/tag/v2.0.0) release comment  with the correct URL - `https://www.terraform.io/docs/providers/vault/guides/version_2_upgrade.html` . The [current one](https://www.terraform.io/docs/providers/vault/version_2_upgrade.html) is a 404 (missing `guides/` part)

**Comment by fairclothjm** [comment]
Fixed!
