### ISSUE TITLE
No sts_region in vault_aws_auth_backend_client

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/terraform-provider-vault#689]
Hi, 

If define sts_endpoint, sts_region is also required, but we can't see this parameter in https://www.terraform.io/docs/providers/vault/r/aws_auth_backend_client.html? Anything I'm missing?

Reference:
https://www.vaultproject.io/api/auth/aws/index.html#inlinecode-sts_endpoint-1

**Comment by pogosoftware** [comment]
Do we know when this issue will be merge and release?

**Comment by bradpoulton** [comment]
I am also in need of this feature. Thanks!

**Comment by mjeczalik** [comment]
Any comment on that? I also need this feature.
