### ISSUE TITLE
Add support for for the bound_claims_type attribute in the JWT auth (Vault 1.4.0)

### ISSUE THREAD

**Issue by randomswdev** [hashicorp/terraform-provider-vault#700]
### Terraform Version
Terraform v0.12.19

### Affected Resource(s)
vault_jwt_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_jwt_auth_backend_role" "role" {
  backend = "${vault_auth_backend.jwt.path}"
    role_name = "testrole"
    role_type = "jwt"
  bound_subject = "sl29dlldsfj3uECzsU3Sbmh0F29Fios1@update"
  token_bound_cidrs = ["10.150.0.0/20", "10.152.0.0/20"]
  bound_audiences = ["https://myco.update",]
  user_claim = "https://vault/updateuser"
  groups_claim = "https://vault/updategroups"
  token_policies = ["default", "dev"]
  token_ttl = 7200
  token_num_uses = 24
  token_max_ttl = 10800
  bound_claims_type = "glob"
  bound_claims = {
    department = "engineering-*-admin"
    sector = "7g"
  }
}
```

### Expected Behavior
The above resource definition includes a new field bound_claim_type that allows to specify if the bound claims are matched as plain string or are metched as globs. Vault is supporting this new attirbute starting with version 1.4.0 (see https://github.com/hashicorp/vault-plugin-auth-jwt/issues/82 - the code is included in the release https://github.com/hashicorp/vault-plugin-auth-jwt/releases/tag/v0.6.0-beta1 of the jwt auth plugin that is currently included in https://github.com/hashicorp/vault/releases/tag/v1.4.0-beta1)

**Comment by kschu91** [comment]
Any chance this gets merged soon and packed in a new release?

**Comment by bgagnon** [comment]
Bump. Can we get this moving?
