### ISSUE TITLE
Feature request : Allow specifying role by id in vault_azure_secret_backend_role

### ISSUE THREAD

**Issue by dguihal** [hashicorp/terraform-provider-vault#715]
# Terraform Version

Terraform v0.12.21

### Affected Resource(s)

vault_azure_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_azure_secret_backend_role" "vault_role" {
  role    = "vault_role"

  azure_roles {
    role_id = "/subscriptions/<uuid-1>/providers/Microsoft.Authorization/roleDefinitions/whatever"
    scope   = "/subscriptions/<uuid-1>/resourceGroups/whatever"
  }

  azure_roles {
    role_id = "/subscriptions/<uuid-2>/providers/Microsoft.Authorization/roleDefinitions/whatever"
    scope   = "/subscriptions/<uuid-2>/resourceGroups/whatever"
  }
```

In case we need to specify roles for multiple subscription, looking by name fails as role search is scoped to the current subscription.

To bypass this we need to be able to specify role by id, which is impossible by now as it is specified as "computed"

### Expected Behavior

Succeed

### Actual Behavior

Fails

### Steps to Reproduce

1. `terraform apply`

**Comment by kalafut** [comment]
Hi. I agree this would be useful and we'll look into it.
