### ISSUE TITLE
Deletion of generic secret resource does not delete previous versions

### ISSUE THREAD

**Issue by g-psantos** [hashicorp/terraform-provider-vault#760]
### Terraform Version
`Terraform v0.12.24`

### Affected Resource(s)
- vault_generic_secret

### Terraform Configuration Files
```hcl
resource "vault_mount" "kv" {
    type = "kv-v2"
    path = "kv"
}

resource "vault_generic_secret" "generic_secret" {
    count = length(var.generic_secrets)
    path = join("/", [vault_mount.kv.path, var.generic_secrets[count.index].name])
    data_json = jsonencode(var.generic_secrets[count.index].data)
}
```

### Debug Output
Not Applicable: This is a behavioral issue, there are no errors associated with it.

### Panic Output
Not Applicable

### Expected Behavior
I expected that, upon emptying the `var.generic_secrets` variable, Terraform would delete all `vault_generic_secret.generic_secret` resources, including their respective version histories.

### Actual Behavior
Terraform does delete the _latest version_ of each secret but not their previous versions. This likely results in confusion for users of the KV mount, as the latest version of a secret gets deleted but superseded versions are left behind -- "Should I use the old version now instead?" as opposed to "OK, this secret is no longer available".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Terraform configuration file with a `vault_mount` resource of type `kv-v2` and a `vault_generic_secret` resource within it (use some random `data` for the secret).
2. Run `terraform apply` to deploy the resources to Vault.
3. Change the `data` property of `vault_generic_secret` to something different from what was used in Step 1.
4. Run `terraform apply` to create a second version of the secret in Vault.
5. Delete the `vault_generic_secret` resource from the Terraform configuration file.
6. Run `terraform apply`. This will delete the latest version of the secret but not prior versions.

### Important Factoids
No factoids. As a suggestion to fix this behavior, Terraform could either:

* Create a new version of the secret with no data in it, then delete the resource from Terraform state. This would respect Vault's version history in that the latest secret is blank and previous versions of the secret remain available, but would obviously mean that the secret is no longer managed in Terraform.

* Identify all versions of the secret and delete them. This would be consistent with the way Terraform generally works, but potentially cause data loss issues for users who expected old versions to remain available.

Perhaps a `delete_version_history` attribute could be added to toggle between the two behaviors above? If set to `false` (default), a new version of the secret is created with no content and the resource is deleted from Terraform's state. If set to `true`, all versions of the secret get deleted and the resource is deleted from Terraform's state.

### References
N/A

**Comment by fernando-villalba** [comment]
I concur with this, also, if you have only one version of the secret it leaves it blank instead of deleting it entirely. I don't use Terraform to create secrets, only to create skeleton secrets to provision a folder structure for others to use based on policies, so whenever I destroy, I really would love to be able to destroy entirely the secret.

Right now I have to go one by one and delete them manually after a destroy, which is tedious.

**Comment by briananstett** [comment]
The PR seems to be stuck in limbo. Any updates from the maintainers about when it might get merged in?

**Comment by rcreasey** [comment]
+1 if this ever gets picked up

**Comment by wagnst** [comment]
+1 its still present in the latest TF (`0.14.10`) and vault versions (`1.7`)

```
vault = {
  source  = "hashicorp/vault"
  version = "~> 2.19"
}
```

**Comment by briananstett** [comment]
You would think Vault being a Hashicorp product, the Terraform provider would have more maintainers. #802 has been stuck waiting for approval/merge for months...

**Comment by bobthebuilderberlin** [comment]
A workaround using a local-exec provisioner:
```
resource "vault_generic_secret" "my_secret" {
  path = "<secret-engine-mount-path>/<path-to-secret>"

  data_json = <<EOT
{
  "FOO": "BAR"
}
EOT
  # Delete on_destroy
  //count = 0
  provisioner "local-exec" {
        when        = "destroy"
        command     = "curl --header \"X-Vault-Token: $${VAULT_TOKEN}\" --request DELETE \"$${VAULT_ADDR}/v1/kv/metadata/<path-to-secret>""
  }
}
```

Comment in the `//count = 0` to delete the secret with all versions.

**Comment by g-psantos** [comment]
Looks like v3.1.0 includes #1254, so I'm closing this. Thanks for the implementation, @vinay-gopalan !
