### ISSUE TITLE
Feature request: aws_secret_backend_role: missing user_path parameter

### ISSUE THREAD

**Issue by technicaljones** [hashicorp/terraform-provider-vault#769]
### Affected Resource(s)
- vault_aws_secret_backend_role

### Expected Behavior
In the docs https://www.vaultproject.io/api-docs/secret/aws#create-update-role there is a 'user_path' parameter for configuring path for the username when using a credential_type of iam_user

### Actual Behavior
The property doesn't exist in the terraform provider
https://www.terraform.io/docs/providers/vault/r/aws_secret_backend_role.html#argument-reference

### References
Github issue requesting this: https://github.com/hashicorp/vault/issues/2318
Github PR fixing this: https://github.com/hashicorp/vault/pull/6380

**Comment by benashz** [comment]
Fixed in #781
