### ISSUE TITLE
token_reviewer_jwt errors with illegal base64 data at input byte 342

### ISSUE THREAD

**Issue by popopanda** [hashicorp/terraform-provider-vault#793]
### Terraform Version
Terraform version 0.12.26

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_kubernetes_auth_backend_config

### Terraform Configuration Files
```
resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
}

resource "vault_kubernetes_auth_backend_config" "kubernetes" {
  backend            = vault_auth_backend.kubernetes.path
  kubernetes_host    = var.kubernetes_host
  kubernetes_ca_cert = var.kubernetes_ca_cert
  token_reviewer_jwt = var.token_reviewer_jwt
}
```

### Panic Output

https://gist.github.com/popopanda/cf746807e77d0d935ff442d226a9602f

### Expected Behavior
Should have applied the JWT Token correctly.

### Actual Behavior
Terraform errors stating the value I am inputting into `token_reviewer_jwt`  is `illegal base64 data at input byte 342`. I narrowed down to the `token_reviewer_jwt` because if I exclude that variable, terraform does not fail on apply stage.

### Steps to Reproduce
Followed the documentation at https://www.vaultproject.io/docs/platform/k8s/helm/examples/kubernetes-auth 1 to obtain the token_reviewer_jwt and kubernetes_ca_cert.
1. Obtain `token_reviewer_jwt` by running `cat /var/run/secrets/kubernetes.io/serviceaccount/token` from one of our vault pods
2. copy and paste the outputted value into `token_reviewer_jwt` for the `vault_kubernetes_auth_backend_config` resource

### Important Factoids
Running on EKS 1.15
vault 1.4.2

Additional info - https://discuss.hashicorp.com/t/vault-provider-illegal-token-reviewer-jwt-data/9817

**Comment by popopanda** [comment]
Also to add, running the vault command manually without Terraform vault provider to setup kubernetes auth works without problems.

```
vault write auth/kubernetes/config \
        token_reviewer_jwt="<Token>" \
        kubernetes_host="https://kubernetes.default:443" \
        kubernetes_ca_cert=<CA>
```

**Comment by jgoldschrafe** [comment]
I ran into this problem over the weekend and duplicated it using the Vault CLI interactively, and I have a weird (and hopefully helpful!) request for you.

When you run `cat` and then copy and paste, there's no trailing newline. As a result. the `/` path indicator that leads off the shell's prompt is sort of stuck directly onto the end of the token text. Can you double-check that what you're copying and pasting doesn't include that?

**Comment by popopanda** [comment]
Sorry for the delay. You're totally right. It had a `/` at the end of the token when doing `cat`. Using vim shows the actual token without that trailing slash.

**Comment by tvoran** [comment]
Hi @popopanda, sounds like you got it sorted out, so I'm going to close this for now.

**Comment by clintmod** [comment]
I had to upgrade from 3.5 to 3.6 in order to see this fixed.
