### ISSUE TITLE
Support redshift-database-plugin for Database Secrets Engine

### ISSUE THREAD

**Issue by beyondbill** [hashicorp/terraform-provider-vault#808]
I would like to set up secret engine for a Redshift database but do not see [Redshift plugin](https://www.vaultproject.io/docs/secrets/databases/redshift) listed in code as other types of databases are.
https://github.com/terraform-providers/terraform-provider-vault/blob/6220fe355e0638c71045f2e844b6c681fef0fc25/vault/resource_database_secret_backend_connection.go#L290-L317

### Affected Resource(s)
- vault_database_secret_backend_connection

**Comment by benashz** [comment]
Fixed in #1279
