### ISSUE TITLE
Unable to set metadata for entity_alias

### ISSUE THREAD

**Issue by johannesesbjornsson** [hashicorp/terraform-provider-vault#827]
For the `vault_identity_entity`  resource it's possible to set metadata, however for the `vault_identity_entity_alias` resource it's not, even though it's possible to do it the the vault api.

This then gets in the way of using this type of policy templating `identity.entity.aliases.<mount accessor>.metadata.<metadata key>`

Is setting alias metadata planned to be supported in the near future?

**Comment by ludydoo** [comment]
Looking for this as well
I'd like to provision with terraform the vault_identity_entity_alias that would otherwise be created by the kubernetes auth.
Currently it's not possible to specify the metadata in the alias using terraform

**Comment by vinay-gopalan** [comment]
@johannesesbjornsson thank you for raising an issue! Currently, the entity alias `metadata` field is only set by Vault and is not available for reading and updating via the API. If you would like to add any metadata for things like policy templating, then you can use the `custom_metadata` field to do it. We recently merged an improvement to the feature that enables users to configure `custom_metadata` through the TF Vault Provider and it is milestoned for v3.1.0 https://github.com/hashicorp/terraform-provider-vault/pull/1235

Please feel free to open another issue if the problem still persists!
