### ISSUE TITLE
Feature Request: resource_jwt_auth_backend - add provider_config

### ISSUE THREAD

**Issue by austingebauer** [hashicorp/terraform-provider-vault#828]
Vault 1.5 added provider-specific handling in the JWT/OIDC auth method. This requests support for the feature by adding the [provider_config](https://www.vaultproject.io/api-docs/auth/jwt#provider_config) field to the `resource_jwt_auth_backend` resource.

### Affected Resource(s)

- resource_jwt_auth_backend

### References

- https://www.vaultproject.io/api-docs/auth/jwt#provider_config
- https://www.vaultproject.io/docs/auth/jwt_oidc_providers#azure-specific-handling-configuration

**Comment by Gaardsholt** [comment]
Is this something that are being worked on?
If not, I will give it a crack :)

**Comment by ollandos** [comment]
This would be really helpful!
