### ISSUE TITLE
The vault_pki_secret_backend_cert auto_renew feature suffers from an eventual consistency condition.

### ISSUE THREAD

**Issue by jbcraig** [hashicorp/terraform-provider-vault#835]
When auto_renew is triggered, the expiration and serial_number fields are not marked as computed.  This causes resources which reference these values not to trigger.  On a subsequent run, the changes are noted and the resources are triggered. Leading to an eventual consistency condition.

### Terraform Version
Terraform v0.12.24
+ provider.vault v2.12.0

### Affected Resource(s)
- vault_pki_secret_backend_cert

### Terraform Configuration Files
```hcl
resource "vault_pki_secret_backend_cert" "vs_cert" {
  backend               = "pki/internal"
  name                  = "test"
  ttl                   = 600
  min_seconds_remaining = 60
  auto_renew            = true

  common_name = "test.example.com"
}
```

### Expected Behavior
When the cert is triggered by auto_renew the expiration and serial_number fields must be marked for change with future values being "computed".

### Actual Behavior

1. First apply generates a new certificate
2. Subsequent plan or apply marks the resource for change but these fields still show their previous values.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` - to genereate initial certificate
2. Wait for auto_renew condition to become true
2. `terraform plan` - note these attributes retain their previous values

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-353
- GH-386

**Comment by Merenon** [comment]
Is there any estimation on when the related Pull Request will be merged?
