### ISSUE TITLE
terraform-provider-vault/website/docs/r/token.html.md refers to gpg_key directive incorrectly

### ISSUE THREAD

**Issue by earchibald-lv** [hashicorp/terraform-provider-vault#845]
PGP/GPG support has been added to token.html and the provider code reflects that `pgp_key` should be used.

However, the documentation uses `gpg_key = "keybase:my_username"` in its example.

**Comment by HorizonNet** [comment]
I think that this shouldn't be an issue anymore. It was originally solved by #1085 and the got removed in preparation of v3.0.0 in #1201.
