### ISSUE TITLE
Vault provider does not support IAM authentication with docker task role

### ISSUE THREAD

**Issue by mattis-haase** [hashicorp/terraform-provider-vault#866]
### Terraform Version
0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
- provider "vault"

### Terraform Configuration Files
```hcl
provider "vault" {
  address         = "https://vault.mycompany.com:443"
  skip_tls_verify = false
  auth_login {
    path = "auth/aws/login"
    parameters = {
      role                 = "atlantis-admin"
      iam_http_post_method = "POST"
      # this is base64 for https://sts.amazonaws.com/
      iam_request_url      = "aHR0cHM6Ly9zdHMuYW1hem9uYXdzLmNvbS8="
      # this is base64 for Action=GetCallerIdentity&Version=2011-06-15
      iam_request_body     = "QWN0aW9uPUdldENhbGxlcklkZW50aXR5JlZlcnNpb249MjAxMS0wNi0xNQ=="
    }
  }
}

```

### Expected Behavior
Provider should work

### Actual Behavior
```
Error: Error making API request.

URL: PUT https://vault.mycompany.com:443/v1/auth/aws/login
Code: 400. Errors:

* didn't supply required authentication values

  on providers.tf line 1, in provider "vault":
   1: provider "vault" {
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This is running in an ECS container. The task role of that container is allowed to assume the vault role atlantis-admin. It seems the vault provider behaves differently from vault login -method=aws.

I guess we could install vault in atlantis and run vault login instead, but it would be nice if this worked using just terraform.

**Comment by catsby** [comment]
Hello - 

I believe there is a typo in your `parameters` block; the parameter `iam_http_post_method` should instead be `iam_http_request_method`.  Please give that a try and let us know!

**Comment by yanilov** [comment]
@catsby We've encountered the same issue and an identical error message when trying to plan/apply locally.

```terraform
provider "vault" {
  address         = var.vault_url
  skip_tls_verify = false
  auth_login {
    path = "auth/aws/login"
    parameters = {
      iam_http_request_method = "POST"
      role = "my_role"
      iam_request_url = base64encode("https://sts.amazonaws.com/")
      iam_request_body = base64encode("Action=GetCallerIdentity&Version=2011-06-15")
    }
  }
}
```

and we're able to login successfully using `vault login -method=aws role=my_role`
(aws credentials stored at default location, ~/.aws/credentials).

**Comment by iusergii** [comment]
I'm quite new to terraform, not sure what is the cleanest way to write this but with this python [script](https://github.com/hashicorp/terraform-aws-vault/blob/master/examples/vault-consul-ami/auth/sign-request.py) I get signed request and update values in `vars.auto.tfvars`. 
And this works for me:
```bash
 provider "vault" {
  address = "https://vault.foo.com/"

  auth_login {
    path = "auth/aws/login"

    parameters = {
      iam_http_request_method = "POST"
      role  = var.auth_login_role
      iam_request_url  = var.iam_request_url
      iam_request_body = var.iam_request_body
      iam_request_headers = var.iam_request_headers
    }
  }
}
```
`Terraform v0.13.4`

**Comment by stpierre** [comment]
TBH it's a little incredible that this doesn't work with just, like, AWS credentials. Seems like an awful lot wheel reinvention going on here that we have to craft our own body and sign our own headers.

**Comment by bernardogza** [comment]
@stpierre I guess on terraform they don't want to allow to use access key and secret key because they would appear on the tfstate. Does any one have other ideas to retrieve the request headers with Terraform ?

**Comment by atikhono** [comment]
Signing request is a non-standard operation. This is stated clearly in the Vault AWS auth official documentation, and the parameters you need to pass. Vault CLI kindly signs for us, which we can see it in the code: https://github.com/hashicorp/vault/blob/7a66647ca62f628cef28ebc26990bfd891333d65/builtin/credential/aws/cli.go#L38.

This would be a super-nice enhancement for vault provider. This time I have to use a vault CLI wrapper in an external data source to login and parse token, and then pass that token to the vault provider. My use case is Atlantis EC2 instance that deploys to multiple Vaults across infrastructure. I'd love to do just
```
provider "vault" {
  address = https://vault.example.com
  auth_login {
    path = "auth/aws/login"
    parameters = {
      role = "atlantis"
    }
  }
}
```

**Comment by mikegreen** [comment]
To note here, this isn't docker specific but universally painful for any auth_login with AWS, docker or not.

**Comment by carnei-ro** [comment]
Same here... I would be nice if Vault Provider sign the request for us.

**Comment by mengesb** [comment]
> Signing request is a non-standard operation. This is stated clearly in the Vault AWS auth official documentation, and the parameters you need to pass. Vault CLI kindly signs for us, which we can see in the code: https://github.com/hashicorp/vault/blob/7a66647ca62f628cef28ebc26990bfd891333d65/builtin/credential/aws/cli.go#L38.
> 
> This would be a super-nice enhancement for vault provider. This time I have to use a vault CLI wrapper in an external data source to login and parse token, and then pass that token to the vault provider. My use case is Atlantis EC2 instance that deploys to multiple Vaults across infrastructure. I'd love to do just
> 
> ```
> provider "vault" {
>   address = https://vault.example.com
>   auth_login {
>     path = "auth/aws/login"
>     parameters = {
>       role = "atlantis"
>     }
>   }
> }
> ```

I'm currently doing something much the same:

```hcl
provider "vault" {
  address               = var.address
  namespace             = var.namespace

  auth_login {
    path = "auth/aws/login"
    parameters = {
      iam_http_request_method = data.external.vault.result.iam_http_request_method
      iam_request_body        = data.external.vault.result.iam_request_body
      iam_request_headers     = data.external.vault.result.iam_request_headers
      iam_request_url         = data.external.vault.result.iam_request_url
      role                    = data.external.vault.result.role
    }
  }
}
```

Making use of the `external` provider which provides the JSON content for our requirements.

It would be HIGHLY optimal if the provider would support this natively for all cloud auth backends.

**Comment by yermulnik** [comment]
Have just hit this issue too – are there any plans to implement this internally in TF Vault provider?

**Comment by yermulnik** [comment]
Also for when it gets being worked on we'd be very keen to also have an option considered to supply an AWS IAM Role Arn for Terraform to assume before attempting to authenticate to Vault. Something like this:
```
provider "vault" {
  address = […]
  namespace = "ex[…]dia/rcp"

  assume_role {
   region        = var.aws_region
    role_arn     = "arn:aws:iam::<account_id>:role/vault-role"
    external_id  = "xxxxxx"
    session_name = "vault-operator"
  }

  auth_login {
    path      = "auth/aws/login"
    namespace = "ex[…]dia/rcp"

    parameters = {
      role                       = "operator"
      iam_server_id_header_value = var.vault_server_id # optional
    }
  }
}
```

Our use case is: the pipeline in Source AWS account assumes the role in Control account which is allowed to assume roles in Target AWS accounts to create AWS resources and also to authenticate into Vault in one or several of Target AWS accounts – with TF AWS provider this is achievable at the moment, though TF Vault provider is missing this option.
Thanks in advance 🙇

**Comment by mengesb** [comment]
So just to parrot my prior comment on this... and I want to still be **very** clear that it would help immensely if the terraform provider were to natively support cloud auth engines...

I've since made my own repo with scripted solution. This is used primarily by Terraform Enterprise, so that we can use the attached AWS instance profile as an allowed auth to HashiCorp Vault, however that doesn't prevent this script from being used in other situations such as JenkinsCI, Rundeck, or other bash scripted situations, or environment variable generated situations. I did my best to avoid installable tools, such as `jq`, which isn't included in the Terraform worker container for Terraform Enterprise or Terraform Cloud, however because nearly every system includes `openssl` I make liberal use...

[mengesb/vault-iam-auth](https://github.com/mengesb/vault-iam-auth) provides for an AWS IAM method script to generate all the required bits to give to the provider, and it is designed to be exercised by the external provider. You can travel on over to my repo and have a gander, I'm still updating documentation but there's a lot there already. Currently working on the GCE authentication path, but having some shortcomings with the mock tests for the google metadata service and want to release with tests =). I might make one for the AWS EC2 method, though right now I'm focused on the Google GCE method.

**Comment by jasonodonnell** [comment]
Hi all,

I'm about to open a PR for this feature. Once merged, TFVP will be able to detect and sign the login request for AWS. I did need to add a new `auth_login` configurable `iam` (might change once reviewed by team) since the AWS auth method may be mounted in a non-standard location. Here's a small example:

```bash
$ cat aws.tf
provider "vault" {
  address         = "http://127.0.0.1:8200"
  auth_login {
    path = "auth/aws/login"
    iam = "true"
    parameters = {
      role = "dev-role-iam"
    }
  }
}

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/vault from the dependency lock file
- Using previously-installed hashicorp/vault v2.20.0

╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/vault in /home/ec2-user/.terraform.d/plugins
│
│ Skip terraform init when using provider development overrides. It is not necessary and may error unexpectedly.
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform plan
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/vault in /home/ec2-user/.terraform.d/plugins
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
$ terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/vault in /home/ec2-user/.terraform.d/plugins
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```
