### ISSUE TITLE
Changing the description of a vault_mount replaces the entire mount rather than amending it

### ISSUE THREAD

**Issue by fernando-villalba** [hashicorp/terraform-provider-vault#909]
If you change the description of a vault_mount and want to apply the changes it will destroy the mount and recreate it with the new name, this could easily lead to seriously catastrophic consequences. 

The provider should be smart enough to just amend the description rather than recreate the entire mount.

```
resource "vault_mount" "kv2" {
  path        = "kv"
  type        = "kv-v2"
  description = "If you change me I will destroy and recreate"
}
```

**Comment by jasonodonnell** [comment]
Thanks for the report @fernando-villalba, we'll take a look.

**Comment by fernando-villalba** [comment]
Amazing! Thank you very much for implementing this so quickly!
