### ISSUE TITLE
vault_aws_secret_backend_role: policy_arns can't be set to empty list

### ISSUE THREAD

**Issue by jeremiahsnapp** [hashicorp/terraform-provider-vault#925]
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/vault v2.16.0
```

### Affected Resource(s)

`vault_aws_secret_backend_role`

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend" "aws" {
  path        = "account/dynamic/aws"
  description = "Generate STS credentials for the AWS account"

  region = "us-west-2"

  default_lease_ttl_seconds = (3 * 3600)
  max_lease_ttl_seconds     = (8 * 3600)
}

resource "vault_aws_secret_backend_role" "default" {
  backend         = vault_aws_secret_backend.aws.path
  name            = "default"
  credential_type = "assumed_role"
  role_arns       = ["arn:aws:iam::12345678:role/vault-secret-backend"]
  default_sts_ttl = (2 * 3600)

  policy_arns = [ "arn:aws:iam::aws:policy/PowerUserAccess" ]
}
```

### Expected Behavior
What should have happened?

`policy_arns` should be set to an empty list when the `policy_arns` attribute is commented out.

### Actual Behavior
What actually happened?

`terraform plan` recognizes that `policy_arns` should be changed but `terraform apply` does not make the change.

Here is the `terraform plan` output.

```
Terraform will perform the following actions:

  # vault_aws_secret_backend_role.default will be updated in-place
  ~ resource "vault_aws_secret_backend_role" "default" {
        backend         = "account/dynamic/aws"
        credential_type = "assumed_role"
        default_sts_ttl = 7200
        iam_groups      = []
        id              = "account/dynamic/aws/roles/default"
        max_sts_ttl     = 0
        name            = "default"
      ~ policy_arns     = [
          - "arn:aws:iam::aws:policy/PowerUserAccess",
        ]
        role_arns       = [
            "arn:aws:iam::12345678:role/vault-secret-backend",
        ]
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Use the HCL code above so `policy_arns` gets set to `[ "arn:aws:iam::aws:policy/PowerUserAccess" ]`
1. `terraform apply`
1. `policy_arns` is properly set at this point
1. Comment out the `policy_arns` attribute to set it back to `[]`
1. `terraform apply`
1. `policy_arns` incorrectly remains set to `[ "arn:aws:iam::aws:policy/PowerUserAccess" ]`

### References

I believe the `if len(policyARNs) != 0` conditional [here](https://github.com/hashicorp/terraform-provider-vault/blob/master/vault/resource_aws_secret_backend_role.go#L146) is causing the problem. It doesn't allow `policy_arns` to get set to an empty list. Judging by the surrounding code I believe this is also a problem for the `policy_document`, `role_arns` and `iam_groups` attributes but I haven't tested those.

**Comment by jasonodonnell** [comment]
Thanks for the report @jeremiahsnapp, I'll take a look!

**Comment by ppejovic** [comment]
There is equivalent behaviour in the `vault_aws_auth_backend_role` resource also. Removing any of the `backend_iam_*` arguments, or setting them to `null` shows as a delete in the `plan` but they aren't removed by the `apply`. I can raise as a separate issue and link here.
