### ISSUE TITLE
Documentation: token_num_uses

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-provider-vault#930]
In the terraform-provider-vault documentation, aws_auth_backend_role, for example, 
token_num_uses is defined as The period, if any, in number of seconds to set on the token.

However in the Vault documentation,
token_num_uses is defined as The maximum number of times a generated token may be used (within its lifetime); 0 means unlimited. If you require the token to have the ability to create child tokens, you will need to set this value to 0.

and when I tested setting this value, it is in fact setting the token_num_uses per the Vault definition.

**Comment by jasonodonnell** [comment]
@assareh Thanks for the report, I'll take a look!
