### ISSUE TITLE
vault_jwt_auth_backend for type oidc: provider_config is parsing everything as String

### ISSUE THREAD

**Issue by tx-kstav** [hashicorp/terraform-provider-vault#957]
Hello, 

following PR [943](https://github.com/hashicorp/terraform-provider-vault/pull/943), and comments there, I face the following issue. 

When trying to create a vault_jwt_auth_backend with oidc type for gsuite (documentation guide [here](https://www.vaultproject.io/docs/auth/jwt_oidc_providers), everything in "provider_config" gets parsed as String. This means that the boolean variables "fetch_groups" & "fetch_user_info" and the int variable "groups_recurse_max_depth" can not be used, as their respective value types are expected.

In addition, trying to customize/edit the provider I have stumbled upon an issue which may be a code bug, so I am reporting this as well. See below.

### Terraform Version

```
terraform -v                                                         
Terraform v0.14.4
Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
`vault_jwt_auth_backend`

### Terraform Configuration Files
```
resource "vault_jwt_auth_backend" "this" {
  path                                = "oidc"
  type                                = "oidc"
  oidc_discovery_url         = "https://accounts.google.com"
  oidc_client_id                 =  "xxxxxx.apps.googleusercontent.com"
  oidc_client_secret          =  "xxxxxx"
  default_role                    = "xxxxxx"
  provider_config = {
    provider                                = "gsuite"
    gsuite_service_account       = "/path/to/service-account.json"
    gsuite_admin_impersonate  = "xxx@xxxxxx.com"
    fetch_groups                        = true
    fetch_user_info                    = true
    groups_recurse_max_depth = 5
  }
}
```

### Debug Output
See below.

### Expected Behavior
Ideally, the oidc backend should be created, with the correct configuration.

### Actual Behavior
```
  + resource "vault_jwt_auth_backend" "this" {
      + accessor           = (known after apply)
      + default_role       = "readonly"
      + id                 = (known after apply)
      + oidc_client_id     = "xxxxxxx"
      + oidc_client_secret = (sensitive value)
      + oidc_discovery_url = "xxxxxxx"
      + path               = "oidc"
      + provider_config    = {
          + "fetch_groups"             = "true"
          + "fetch_user_info"          = "true"
          + "groups_recurse_max_depth" = "5"
          + "gsuite_admin_impersonate" = "xxxxxx"
          + "gsuite_service_account"   = "/etc/config/vault-sa-key.json"
          + "provider"                 = "gsuite"
        }
      + tune               = (known after apply)
      + type               = "oidc"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vault_jwt_auth_backend.this: Creating...

Error: error updating configuration to Vault for path oidc: Error making API request.

URL: PUT https://xxxxxxxxxxxxxx/v1/auth/oidc/config

Code: 400. Errors:

* invalid provider_config: error initializing "gsuite" provider_config: 3 error(s) decoding:

* 'fetch_groups' expected type 'bool', got unconvertible type 'string'
* 'fetch_user_info' expected type 'bool', got unconvertible type 'string'
* 'groups_recurse_max_depth' expected type 'int', got unconvertible type 'string'

  on main.tf line 1, in resource "vault_jwt_auth_backend" "this":
   1: resource "vault_jwt_auth_backend" "this" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Attempt to create a oidc auth backend of type gsuite.

### Important Factoids
I have attempted to fix the issue in [WIP: PR 953](https://github.com/hashicorp/terraform-provider-vault/pull/953), but another error is thrown:
```
2021-01-26T11:49:39.481+0200 [DEBUG] plugin.terraform-provider-vault_v2.18.0_x4: 2021/01/26 11:49:39 [DEBUG] Updating auth oidc2 in Vault
2021/01/26 11:49:39 [DEBUG] vault_jwt_auth_backend.this: apply errored, but we're indicating that via the Error pointer rather than returning it: error updating configuration to Vault for path oidc2: json: unsupported type: schema.SchemaSetFunc
2021/01/26 11:49:39 [TRACE] EvalMaybeTainted: vault_jwt_auth_backend.this encountered an error during creation, so it is now marked as tainted
2021/01/26 11:49:39 [TRACE] EvalWriteState: recording 0 dependencies for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalWriteState: writing current state object for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalApplyProvisioners: vault_jwt_auth_backend.this is tainted, so skipping provisioning
2021/01/26 11:49:39 [TRACE] EvalMaybeTainted: vault_jwt_auth_backend.this was already tainted, so nothing to do
2021/01/26 11:49:39 [TRACE] EvalWriteState: recording 0 dependencies for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] EvalWriteState: writing current state object for vault_jwt_auth_backend.this
2021/01/26 11:49:39 [TRACE] vertex "vault_jwt_auth_backend.this": visit complete
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/vault\"] (close)" errored, so skipping
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/26 11:49:39 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 5
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/26 11:49:39 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
Error: error updating configuration to Vault for path oidc2: json: unsupported type: schema.SchemaSetFunc

on main.tf line 13, in resource "vault_jwt_auth_backend" "this":
13: resource "vault_jwt_auth_backend" "this" {
```

### References
https://github.com/hashicorp/terraform-provider-vault/pull/953
https://github.com/hashicorp/terraform-provider-vault/pull/943
https://github.com/hashicorp/terraform-provider-vault/issues/828

**Comment by jasonodonnell** [comment]
Hi @tx-kstav, we're taking a look at this!

**Comment by jasonodonnell** [comment]
Fix proposed here: https://github.com/hashicorp/terraform-provider-vault/pull/960

**Comment by sam-allen-skyspecs** [comment]
Is there a workaround one could use while we wait for this to merge?  I am blocked by this issue presently.

**Comment by bluemalkin** [comment]
I'm also interested in a workaround. Especially how to put the service account key json contents in

**Comment by memes** [comment]
@bluemalkin - here's a link to how I'm working around the issue: https://gist.github.com/memes/3267553b31ba0f662b8fb601560c53b7

* Terraform: add a lifecycle declaration to ignore changes to provider_config
* Shell: apply the missing configuration params from command line with `vault`

**Comment by bluemalkin** [comment]
Thanks @memes 

Wondering whether you've managed to get Gsuite to work all configured via Terraform ? I have been struggling with all the configs `vault_jwt_auth_backend_role` group mapping etc.. The Vault documentation is lacking.

**Comment by memes** [comment]
Glad to help @bluemalkin. I updated the gist to include all of the `oidc.tf` I use in my lab, along with some supporting files. Everything GSuite/OIDC is managed through `oidc.tf` but it does refer to an admin policy that I define in `main.tf` (I included an edited snippet for that too).

My approach allows all users in the GSuite domain to authenticate to Vault and get a token with `default` policy and those in an admins group get a token with `admin` policy. In my lab environment with limited user pool/MFA/etc. that's good enough, but you'll want to change that for a prod environment.

**Comment by sam-allen-skyspecs** [comment]
@bluemalkin There's definitely a bit of clarity which could be added to the docs, though personally, I found the GSuite side to be over-documented to the point of it hard to grok and many topical paths to traverse before it was clear what to do.  [This article](https://vagarwal2.medium.com/hashicorp-vault-groups-integration-with-google-g-suite-6df8951d7573) was helpful to me in getting things going.  It does work quite nicely once you get the pieces together.  In my mind it would be really clarifying for some of the Vault examples to list relevant examples from the GSuite provider templates, even if one didn't intend to use Terraform to manage their GSuite implementation, as it seems like it would simmer down what the actual contract is.

**Comment by jasonodonnell** [comment]
When fixing this bug I introduced an upgrade error. We're looking into solutions internally but this bug was disclosed here https://github.com/hashicorp/terraform-provider-vault/issues/1112 and a small workaround provided if this is blocking you. Sorry for the inconvenience!

**Comment by Keramblock** [comment]
So, is there any fix/workaround for now? I getting same error on 2.22.1 =(
