### ISSUE TITLE
docs for vault_mount

### ISSUE THREAD

**Issue by SvenDowideit** [hashicorp/terraform-provider-vault#979]
I can't find any docs for creating a new (for example) kv secrets engine - I'm presuming I should use vault_generic_endpoint, but its very opaque.

I'm working towards getting total non-vault users to stop emailing each other passwords, and the apparent lack of docs that use the words / jargon that a user sees on the vault web ui or cli makes onboarding surprisingly complicated.

does anyone want to give me enough stuff to put in a Docs PR? or just to work on that as is?

**Comment by SvenDowideit** [comment]
If you're not going to list all the `types` in the docs, at least tell the user how to find out what they are, and which are installed on their system - `type="kv-v2"` is utterly un-guessable by someone that needs to read the docs to use it.

**Comment by mikegreen** [comment]
I would think you'd want to use vault_mount - seen this? 
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/mount

**Comment by SvenDowideit** [comment]
yes, exactly - and yet there's nothing in that doc to give a user of the vault cli or web UI any idea what valid types exist, or what the magic string that makes them go are - users should be able to read the docs, and use it...

**Comment by mikegreen** [comment]
Yeah, I could see a link in there showing which mount types/syntax. 
Here are a few examples  you could paste in. Cant PR it anytime soon, but I agree could be better.
```
resource "vault_mount" "version2-example" {
  path        = "version2-example"
  type        = "kv-v2"
  description = "This is an example KV Version 2 secret engine mount"
}

resource "vault_mount" "transit-example" {
  path                      = "transit-example-01"
  type                      = "transit"
  default_lease_ttl_seconds = 3600
  max_lease_ttl_seconds     = 86400
  options = {
    convergent_encryption = false
  }
  description = "This is an example transit secret engine mount"
}
```
