### ISSUE TITLE
How to check if Vault namespace already exist - getting "* namespace "mynamespace/" already exists"

### ISSUE THREAD

**Issue by kiich** [hashicorp/terraform-provider-vault#995]
Hello! Wondering if I have missed something in the documentation for me to query namespace but i am getting:

```
Error: error writing to Vault: Error making API request.

URL: PUT https://vault.com.:443/v1/sys/namespaces/mynamespace
Code: 400. Errors:

* namespace "mynamespace/" already exists
```

which is fine that namespace does exist indeed.
However the TF i am running does not share state with the one that created the namespace and the TF needs to make the namespace if it does not exist. if it does, it needs to then use it as part of the provider.

The TF at the moment does something like:
```
provider "vault" {
  address = var.vault_address
}

resource "vault_namespace" "mynamespace" {
  path = var.vault_namespace
}

provider vault {
  alias     = "mynamespace"
  address   = var.vault_address
  namespace = vault_namespace.mynamespace.path
}
```

And I was looking for a data resource that can fetch if a namespace exist or not to check but i could not find any. Is there any way to achieve what I would like to do?

I see in the doc that `curl` can actually query this but was wondering if there is a "native" way of doing this.

thanks

```
terraform version
Terraform v0.13.5
```

**Comment by tmatilai** [comment]
Terraform is maybe really not meant to be used this way, but if #1769 gets merged, you could do something like:

```terraform
data "vault_namespaces" "all" {}

resource "vault_namespace" "mynamespace" {
  count = contains(data.vault_namespaces.all.paths, var.vault_namespace) ? 1 : 0
  path  = var.vault_namespace
}
```

At the moment one ugly workaround could be to use the [external data source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) to run `curl` or `vault`. But authentication might get hairy.
