### ISSUE TITLE
vault_auth_backend description change shouldn't create new mount

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/terraform-provider-vault#998]
### Affected Resource(s)
`vault_auth_backend`

### Expected Behavior
Altering `description` should not force replacement of resource.

### Actual Behavior
Description change forces new resource.

### Steps to Reproduce
Apply terraform instantiating a `vault_auth_backend`. Change the `description` field once the resource exists.

**Comment by holtwilkins** [comment]
Is this also the case for `vault_aws_secret_backend`?

**Comment by xeivieni** [comment]
It also applies to `vault_auth_backend`. 

A side effect to that is that any `vault_aws_auth_backend_role` attached to a `vault_auth_backend` which description changes isn't recreated on the new auth backend.

**Comment by holtwilkins** [comment]
Also the case for `vault_azure_secret_backend` it seems

**Comment by maxb** [comment]
The original issue in the title and main description has been fixed via #1439.

It's not clear to me whether subsequent comments about aws and azure resources need any further work, but I'd suggest closing this issue and filing new ones if there is other work still needed.

**Comment by hsimon-hashicorp** [comment]
> The original issue in the title and main description has been fixed via #1439.
> 
> It's not clear to me whether subsequent comments about aws and azure resources need any further work, but I'd suggest closing this issue and filing new ones if there is other work still needed.

Max, you make my job so much easier. Thanks again. :)
